### ISSUE TITLE
Exception in thread Thread-1 & Caught Exception from bitcoind

### ISSUE THREAD

**Issue by rllola** [blockstack/blockstack-core#156]
I had this error in ~.blockstore/blockstore.log.indexer : 

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 326, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 230, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

[ERROR] [transactions:94] (11215) 

[11223] Caught Exception from bitcoind
[ERROR] [transactions:95] (11215) ''
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/transactions.py", line 83, in getrawtransaction
    tx = bitcoind.getrawtransaction( txid, verbose )
  File "/usr/local/lib/python2.7/dist-packages/bitcoinrpc/authproxy.py", line 114, in __call__
    response = self._get_response()
  File "/usr/local/lib/python2.7/dist-packages/bitcoinrpc/authproxy.py", line 134, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```

**Comment by muneeb-ali** [comment]
Which branch are you using? Is the version you're using installed via pip install blockstore or directly from Github?

**Comment by rllola** [comment]
I used `pip install blockstore`.
I restarted blockstore and it does work again.

**Comment by jcnelson** [comment]
The latter exception can be ignored (it only indicates that a transient network error occurred, like a timeout).  I have since bumped up the number of RPC threads in our bitcoind fleet to help make these rarer.

The former exception is new to me.  How much free RAM does your host have?

**Comment by rllola** [comment]
I am running it on a bithost server. There is only blockstore running.
result of the command `free -m` : 
```
             total       used       free     shared    buffers     cached
Mem:           490        375        114          0          0          9
-/+ buffers/cache:        365        124
Swap:            0          0          0
```

**Comment by jcnelson** [comment]
That's probably not enough free RAM.  I'll see if I can get the RAM usage down before the next update.

**Comment by jcnelson** [comment]
Should be fixed in the `jude` branch of virtualchain, which no longer requires as much RAM.

**Comment by rllola** [comment]
Ok thanks :+1: . I will try this week end.

**Comment by jcnelson** [comment]
The memory usage in Blockstack has been reduced 20x in the 0.14 release.  I'm going to go ahead and close this issue; please re-open if the problem persists.
