### ISSUE TITLE
DHT profile lookup timeouts 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#176]
Periodically experiencing DHT timeouts on my node in Hong Kong.

```
root@blockchainid:~# blockstore-cli lookup larry.id
[ERROR] [storage:314] (26139) timed out
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/storage.py", line 312, in get_immutable_data
    data = handler.get_immutable_handler( data_key )
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/drivers/dht.py", line 151, in get_immutable_handler
    return dht_get_key(key)
  File "/usr/local/lib/python2.7/dist-packages/blockstore_client/drivers/dht.py", line 101, in dht_get_key
    ret = dht_server.get( data_key )
  File "/usr/local/lib/python2.7/dist-packages/basicrpc/basicrpc.py", line 46, in default
    return self.request()
  File "/usr/local/lib/python2.7/dist-packages/basicrpc/basicrpc.py", line 82, in request
    c = self.sock.recv(1)
timeout: timed out
[ERROR] [client:281] (26139) Failed to load user record '3ffe2c8bfd911ff17acc1b1db49c6f3e698f3c65'
{
    "error": "User data could not be loaded from storage"
}
root@blockchainid:~# 
```

I'm not currently running a DHT mirror, however, I am running a DHT node.

Below are traceroutes to the three default DHT bootstrapping nodes:

```
root@blockchainid:~# traceroute dht.blockstack.org
traceroute to dht.blockstack.org (54.173.110.67), 30 hops max, 60 byte packets
 1  192.168.188.1 (192.168.188.1)  0.661 ms  0.664 ms  0.790 ms
 2  175.45.53.42 (175.45.53.42)  3.256 ms  3.249 ms  3.251 ms
 3  10.80.1.41 (10.80.1.41)  3.162 ms  3.337 ms  3.331 ms
 4  175.45.53.205 (175.45.53.205)  4.632 ms  4.631 ms  4.671 ms
 5  115.160.187.41 (115.160.187.41)  4.716 ms 115.160.187.103 (115.160.187.103)  4.611 ms 115.160.187.41 (115.160.187.41)  4.656 ms
 6  80.77.0.181 (80.77.0.181)  4.621 ms  4.215 ms  3.618 ms
 7  ge-5-1-0.0.cjr04.hkg003.flagtel.com (62.216.128.65)  245.650 ms ge-5-1-0.0.cjr03.hkg003.flagtel.com (62.216.128.29)  222.877 ms  222.841 ms
 8  so-1-1-0.0.pjr02.hkg005.flagtel.com (85.95.25.213)  221.466 ms ge-5-3-0.0.pjr02.hkg005.flagtel.com (85.95.25.89)  224.042 ms  222.731 ms
 9  ge-0-0-0.0.pjr02.wad001.flagtel.com (85.95.26.90)  227.908 ms  227.804 ms ge-3-0-0.0.pjr02.wad001.flagtel.com (85.95.26.101)  222.511 ms
10  so-2-1-0.0.pjr01.lax002.flagtel.com (85.95.25.17)  211.964 ms so-0-0-0.0.pjr02.lax002.flagtel.com (85.95.26.85)  172.628 ms  172.587 ms
11  xe-8-1-0.0.pjr02.nyc007.flagtel.com (85.95.26.21)  217.076 ms xe-2-3-0.0.pjr02.nyc005.flagtel.com (85.95.26.13)  219.705 ms xe-8-1-0.0.pjr02.nyc007.flagtel.com (85.95.26.21)  217.020 ms
12  xe-2-0-0.0.pjr02.nyc005.flagtel.com (85.95.25.149)  220.115 ms  221.323 ms  220.040 ms
13  equinix01-iad2.amazon.com (206.126.236.68)  225.180 ms 54.239.111.254 (54.239.111.254)  256.672 ms equinix01-iad2.amazon.com (206.126.236.68)  226.418 ms
14  54.239.111.254 (54.239.111.254)  256.590 ms 54.239.108.201 (54.239.108.201)  235.543 ms 54.239.111.254 (54.239.111.254)  240.533 ms
15  54.239.109.47 (54.239.109.47)  215.561 ms  216.854 ms 54.239.109.13 (54.239.109.13)  224.618 ms
16  * * 205.251.245.250 (205.251.245.250)  231.130 ms
17  * * *
18  * * *
19  * * *
20  * * *
21  * *^C
root@blockchainid:~# traceroute dht.halfmoon.com
dht.halfmoon.com: Name or service not known
Cannot handle "host" cmdline arg `dht.halfmoon.com' on position 1 (argc 1)
root@blockchainid:~# traceroute dht.halfmoonlabs.com
traceroute to dht.halfmoonlabs.com (52.20.194.97), 30 hops max, 60 byte packets
 1  192.168.188.1 (192.168.188.1)  0.879 ms  0.900 ms  1.004 ms
 2  175.45.53.42 (175.45.53.42)  3.913 ms  3.879 ms  3.906 ms
 3  10.80.1.41 (10.80.1.41)  3.847 ms  3.876 ms  4.640 ms
 4  175.45.53.205 (175.45.53.205)  4.629 ms  4.637 ms  4.640 ms
 5  115.160.187.103 (115.160.187.103)  5.846 ms  5.816 ms  5.823 ms
 6  80.77.0.181 (80.77.0.181)  5.693 ms  3.388 ms  4.311 ms
 7  ge-5-1-0.0.cjr04.hkg003.flagtel.com (62.216.128.65)  229.983 ms ge-5-1-0.0.cjr03.hkg003.flagtel.com (62.216.128.29)  220.736 ms ge-5-1-0.0.cjr04.hkg003.flagtel.com (62.216.128.65)  229.904 ms
 8  so-1-1-0.0.pjr02.hkg005.flagtel.com (85.95.25.213)  219.370 ms so-0-2-0.0.pjr01.hkg005.flagtel.com (85.95.25.217)  215.411 ms ge-5-3-0.0.pjr02.hkg005.flagtel.com (85.95.25.89)  224.571 ms
 9  so-1-0-0.0.pjr01.wad001.flagtel.com (85.95.25.193)  223.202 ms so-2-2-0.0.pjr01.wad001.flagtel.com (85.95.25.37)  221.863 ms  221.839 ms
10  so-2-1-0.0.pjr01.lax002.flagtel.com (85.95.25.17)  212.617 ms so-0-0-0.0.pjr02.lax002.flagtel.com (85.95.26.85)  170.084 ms so-2-1-0.0.pjr01.lax002.flagtel.com (85.95.25.17)  215.962 ms
11  xe-2-3-0.0.pjr02.nyc005.flagtel.com (85.95.26.13)  230.422 ms  230.400 ms xe-2-0-1.0-pjr02.nyc007.flagtel.com (85.95.26.161)  213.276 ms
12  xe-2-0-0.0.pjr02.nyc005.flagtel.com (85.95.25.149)  220.377 ms equinix01-iad2.amazon.com (206.126.236.68)  234.837 ms xe-2-0-0.0.pjr02.nyc005.flagtel.com (85.95.25.149)  217.701 ms
13  equinix01-iad2.amazon.com (206.126.236.68)  225.617 ms  225.578 ms 54.239.111.242 (54.239.111.242)  241.678 ms
14  54.239.108.199 (54.239.108.199)  237.354 ms 54.239.111.238 (54.239.111.238)  239.887 ms 54.239.111.246 (54.239.111.246)  246.572 ms
15  205.251.245.234 (205.251.245.234)  238.522 ms 54.239.108.199 (54.239.108.199)  227.945 ms 54.239.108.233 (54.239.108.233)  218.665 ms
16  205.251.245.234 (205.251.245.234)  227.804 ms * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * *^C
root@blockchainid:~# traceroute dht.onename.com
traceroute to dht.onename.com (54.174.135.157), 30 hops max, 60 byte packets
 1  192.168.188.1 (192.168.188.1)  1.370 ms  1.383 ms  1.510 ms
 2  175.45.53.42 (175.45.53.42)  5.019 ms  4.998 ms  5.017 ms
 3  10.80.1.41 (10.80.1.41)  4.966 ms  4.996 ms  4.995 ms
 4  175.45.53.205 (175.45.53.205)  5.004 ms  6.066 ms  6.055 ms
 5  115.160.187.41 (115.160.187.41)  7.332 ms  7.308 ms  7.312 ms
 6  80.77.0.181 (80.77.0.181)  5.975 ms  3.872 ms  3.909 ms
 7  ge-5-1-0.0.cjr03.hkg003.flagtel.com (62.216.128.29)  220.565 ms ge-5-1-0.0.cjr04.hkg003.flagtel.com (62.216.128.65)  229.181 ms ge-5-1-0.0.cjr03.hkg003.flagtel.com (62.216.128.29)  220.509 ms
 8  so-1-1-0.0.pjr02.hkg005.flagtel.com (85.95.25.213)  222.498 ms ge-5-3-0.0.pjr02.hkg005.flagtel.com (85.95.25.89)  223.786 ms so-0-2-0.0.pjr01.hkg005.flagtel.com (85.95.25.217)  214.999 ms
 9  so-2-2-0.0.pjr01.wad001.flagtel.com (85.95.25.37)  220.414 ms ge-3-0-0.0.pjr02.wad001.flagtel.com (85.95.26.101)  222.451 ms so-1-0-0.0.pjr01.wad001.flagtel.com (85.95.25.193)  222.412 ms
10  so-3-0-0.0.pjr01.lax002.flagtel.com (85.95.26.1)  226.293 ms so-0-0-0.0.pjr02.lax002.flagtel.com (85.95.26.85)  175.467 ms  169.798 ms
11  xe-2-3-0.0.pjr02.nyc005.flagtel.com (85.95.26.13)  220.890 ms  219.563 ms xe-2-0-1.0-pjr02.nyc007.flagtel.com (85.95.26.161)  210.380 ms
12  xe-2-0-0.0.pjr02.nyc005.flagtel.com (85.95.25.149)  224.669 ms equinix01-iad2.amazon.com (206.126.236.68)  233.815 ms  236.384 ms
13  54.239.111.254 (54.239.111.254)  244.265 ms equinix01-iad2.amazon.com (206.126.236.68)  226.492 ms  229.028 ms
14  54.239.111.250 (54.239.111.250)  254.030 ms 54.239.109.47 (54.239.109.47)  227.646 ms 54.239.108.167 (54.239.108.167)  236.768 ms
15  54.239.109.47 (54.239.109.47)  220.457 ms 205.251.245.250 (205.251.245.250)  236.077 ms 54.239.108.167 (54.239.108.167)  225.890 ms
16  * * 205.251.245.244 (205.251.245.244)  224.418 ms
17  * * *
18  * * *
19  * * *
20  * * *
21  * *^C
root@blockchainid:~# 

```

**Comment by jcnelson** [comment]
Shouldn't be a problem anymore, since all blockstack nodes can serve zonefiles directly and profiles get served from the user's choice of cloud storage.
