### ISSUE TITLE
Ubuntu installation issues

### ISSUE THREAD

**Issue by JustinDrake** [blockstack/blockstack-core#246]
I'm having issues installing blockstack-core on Ubuntu. I have run `sudo apt-get update && sudo apt-get install -y python-pip python-dev libssl-dev` first without issues, but then `sudo pip install blockstack` fails (see below).

```
Requirement already satisfied (use --upgrade to upgrade): blockstack in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): virtualchain>=0.0.13.0 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already satisfied (use --upgrade to upgrade): protocoin>=0.1 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already satisfied (use --upgrade to upgrade): blockstack-profiles>=0.4.4 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already satisfied (use --upgrade to upgrade): pybitcoin>=0.9.9 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already satisfied (use --upgrade to upgrade): blockstack-zones>=0.1.6 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already satisfied (use --upgrade to upgrade): blockstack-storage-drivers>=0.0.13.6 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already satisfied (use --upgrade to upgrade): blockstack-utxo>=0.0.13.0 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already satisfied (use --upgrade to upgrade): defusedxml>=0.4.1 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already satisfied (use --upgrade to upgrade): keylib>=0.0.5 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already satisfied (use --upgrade to upgrade): mixpanel>=4.3.1 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6.1 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already satisfied (use --upgrade to upgrade): bitcoin>=1.1.42 in /usr/local/lib/python2.7/dist-packages (from virtualchain>=0.0.13.0->blockstack)
Requirement already satisfied (use --upgrade to upgrade): python-bitcoinrpc==0.1 in /usr/local/lib/python2.7/dist-packages (from virtualchain>=0.0.13.0->blockstack)
Requirement already satisfied (use --upgrade to upgrade): utilitybelt>=0.2.6 in /usr/local/lib/python2.7/dist-packages (from virtualchain>=0.0.13.0->blockstack)
Requirement already satisfied (use --upgrade to upgrade): ecdsa>=0.10 in /usr/local/lib/python2.7/dist-packages (from protocoin>=0.1->blockstack)
Downloading/unpacking cryptography>=1.2.3 (from blockstack-profiles>=0.4.4->blockstack)
  Running setup.py (path:/tmp/pip_build_root/cryptography/setup.py) egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking jsontokens>=0.0.2 (from blockstack-profiles>=0.4.4->blockstack)
  Downloading jsontokens-0.0.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/jsontokens/setup.py) egg_info for package jsontokens
    
Downloading/unpacking requests>=2.4.3 (from pybitcoin>=0.9.9->blockstack)
Downloading/unpacking commontools==0.1.0 (from pybitcoin>=0.9.9->blockstack)
  Downloading commontools-0.1.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/commontools/setup.py) egg_info for package commontools
    
Downloading/unpacking keychain>=0.1.4 (from pybitcoin>=0.9.9->blockstack)
  Downloading keychain-0.1.4.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/keychain/setup.py) egg_info for package keychain
    
Downloading/unpacking boto>=2.38.0 (from blockstack-storage-drivers>=0.0.13.6->blockstack)
Downloading/unpacking basicrpc>=0.0.2 (from blockstack-storage-drivers>=0.0.13.6->blockstack)
  Downloading basicrpc-0.0.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/basicrpc/setup.py) egg_info for package basicrpc
    
Downloading/unpacking idna>=2.0 (from cryptography>=1.2.3->blockstack-profiles>=0.4.4->blockstack)
Downloading/unpacking pyasn1>=0.1.8 (from cryptography>=1.2.3->blockstack-profiles>=0.4.4->blockstack)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/lib/python2.7/dist-packages (from cryptography>=1.2.3->blockstack-profiles>=0.4.4->blockstack)
Downloading/unpacking setuptools>=11.3 (from cryptography>=1.2.3->blockstack-profiles>=0.4.4->blockstack)
Downloading/unpacking enum34 (from cryptography>=1.2.3->blockstack-profiles>=0.4.4->blockstack)
  Downloading enum34-1.1.6-py2-none-any.whl
Downloading/unpacking ipaddress (from cryptography>=1.2.3->blockstack-profiles>=0.4.4->blockstack)
  Downloading ipaddress-1.0.17-py2-none-any.whl
Downloading/unpacking cffi>=1.4.1 (from cryptography>=1.2.3->blockstack-profiles>=0.4.4->blockstack)
  Running setup.py (path:/tmp/pip_build_root/cffi/setup.py) egg_info for package cffi
    
Downloading/unpacking bitmerchant>=0.1.8 (from keychain>=0.1.4->pybitcoin>=0.9.9->blockstack)
  Downloading bitmerchant-0.1.8-py2.py3-none-any.whl
Downloading/unpacking pycparser (from cffi>=1.4.1->cryptography>=1.2.3->blockstack-profiles>=0.4.4->blockstack)
  Running setup.py (path:/tmp/pip_build_root/pycparser/setup.py) egg_info for package pycparser
    
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Downloading/unpacking cachetools>=1.1.1 (from bitmerchant>=0.1.8->keychain>=0.1.4->pybitcoin>=0.9.9->blockstack)
  Downloading cachetools-2.0.0-py2.py3-none-any.whl
Downloading/unpacking base58>=0.2.1 (from bitmerchant>=0.1.8->keychain>=0.1.4->pybitcoin>=0.9.9->blockstack)
  Downloading base58-0.2.3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/base58/setup.py) egg_info for package base58
    
Installing collected packages: cryptography, jsontokens, requests, commontools, keychain, boto, basicrpc, idna, pyasn1, setuptools, enum34, ipaddress, cffi, bitmerchant, pycparser, cachetools, base58
  Running setup.py install for cryptography
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip_build_root/cryptography/setup.py", line 334, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1028, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-IeKwQz-record/install-record.txt --single-version-externally-managed --compile:
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

 #include <ffi.h>

                 ^

compilation terminated.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/cryptography/setup.py", line 334, in <module>

    **keywords_with_side_effects(sys.argv)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain

    return installer(requirement)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1028, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-IeKwQz-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cryptography
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by pandu-rao** [comment]
Did you do `apt-get install libffi-dev`?

**Comment by JustinDrake** [comment]
@pandu-rao I didn't. Where is that documented? This particular error seems to have gone with `libffi-dev`.

**Comment by pandu-rao** [comment]
I saw it here:
https://github.com/blockstack/blockstack-cli#debian--ubuntu
