### ISSUE TITLE
Error in Server run 0.14

### ISSUE THREAD

**Issue by doodlemania2** [blockstack/blockstack-core#255]
[ERROR] [db:482] (19623.140283954771712) UNIQUE constraint failed: history.txid, history.history_id, history.block_id, history.vtxindex
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/nameset/db.py", line 467, in namedb_query_execute
    ret = cur.execute( query, values )
IntegrityError: UNIQUE constraint failed: history.txid, history.history_id, history.block_id, history.vtxindex
[2016-11-01 21:55:54,956] [ERROR] [db:483] (19623.140283954771712) FATAL: failed to execute query (INSERT INTO history (block_id,history_data,history_id,op,txid,vtxindex) VALUES (?,?,?,?,?,?);, (374234, '{"value_hash": "8b3fe3a9ecb162cb7968d5a889fbf159c9f317cb", "last_renewed": 373653, "last_creation_op": ";", "sender": "76a914b2f96e6718a678b97327ffbb15ff5a8a7fd3c10188ac", "sender_pubkey": "03ece9b12bd0395b15de83322e805a08b0a82d895cf3e6ad6e718fc61ca56049d1", "revoked": false, "block_number": 373653, "consensus_hash": null, "namespace_block_number": 373601, "preorder_block_number": 373653, "txid": "3fefa4856bff5a0952d82ff5261831e88f9103dbc43d476b4ec91c0c45f83d7e", "importer": "76a9148d76b705a25b2d5456d4ceeb545e7f7e71493e6688ac", "transfer_send_block_id": null, "address": "1HKL5w9jotV9iizhd8u9fT1SGUU6uxY5ZN", "op_fee": 25600000.0, "preorder_hash": "5f9a723a98c26866c266656b922dcefdaea10ea1", "importer_address": "1DtzVWMDtgjMCaJB6XXQN28oR1uHvUDhhk", "first_registered": 373653, "vtxindex": 100, "op": ";"}', 'qy.id', u';', '3fefa4856bff5a0952d82ff5261831e88f9103dbc43d476b4ec91c0c45f83d7e', 100))
[2016-11-01 21:55:54,958] [ERROR] [db:484] (19623.140283954771712)   File "/usr/local/bin/blockstack-server", line 42, in <module>
    run_blockstackd()

  File "/usr/local/lib/python2.7/dist-packages/blockstack/blockstackd.py", line 2223, in run_blockstackd
    exit_status = run_server( foreground=args.foreground, expected_snapshots=expected_snapshots, port=int(args.port) )

  File "/usr/local/lib/python2.7/dist-packages/blockstack/blockstackd.py", line 1776, in run_server
    running = index_blockchain(expected_snapshots=expected_snapshots)

  File "/usr/local/lib/python2.7/dist-packages/blockstack/blockstackd.py", line 1642, in index_blockchain
    rc = virtualchain_hooks.sync_blockchain( bt_opts, current_block, expected_snapshots=expected_snapshots, tx_filter=blockstack_tx_filter )

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/nameset/virtualchain_hooks.py", line 466, in sync_blockchain
    rc = virtualchain.sync_virtualchain( bt_opts, last_block, new_db, expected_snapshots=expected_snapshots, **virtualchain_args )

  File "/usr/local/lib/python2.7/dist-packages/virtualchain/virtualchain.py", line 71, in sync_virtualchain
    rc = indexer.StateEngine.build(bitcoind_opts, last_block + 1, state_engine, expected_snapshots=expected_snapshots, tx_filter=tx_filter )

  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/indexer.py", line 1145, in build
    consensus_hash = state_engine.process_block( processed_block_id, ops, expected_snapshots=expected_snapshots )

  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/indexer.py", line 1069, in process_block
    new_ops = self.process_ops( block_id, ops )

  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/indexer.py", line 1013, in process_ops
    new_op_list = self.impl.db_commit( block_id, opcode, op_sanitized, reserved['virtualchain_txid'], reserved['virtualchain_txindex'], db_state=self.state )

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/nameset/virtualchain_hooks.py", line 354, in db_commit
    op_seq = db_state.commit_operation( op_data, block_id )

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/nameset/namedb.py", line 1335, in commit_operation
    op_seq = self.commit_state_create( nameop, current_block_number )

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/nameset/namedb.py", line 1538, in commit_state_create
    history_id, prior_record, table, constraints_ignored=constraints_ignored )

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/nameset/db.py", line 1043, in namedb_state_create_as_import
    rc = namedb_history_save( cur, opcode, history_id, block_id, vtxindex, txid, prior_import )

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/nameset/db.py", line 1227, in namedb_history_save
    rc = namedb_history_append( cur, history_id, block_id, vtxindex, txid, history_diff )

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/nameset/db.py", line 1264, in namedb_history_append
    namedb_query_execute( cur, query, values )

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/nameset/db.py", line 484, in namedb_query_execute
    log.error("\n".join(traceback.format_stack()))

**Comment by jcnelson** [comment]
Hey @doodlemania2, did you by chance stop your server and re-start it while it was indexing?  What's happened here is the server tried to process a Bitcoin transaction that it had already processed.  The immediate remedy would be to run `blockstack-server stop`, followed by `blockstack-server restore`, followed by `blockstack-server start` to restart it from a known-good state.

**Comment by doodlemania2** [comment]
That's likely what happened - any thoughts on how one could protect against something like that? Obviously clean stopping the server then shutting the VM down, but thinking more like - detect that is what happened, auto restore from previous known-good state, etc. instead of just crashing?

**Comment by jcnelson** [comment]
What should happen is the `blockstack-server restore` step should execute automatically when you try to run `blockstack-server start` after a bad shutdown.  We already have the mechanism to detect this; I just need to plumb it through.

**Comment by jcnelson** [comment]
I added a fix that will cause `blockstack-server start` to attempt to restore state if it detects that it was interrupted while indexing.
