### ISSUE TITLE
ImportError: cannot import name sign

### ISSUE THREAD

**Issue by JustinDrake** [blockstack/blockstack-core#259]
I've followed [the docs](https://blockstack.org/docs) by the letter, but failed on lookup. (Running on Ubuntu.)

```
blockstack lookup timblee.id
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/__init__.py", line 24, in <module>
    import app
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/app.py", line 27, in <module>
    import wallet
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/wallet.py", line 32, in <module>
    import pybitcoin
  File "/usr/local/lib/python2.7/dist-packages/pybitcoin/__init__.py", line 13, in <module>
    import transactions
  File "/usr/local/lib/python2.7/dist-packages/pybitcoin/transactions/__init__.py", line 12, in <module>
    from .network import broadcast_transaction, send_to_address, get_unspents, \
  File "/usr/local/lib/python2.7/dist-packages/pybitcoin/transactions/network.py", line 11, in <module>
    from bitcoin import sign as sign_transaction
ImportError: cannot import name sign
```

**Comment by muneeb-ali** [comment]
Try using the new install instructions in the [README](https://github.com/blockstack/blockstack-core/blob/master/README.md). This has been fixed.
