### ISSUE TITLE
Trouble building rc-0.14.1b on macOS / missing dependencies

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#274]
I had some trouble install rc-0.14.1b into a virtualenv on macOS 10.3.2.

I ran `python setup.py install` - it couldn't find sources for some of our libraries that have been updated for rc-0.14.1. I was able to clone those repos and `python setup.py install` from their `rc-0.14.1` branches.

Running `python setup.py install` succeeded.

Running `blockstack` resulted in the following error:

```
(venv) Vanquish:blockstack-core larry$ blockstack
Traceback (most recent call last):
  File "/Users/larry/git/blockstack-core/venv/bin/blockstack", line 4, in <module>
    __import__('pkg_resources').run_script('blockstack==0.14.1', 'blockstack')
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/EGG-INFO/scripts/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/__init__.py", line 24, in <module>
    import app
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/app.py", line 39, in <module>
    import wallet
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/wallet.py", line 50, in <module>
    from .backend.crypto.utils import get_address_from_privkey
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/__init__.py", line 21, in <module>
    from registrar import *
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/registrar.py", line 48, in <module>
    from .queue import get_queue_state, in_queue, queue_removeall
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/queue.py", line 33, in <module>
    from ..proxy import get_default_proxy
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/proxy.py", line 42, in <module>
    import storage
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/storage.py", line 38, in <module>
    import fastecdsa
ImportError: No module named fastecdsa
(venv) Vanquish:blockstack-core larry$
```

It looks like fastecdsa is missing from the list of dependencies.

Tried to `pip install fastecdsa`.

It failed -> looks like it requires GMP. 

`brew install gmp`

Trying `pip install fastecdsa` it would still fail:
```
  cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.12-intel-2.7/src/curveMath.o build/temp.macosx-10.12-intel-2.7/src/curve.o build/temp.macosx-10.12-intel-2.7/src/point.o build/temp.macosx-10.12-intel-2.7/src/binaryField.o -lgmp -o build/lib.macosx-10.12-intel-2.7/fastecdsa/curvemath.so
    ld: library not found for -lgmp
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/larry/git/blockstack-core/venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/nf/ylp1ctks7c11dfpdly8pv_980000gn/T/pip-build-mfERmM/fastecdsa/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/nf/ylp1ctks7c11dfpdly8pv_980000gn/T/pip-Yl3Zxo-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/larry/git/blockstack-core/venv/include/site/python2.7/fastecdsa" failed with error code 1 in /private/var/folders/nf/ylp1ctks7c11dfpdly8pv_980000gn/T/pip-build-mfERmM/fastecdsa/
```
The solution was to tell the linker where to find the gmp library brew installed:

`export LIBRARY_PATH="/usr/local/lib"`

**Comment by larrysalibra** [comment]
@jcnelson Take away from this issue is that I think `fastecdsa` needs to be added as a dependency.

**Comment by jcnelson** [comment]
Yup, that was missing.  Fixed in the latest push.  Thanks!

**Comment by jcnelson** [comment]
@larrysalibra Can we close this issue?

**Comment by larrysalibra** [comment]
Yes. Thank you.
