### ISSUE TITLE
Rest API crashes on startup

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#276]
After entering the correct wallet password, `blockstack rpcctl start` crashes with following output: 

(i'm on commit 659b243f6e5dcca24b3eeacb9026d9d2ed9c8d4a) 
```
(venv) Vanquish:blockstack-core larry$ blockstack rpcctl start
[2017-02-02 16:19:05,918] [DEBUG] [spv:103] (59633.140736967087040) Using mainnet
[2017-02-02 16:19:06,051] [DEBUG] [client:86] (59633.140736967087040) Connect to explore.appartisan.com:6264
[2017-02-02 16:19:06,071] [DEBUG] [client:120] (59633.140736967087040) Loaded storage driver "disk"
[2017-02-02 16:19:06,071] [DEBUG] [client:120] (59633.140736967087040) Loaded storage driver "blockstack_resolver"
[2017-02-02 16:19:06,072] [DEBUG] [client:120] (59633.140736967087040) Loaded storage driver "blockstack_server"
[2017-02-02 16:19:06,072] [DEBUG] [client:120] (59633.140736967087040) Loaded storage driver "http"
[2017-02-02 16:19:06,073] [DEBUG] [client:120] (59633.140736967087040) Loaded storage driver "dht"
[2017-02-02 16:19:06,526] [DEBUG] [spv:103] (59636.140736967087040) Using mainnet
Enter wallet password: 
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/larry/git/blockstack-core/blockstack_client/rpc_runner.py", line 55, in <module>
    rc = local_rpc_start(portnum, config_dir=config_dir, password=passwd)
  File "blockstack_client/rpc.py", line 3240, in local_rpc_start
    include_private=True, wallet_path=wallet_path
  File "blockstack_client/wallet.py", line 665, in load_wallet
    res = decrypt_wallet(data, password, config_path=config_path)
  File "blockstack_client/wallet.py", line 414, in decrypt_wallet
    key_defaults = make_legacy_wallet_keys(data, password, max_tries=max_tries)
  File "blockstack_client/wallet.py", line 309, in make_legacy_wallet_keys
    'data': child_keys[2[1]]
TypeError: 'int' object has no attribute '__getitem__'
RPC controller exit code 1
(venv) Vanquish:blockstack-core larry$```

**Comment by jcnelson** [comment]
Just pushed a fix.  Thanks for reporting!

**Comment by larrysalibra** [comment]
Thanks! Works for me!
