### ISSUE TITLE
POST /v1/name fails w/ 500 error

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#295]
post body:

```JSON
{"name":"devname5.id","owner_address":"1DRuTWe4LzNmKe7zcnKdd8rBFbXS4jecTH","zonefile":"$ORIGIN devname5.id\n$TTL 3600\n_http._tcp\tIN\tURI\t10\t1\t\"https://www.dropbox.com/s/bmukjtiecd9oyx7/profile.json?dl=1\"\n\n"}
```

```
[2017-02-12 16:08:13,685] [DEBUG] [rpc:683] (37428.140735938274240) No authorization header
127.0.0.1 - - [12/Feb/2017 16:08:13] "OPTIONS /v1/names HTTP/1.1" 200 -
[2017-02-12 16:08:13,690] [DEBUG] [rpc:2978] (37428.140735938274240) 
full path: /v1/names
method: POST
path: /v1/names
qs: {}
headers:
 origin: http://localhost:3000
content-length: 216
accept-language: en-US,en;q=0.8
accept-encoding: gzip, deflate, br
connection: keep-alive
accept: application/json
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
host: localhost:6270
referer: http://localhost:3000/profiles/register
content-type: application/json

[2017-02-12 16:08:13,690] [DEBUG] [rpc:683] (37428.140735938274240) No authorization header
[2017-02-12 16:08:13,700] [DEBUG] [proxy:184] (37428.140735938274240) Default proxy to node.blockstack.org:6264
[2017-02-12 16:08:13,701] [DEBUG] [client:86] (37428.140735938274240) Connect to node.blockstack.org:6264
[2017-02-12 16:08:13,701] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "disk"
[2017-02-12 16:08:13,702] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "blockstack_resolver"
[2017-02-12 16:08:13,703] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "blockstack_server"
[2017-02-12 16:08:13,704] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "http"
[2017-02-12 16:08:13,704] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "dht"
[2017-02-12 16:08:14,089] [DEBUG] [proxy:1599] (37428.140735938274240) Failed to read blockchain record for devname5.id
[2017-02-12 16:08:14,089] [DEBUG] [rpc:3468] (37428.140735938274240) Caller is the RPC server. Short-circuiting.
[2017-02-12 16:08:14,100] [DEBUG] [proxy:184] (37428.140735938274240) Default proxy to node.blockstack.org:6264
[2017-02-12 16:08:14,100] [DEBUG] [client:86] (37428.140735938274240) Connect to node.blockstack.org:6264
[2017-02-12 16:08:14,100] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "disk"
[2017-02-12 16:08:14,101] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "blockstack_resolver"
[2017-02-12 16:08:14,101] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "blockstack_server"
[2017-02-12 16:08:14,102] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "http"
[2017-02-12 16:08:14,102] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "dht"
[2017-02-12 16:08:14,106] [DEBUG] [registrar:1070] (37426.140735938274240) begin key decrypt
[2017-02-12 16:08:14,106] [DEBUG] [rpc:3468] (37428.140735938274240) Caller is the RPC server. Short-circuiting.
[2017-02-12 16:08:14,115] [DEBUG] [proxy:184] (37428.140735938274240) Default proxy to node.blockstack.org:6264
[2017-02-12 16:08:14,115] [DEBUG] [client:86] (37428.140735938274240) Connect to node.blockstack.org:6264
[2017-02-12 16:08:14,115] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "disk"
[2017-02-12 16:08:14,115] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "blockstack_resolver"
[2017-02-12 16:08:14,116] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "blockstack_server"
[2017-02-12 16:08:14,116] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "http"
[2017-02-12 16:08:14,116] [DEBUG] [client:120] (37428.140735938274240) Loaded storage driver "dht"
[2017-02-12 16:08:14,120] [DEBUG] [registrar:1070] (37426.140735938274240) begin key decrypt
[2017-02-12 16:08:14,580] [DEBUG] [actions:366] (37428.140735938274240) Get total registration fees for registering devname5.id to 39LU7b4xifms1H4VytaDcDxJTNggh4hwrK paid by 37tbGfinfPk6h4NCpXRQHAQT9cEWWWGW89
[2017-02-12 16:08:17,160] [WARNING] [nameops:163] (37428.140735938274240) Assuming 2 signatures required from p2sh payment address
[2017-02-12 16:08:17,161] [DEBUG] [blockchain:57] (37428.140735938274240) Connect to bitcoind at bitcoin.blockstack.com:8332 (/Users/larry/git/blockstack-core/config/client.ini)
[2017-02-12 16:08:17,161] [DEBUG] [session:129] (37426.140735938274240) [37428] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2017-02-12 16:08:17,462] [DEBUG] [nameops:274] (37428.140735938274240) preorder tx 590 bytes, 70842 satoshis
[2017-02-12 16:08:17,468] [DEBUG] [nameops:112] (37428.140735938274240) dust_fee is 26500
[2017-02-12 16:08:17,468] [DEBUG] [nameops:279] (37428.140735938274240) Additional dust fee: 26500
[2017-02-12 16:08:22,585] [WARNING] [nameops:163] (37428.140735938274240) Assuming 2 signatures required from p2sh payment address
[2017-02-12 16:08:22,586] [DEBUG] [blockchain:57] (37428.140735938274240) Connect to bitcoind at bitcoin.blockstack.com:8332 (/Users/larry/git/blockstack-core/config/client.ini)
[2017-02-12 16:08:22,586] [DEBUG] [session:129] (37426.140735938274240) [37428] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2017-02-12 16:08:22,827] [DEBUG] [nameops:319] (37428.140735938274240) register tx 563 bytes, 67600 satoshis txfee
[2017-02-12 16:08:22,832] [DEBUG] [nameops:112] (37428.140735938274240) dust_fee is 26500
[2017-02-12 16:08:22,832] [DEBUG] [nameops:324] (37428.140735938274240) Additional dust fee: 26500
[2017-02-12 16:08:25,146] [WARNING] [nameops:194] (37428.140735938274240) Guessing that owner address 39LU7b4xifms1H4VytaDcDxJTNggh4hwrK requires 2 signatures
[2017-02-12 16:08:26,691] [DEBUG] [scripts:471] (37428.140735938274240) 37tbGfinfPk6h4NCpXRQHAQT9cEWWWGW89 will subsidize 15500 (ops+dust) satoshi
[2017-02-12 16:08:27,179] [ERROR] [nameops:415] (37428.140735938274240) Missing private keys
Traceback (most recent call last):
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/nameops.py", line 403, in estimate_update_tx_fee
    signed_subsidized_tx = subsidize_or_pad_transaction(unsigned_tx, owner_address, owner_privkey_params, payment_privkey_info, fees_update, utxo_client, payment_address=payment_address, config_path=config_path )
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/nameops.py", line 219, in subsidize_or_pad_transaction
    subsidized_tx = tx_make_subsidizable( unsigned_tx, fees_func, 21 * 10**14, payment_privkey_info, utxo_client )
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/scripts.py", line 524, in tx_make_subsidizable
    subsidized_tx, idx, subsidy_key_info, hashcode=bitcoin.SIGHASH_ANYONECANPAY
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/scripts.py", line 366, in tx_sign_input
    return tx_sign_multisig(blockstack_tx, idx, redeem_script, private_keys, hashcode=bitcoin.SIGHASH_ALL)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/scripts.py", line 321, in tx_sign_multisig
    assert len(used_keys) == m, 'Missing private keys'
AssertionError: Missing private keys
[2017-02-12 16:08:27,180] [ERROR] [nameops:417] (37428.140735938274240) Unable to create transaction
[2017-02-12 16:08:27,181] [DEBUG] [blockchain:57] (37428.140735938274240) Connect to bitcoind at bitcoin.blockstack.com:8332 (/Users/larry/git/blockstack-core/config/client.ini)
[2017-02-12 16:08:27,181] [DEBUG] [session:129] (37426.140735938274240) [37428] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2017-02-12 16:08:30,065] [WARNING] [nameops:194] (37428.140735938274240) Guessing that owner address 39LU7b4xifms1H4VytaDcDxJTNggh4hwrK requires 2 signatures
[2017-02-12 16:08:31,465] [DEBUG] [scripts:471] (37428.140735938274240) 37tbGfinfPk6h4NCpXRQHAQT9cEWWWGW89 will subsidize 26500 (ops+dust) satoshi
[2017-02-12 16:08:31,966] [ERROR] [rpc:3039] (37428.140735938274240) local variable 've' referenced before assignment
Traceback (most recent call last):
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/rpc.py", line 3036, in _dispatch
    return route_method( session, path_info, *route_args )
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/rpc.py", line 1001, in POST_names
    res = internal.cli_register(name, zonefile_txt, recipient_address, min_confs, interactive=False, force_data=True)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/rpc.py", line 255, in argwrapper
    result = run_cli_rpc(method_info['command'], list(args), config_path=cf, check_rpc=check_rpc, **kw)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/rpc.py", line 236, in run_cli_rpc
    res = command_info['method'](args, config_path=config_path, **kw)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/actions.py", line 1340, in cli_register
    proxy=proxy, config_path=config_path, transfer_address=transfer_address, owner_address=owner_address
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/actions.py", line 411, in get_total_registration_fees
    config_path=config_path, payment_address=payment_address, include_dust=True
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/nameops.py", line 481, in estimate_transfer_tx_fee
    log.exception(ve)
UnboundLocalError: local variable 've' referenced before assignment
127.0.0.1 - - [12/Feb/2017 16:08:31] "POST /v1/names HTTP/1.1" 500 -
```

**Comment by larrysalibra** [comment]
fixes merged. closing issue
