### ISSUE TITLE
Withdraw endpoint doesn't work

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#298]
POST to `http://localhost:6270/v1/wallet/balance`

post body:

```JSON
{"address":"1M898gHnBM9EendVtcWwFWk7MVHq9HBLoZ"}
```

Response status is `500` and no output is returned.

This is the output from `api_endpoint.log`:

```
[2017-02-12 17:43:57,881] [DEBUG] [rpc:2978] (37519.140735938274240) 
full path: /v1/wallet/payment_address
method: GET
path: /v1/wallet/payment_address
qs: {}
headers:
 accept-language: en-us
accept-encoding: gzip, deflate
host: localhost:6270
accept: */*
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8
dnt: 1
connection: keep-alive
cookie: io=O3Bqc3h7dLm548xWAADk; mp_f6808747c935f2b51cf0563b5d8cbd04_mixpanel=%7B%22distinct_id%22%3A%20%22159ba4efb70b91-0614dfdeb9099b-4a1b3104-13c680-159ba4efb7198b%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; mp_mixpanel__c=0; _t=d49f4444cb77e4c90f008636f92194e4
cache-control: max-age=0
referer: http://localhost:3000/account/withdraw?recipientAddress=1M898gHnBM9EendVtcWwFWk7MVHq9HBLoZ&password=password

[2017-02-12 17:43:57,881] [DEBUG] [rpc:683] (37519.140735938274240) No authorization header
127.0.0.1 - - [12/Feb/2017 17:43:57] "GET /v1/wallet/payment_address HTTP/1.1" 200 -
[2017-02-12 17:44:00,729] [DEBUG] [rpc:2978] (37519.140735938274240) 
full path: /v1/wallet/payment_address
method: GET
path: /v1/wallet/payment_address
qs: {}
headers:
 origin: http://localhost:3000
accept-language: en-US,en;q=0.8
accept-encoding: gzip, deflate, sdch, br
connection: keep-alive
accept: */*
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
host: localhost:6270
referer: http://localhost:3000/account/withdraw
cache-control: max-age=0

[2017-02-12 17:44:00,730] [DEBUG] [rpc:683] (37519.140735938274240) No authorization header
127.0.0.1 - - [12/Feb/2017 17:44:00] "GET /v1/wallet/payment_address HTTP/1.1" 200 -
[2017-02-12 17:44:01,759] [DEBUG] [rpc:2978] (37519.140735938274240) 
full path: /v1/wallet/payment_address
method: GET
path: /v1/wallet/payment_address
qs: {}
headers:
 origin: http://localhost:3000
accept-language: en-US,en;q=0.8
accept-encoding: gzip, deflate, sdch, br
connection: keep-alive
accept: */*
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
host: localhost:6270
referer: http://localhost:3000/account/withdraw?recipientAddress=1M898gHnBM9EendVtcWwFWk7MVHq9HBLoZ&password=password
cache-control: max-age=0

[2017-02-12 17:44:01,759] [DEBUG] [rpc:683] (37519.140735938274240) No authorization header
127.0.0.1 - - [12/Feb/2017 17:44:01] "GET /v1/wallet/payment_address HTTP/1.1" 200 -
[2017-02-12 17:44:12,449] [DEBUG] [rpc:2978] (37519.140735938274240) 
full path: /v1/wallet/balance
method: POST
path: /v1/wallet/balance
qs: {}
headers:
 origin: http://localhost:3000
content-length: 48
accept-language: en-US,en;q=0.8
accept-encoding: gzip, deflate, br
connection: keep-alive
accept: application/json
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
host: localhost:6270
referer: http://localhost:3000/account/withdraw
content-type: application/json

[2017-02-12 17:44:12,457] [DEBUG] [rpc:683] (37519.140735938274240) No authorization header
[2017-02-12 17:44:13,944] [ERROR] [rpc:3039] (37519.140735938274240) Missing private keys
Traceback (most recent call last):
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/rpc.py", line 3036, in _dispatch
    return route_method( session, path_info, *route_args )
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/rpc.py", line 2088, in POST_wallet_balance
    res = internal.cli_withdraw(address, amount, min_confs, tx_only, config_path=self.server.config_path, interactive=False, wallet_keys=self.server.wallet_keys)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/rpc.py", line 255, in argwrapper
    result = run_cli_rpc(method_info['command'], list(args), config_path=cf, check_rpc=check_rpc, **kw)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/rpc.py", line 236, in run_cli_rpc
    res = command_info['method'](args, config_path=config_path, **kw)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/actions.py", line 701, in cli_withdraw
    signed_tx = sign_tx(serialized_tx, wallet_keys['payment_privkey'])
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/tx.py", line 133, in sign_tx
    return tx_sign_all_unsigned_inputs(private_key_info, tx_hex)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/scripts.py", line 392, in tx_sign_all_unsigned_inputs
    tx_hex = tx_sign_input(str(unsigned_tx_hex), i, private_key_info)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/scripts.py", line 366, in tx_sign_input
    return tx_sign_multisig(blockstack_tx, idx, redeem_script, private_keys, hashcode=bitcoin.SIGHASH_ALL)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/scripts.py", line 321, in tx_sign_multisig
    assert len(used_keys) == m, 'Missing private keys'
AssertionError: Missing private keys
127.0.0.1 - - [12/Feb/2017 17:44:13] "POST /v1/wallet/balance HTTP/1.1" 500 -```

**Comment by larrysalibra** [comment]
```
(venv) Vanquish:git larry$ tail -f blockstack-core/config/api_endpoint.log 

[2017-02-12 22:06:04,060] [DEBUG] [rpc:2985] (41866.140735938274240) 
full path: /v1/wallet/balance
method: POST
path: /v1/wallet/balance
qs: {}
headers:
 origin: http://localhost:3000
content-length: 48
accept-language: en-US,en;q=0.8
accept-encoding: gzip, deflate, br
connection: keep-alive
accept: application/json
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
host: localhost:6270
referer: http://localhost:3000/account/withdraw
content-type: application/json

[2017-02-12 22:06:04,060] [DEBUG] [rpc:684] (41866.140735938274240) No authorization header
[2017-02-12 22:06:05,541] [DEBUG] [rpc:2097] (41866.140735938274240) Failed to transfer balance: Cannot withdraw dust
127.0.0.1 - - [12/Feb/2017 22:06:05] "POST /v1/wallet/balance HTTP/1.1" 500 -
```

**Comment by larrysalibra** [comment]
@jcnelson just gave it another try. I'm trying to withdraw the entire balance, so i'm not providing an amount. Post body is the same as above.

```
(venv) Vanquish:git larry$ tail -f blockstack-core/config/api_endpoint.log 

[2017-02-12 22:43:22,579] [DEBUG] [rpc:2985] (42873.140735938274240) 
full path: /v1/wallet/balance
method: POST
path: /v1/wallet/balance
qs: {}
headers:
 origin: http://localhost:3000
content-length: 48
accept-language: en-US,en;q=0.8
accept-encoding: gzip, deflate, br
connection: keep-alive
accept: application/json
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
host: localhost:6270
referer: http://localhost:3000/account/withdraw
content-type: application/json

[2017-02-12 22:43:22,580] [DEBUG] [rpc:684] (42873.140735938274240) No authorization header
[2017-02-12 22:43:22,582] [DEBUG] [actions:667] (42873.140735938274240) amount = None
[2017-02-12 22:43:22,582] [DEBUG] [rpc:2097] (42873.140735938274240) Failed to transfer balance: Invalid amount
127.0.0.1 - - [12/Feb/2017 22:43:22] "POST /v1/wallet/balance HTTP/1.1" 500 -
```

**Comment by jcnelson** [comment]
My latest patches add more debugging information, if you want to try again.  The gist of it is that somehow, not all private keys are getting used to sign off on the withdrawal transaction.

**Comment by jcnelson** [comment]
Okay, I think I see what's going on.  Working on a fix...

**Comment by jcnelson** [comment]
Pushed a possible fix.

**Comment by jcnelson** [comment]
Minus the inability to do `min_conf=0` with `blockcypher` as your UTXO driver, can we say that this works now?

**Comment by shea256** [comment]
OK sounds like we can close this and continue working off of #301

**Comment by larrysalibra** [comment]
Yes, it works. Thanks for your help @jcnelson !
