### ISSUE TITLE
Price API endpoint fails if wallet has no UTXOs

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#315]
```
[2017-02-15 22:08:28,476] [DEBUG] [rpc:2956] (54402.140737199449024) 
full path: /v1/prices/names/guylepage3.id
method: GET
path: /v1/prices/names/guylepage3.id
qs: {}
headers:
 accept-language: en-us
accept-encoding: gzip, deflate
connection: keep-alive
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8
dnt: 1
host: localhost:6270
cookie: mp_f6808747c935f2b51cf0563b5d8cbd04_mixpanel=%7B%22distinct_id%22%3A%20%22159ba4efb70b91-0614dfdeb9099b-4a1b3104-13c680-159ba4efb7198b%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; _t=d49f4444cb77e4c90f008636f92194e4
upgrade-insecure-requests: 1

[2017-02-15 22:08:28,476] [DEBUG] [rpc:651] (54402.140737199449024) No authorization header
[2017-02-15 22:08:28,481] [DEBUG] [proxy:184] (54402.140737199449024) Default proxy to node.blockstack.org:6264
[2017-02-15 22:08:28,482] [DEBUG] [client:86] (54402.140737199449024) Connect to node.blockstack.org:6264
[2017-02-15 22:08:28,482] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "disk"
[2017-02-15 22:08:28,482] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "blockstack_resolver"
[2017-02-15 22:08:28,483] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "blockstack_server"
[2017-02-15 22:08:28,484] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "http"
[2017-02-15 22:08:28,484] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "dht"
[2017-02-15 22:08:28,485] [DEBUG] [rpc:3806] (54402.140737199449024) RPC running (/Users/larry/Library/Application Support/Blockstack/config/api_endpoint.pid)
[2017-02-15 22:08:28,485] [DEBUG] [rpc:3446] (54402.140737199449024) Caller is the RPC server. Short-circuiting.
[2017-02-15 22:08:28,514] [DEBUG] [proxy:184] (54402.140737199449024) Default proxy to node.blockstack.org:6264
[2017-02-15 22:08:28,515] [DEBUG] [client:86] (54402.140737199449024) Connect to node.blockstack.org:6264
[2017-02-15 22:08:28,515] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "disk"
[2017-02-15 22:08:28,515] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "blockstack_resolver"
[2017-02-15 22:08:28,516] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "blockstack_server"
[2017-02-15 22:08:28,517] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "http"
[2017-02-15 22:08:28,517] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "dht"
[2017-02-15 22:08:28,521] [DEBUG] [registrar:1070] (54400.140737199449024) begin key decrypt
[2017-02-15 22:08:28,521] [DEBUG] [rpc:3446] (54402.140737199449024) Caller is the RPC server. Short-circuiting.
[2017-02-15 22:08:28,530] [DEBUG] [proxy:184] (54402.140737199449024) Default proxy to node.blockstack.org:6264
[2017-02-15 22:08:28,530] [DEBUG] [client:86] (54402.140737199449024) Connect to node.blockstack.org:6264
[2017-02-15 22:08:28,530] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "disk"
[2017-02-15 22:08:28,531] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "blockstack_resolver"
[2017-02-15 22:08:28,531] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "blockstack_server"
[2017-02-15 22:08:28,532] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "http"
[2017-02-15 22:08:28,532] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "dht"
[2017-02-15 22:08:28,536] [DEBUG] [registrar:1070] (54400.140737199449024) begin key decrypt
[2017-02-15 22:08:28,540] [DEBUG] [proxy:184] (54402.140737199449024) Default proxy to node.blockstack.org:6264
[2017-02-15 22:08:28,540] [DEBUG] [client:86] (54402.140737199449024) Connect to node.blockstack.org:6264
[2017-02-15 22:08:28,540] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "disk"
[2017-02-15 22:08:28,541] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "blockstack_resolver"
[2017-02-15 22:08:28,541] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "blockstack_server"
[2017-02-15 22:08:28,542] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "http"
[2017-02-15 22:08:28,542] [DEBUG] [client:120] (54402.140737199449024) Loaded storage driver "dht"
[2017-02-15 22:08:29,347] [DEBUG] [actions:367] (54402.140737199449024) Get total registration fees for registering guylepage3.id to 33GcdiK7JxuNX8NCQTvVh58dZEKW2ym7Hp paid by 3Ht2PzmsT4gy4EpBTp7FKco239ZiHvXdUP
[2017-02-15 22:08:30,318] [ERROR] [rpc:3017] (54402.140737199449024) No UTXOs for 3Ht2PzmsT4gy4EpBTp7FKco239ZiHvXdUP
Traceback (most recent call last):
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 3014, in _dispatch
    return route_method( session, path_info, *route_args )
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 1838, in GET_prices_name
    res = internal.cli_price(name)
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 257, in argwrapper
    result = run_cli_rpc(method_info['command'], list(args), config_path=cf, check_rpc=check_rpc, **kw)
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 238, in run_cli_rpc
    res = command_info['method'](args, config_path=config_path, **kw)
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py", line 785, in cli_price
    transfer_address=transfer_address
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py", line 374, in get_total_registration_fees
    config_path=config_path, include_dust=True
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/nameops.py", line 257, in estimate_preorder_tx_fee
    unsigned_tx = preorder_tx( name, payment_addr, owner_address, name_cost, fake_consensus_hash, utxo_client, min_payment_confs=min_payment_confs )
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/tx.py", line 44, in preorder_tx
    inputs, outputs = tx_preorder(*args, **kw)
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/operations/preorder.py", line 143, in make_transaction
    assert len(inputs) > 0, "No UTXOs for {}".format(preorder_addr)
AssertionError: No UTXOs for 3Ht2PzmsT4gy4EpBTp7FKco239ZiHvXdUP
127.0.0.1 - - [15/Feb/2017 22:08:30] "GET /v1/prices/names/guylepage3.id HTTP/1.1" 500 -```

**Comment by jcnelson** [comment]
Thanks for reporting; will fix this.

**Comment by jcnelson** [comment]
This should be fixed in `rc-0.14.1b`.  You should get an appropriate error message

**Comment by jcnelson** [comment]
@larrysalibra can you confirm that this is fixed?

**Comment by larrysalibra** [comment]
I'll test it out shortly.

**Comment by jcnelson** [comment]
Tested again and fixed a few things.  Should be working now.  Please re-open if not.
