### ISSUE TITLE
Trouble installing 0.14.1 on Debian Jessie

### ISSUE THREAD

**Issue by datawisely** [blockstack/blockstack-core#331]
I have trouble installing Blockstack CLI on Debian Jessie.

I ran _apt-get update && apt-get install -y python-pip python-dev libssl-dev libffi-dev rng-tools_ which worked. Then I ran _pip install blockstack_ which threw an error:

_In file included from src/curveMath.c:1:0:_

_src/curveMath.h:6:17: fatal error: gmp.h: No such file or directory_

 _#include <gmp.h>_

I tried to install _pip install fastecdsa_ but:

_src/curveMath.h:6:17: fatal error: gmp.h: No such file or directory_

 _#include <gmp.h>_

                 _^_

_compilation terminated._

_error: command 'x86_64-linux-gnu-gcc' failed with exit status 1_

I found a similar issue here: https://github.com/blockstack/blockstack-core/issues/274 but that is for MacOSX

Thanks!

**Comment by muneeb-ali** [comment]
@datawisely thanks for reporting -- I'm taking a look

**Comment by muneeb-ali** [comment]
@datawisely try now -- should be fixed.

**Comment by datawisely** [comment]
I ran _pip install blockstack_ again, but got this again:

_In file included from src/curveMath.c:1:0:_

_src/curveMath.h:6:17: fatal error: gmp.h: No such file or directory_

 _#include <gmp.h>_

                 _^_

_compilation terminated._

_error: command 'x86_64-linux-gnu-gcc' failed with exit status 1_

**Comment by jcnelson** [comment]
Hey @datawisely!  Can you also try `apt-get install libgmp-dev`?  Thanks!

**Comment by datawisely** [comment]
Ok, first I did "apt-get install libgmp-dev" and then "pip install blockstack". Now I get a different error:

ImportError: No module named setuptools_ext

----------------------------------------
  Can't roll back cryptography; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-V7O8ua/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-r_5lND-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-V7O8ua/cryptography
Storing debug log for failure in /root/.pip/pip.log

**Comment by petepacific** [comment]
@datawisely try the following:

sudo pip install -U cffi

then run the blockstack install again.

source: https://github.com/pyca/cryptography/issues/2280

**Comment by datawisely** [comment]
Ok. Did that. It installed without error. But when I try:

blockstack lookup timblee.id

I get:

Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/__init__.py", line 24, in <module>
    import app
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/app.py", line 40, in <module>
    import wallet
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/wallet.py", line 30, in <module>
    import virtualchain
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/__init__.py", line 24, in <module>
    from .lib import *
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/__init__.py", line 26, in <module>
    import blockchain
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/__init__.py", line 24, in <module>
    import transactions
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/transactions.py", line 27, in <module>
    from .bitcoin_blockchain import JSONRPCException, BlockchainDownloader, SPVClient
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/__init__.py", line 24, in <module>
    from .keys import BitcoinPublicKey, BitcoinPrivateKey, hex_hash160_to_address, script_hex_to_address, version_byte, analyze_private_key, \
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/keys.py", line 24, in <module>
    import pybitcoin
  File "/usr/local/lib/python2.7/dist-packages/pybitcoin/__init__.py", line 46, in <module>
    from keychain import PrivateKeychain, PublicKeychain
  File "/usr/local/lib/python2.7/dist-packages/keychain/__init__.py", line 1, in <module>
    from .private_keychain import PrivateKeychain
  File "/usr/local/lib/python2.7/dist-packages/keychain/private_keychain.py", line 1, in <module>
    from bitmerchant.wallet import Wallet as HDWallet
  File "/usr/local/lib/python2.7/dist-packages/bitmerchant/wallet/__init__.py", line 1, in <module>
    from .bip32 import Wallet
  File "/usr/local/lib/python2.7/dist-packages/bitmerchant/wallet/bip32.py", line 7, in <module>
    import base58
ImportError: No module named base58

**Comment by muneeb-ali** [comment]
can you please paste the output of

> $ blockstack info 

I want to ensure you're on the latest version of blockstack

**Comment by jcnelson** [comment]
@muneeb-ali @datawisely I think the version of `pip` you're using is old.  That would explain this:

```
ImportError: No module named setuptools_ext
```

This can be fixed with `pip install --upgrade pip`.

The import error on `base58` indicates that not all of the dependencies were installed through `pip`.  If you follow up with `pip install --upgrade blockstack` once your `pip` is at the latest version, that should force the dependent packages to get installed.

Since you're doing this on Jessie, you might also have an out-of-date `pyopenssl`.  This can be fixed with `pip install --upgrade pyopenssl`.

**Comment by jackzampolin** [comment]
Closing this as stale. Please reopen if it is still an issue.
