### ISSUE TITLE
Not able to create account on Blockstack Portal

### ISSUE THREAD

**Issue by 9z25** [blockstack/blockstack-core#400]
I followed directions starting blockstack core:
http://localhost:6270/v1/names/blockstack.id returns a response.

I started the CORS proxy to run at port 1337. All good.

when I start Portal and open localhost:3000. I am greeted with a window to create my account, yet the Create Account button does not work.

How do I resolve this issue to create an account and start using Portal? Thanks!

**Comment by shea256** [comment]
Ah ok. Looks like the portal is working and core is running but the portal is having trouble connecting to it. Can you please paste what you see in your console?

Tagging @larrysalibra and @jcnelson on this as well.

**Comment by 9z25** [comment]
[15:53:28] Requiring external module babel-register
[15:53:30] Using gulpfile ~/blockstack-portal/gulpfile.babel.js
[15:53:30] Starting 'clean'...
[15:53:30] Finished 'clean' after 30 ms
[15:53:30] Starting 'dev'...
[15:53:30] Starting 'imagemin'...
[15:53:30] Starting 'browserify'...
[15:53:30] Rebundle...
[15:53:30] Starting 'copyFonts'...
[15:53:30] Starting 'copyFontAwesomeFonts'...
[15:53:30] Starting 'copyStyles'...
[15:53:30] Starting 'copyIndex'...
[15:53:30] Finished 'copyIndex' after 575 μs
[15:53:30] Starting 'copyIcons'...
[15:53:30] Finished 'copyIcons' after 59 ms
(node:30939) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[15:53:31] Finished 'copyFontAwesomeFonts' after 583 ms
[15:53:31] Finished 'copyStyles' after 892 ms
[15:53:40] Finished 'copyFonts' after 9.91 s
[15:53:40] Finished 'imagemin' after 10 s
[15:53:42] Finished 'browserify' after 12 s
[15:53:42] Starting 'browserSync'...
[15:53:42] Finished 'browserSync' after 36 ms
[15:53:42] Starting 'watch'...
[15:53:42] Finished 'watch' after 154 ms
[15:53:42] Finished 'dev' after 12 s
[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.9:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.9:3001
 ------------------------------------
[BS] Serving files from: ./build/
[BS] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)

**Comment by 9z25** [comment]
I'm sorry, I misunderstood you. Here's what I get from the console:
```

main.js:55533 Warning: index: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
printWarning @ main.js:55533
main.js:7430 Uncaught TypeError: _blockstack.PrivateKeychain is not a constructor
    at http://localhost:3000/js/main.js:7430:25
    at http://localhost:3000/js/main.js:109697:18
    at Object.initializeWallet (http://localhost:3000/js/main.js:109776:12)
    at WelcomeModal.createAccount (http://localhost:3000/js/main.js:2432:20)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:3000/js/main.js:87710:16)
    at executeDispatch (http://localhost:3000/js/main.js:81701:21)
    at Object.executeDispatchesInOrder (http://localhost:3000/js/main.js:81721:7)
    at executeDispatchesAndRelease (http://localhost:3000/js/main.js:81126:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3000/js/main.js:81137:10)
    at Array.forEach (native)
```

**Comment by 9z25** [comment]
I had to install v0.7.0 of blockstack portal. Problem Solved, thanks.

**Comment by jackzampolin** [comment]
Closing this as solved 🎉
