### ISSUE TITLE
Missing reference to pyparsing module in Ubuntu installation instructions [AWS/EC2 install]

### ISSUE THREAD

**Issue by lacabra** [blockstack/blockstack-core#401]
When following installations instructions found in README's Quick Start section for Ubuntu, there is no reference to the pyparsing module requirement. The missing module subsequently breaks pip, and has to be re-installed from source as per the instructions found [here](https://stackoverflow.com/questions/42181056/when-i-do-pip-version-it-show-the-error-as-importerror-no-module-named-pypars/42721488)

This is for an AWS EC2 t2.micro instance running Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-91-generic x86_64). The error is the following:

> Running setup.py install for cffi
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
        import packaging.requirements
      File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 9, in <module>
        from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
    ImportError: No module named pyparsing
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WhMtT8-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 9, in <module>
    from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
ImportError: No module named pyparsing

**Comment by jcnelson** [comment]
Hi @lacabra, thanks for reporting.  To be clear, there's an implicit dependency on pyparsing in Blockstack that isn't getting installed with pip?  Would `pip install pyparsing; pip install blockstack` have worked (or maybe adding `pyparsing` as a dependency in Blockstack)?

**Comment by lacabra** [comment]
I understand that there is an implicit dependency, but my impression is that it wasn't getting installed with pip automatically (hence reporting this issue, and so that others experiencing it can access a resource to get unstuck). Either solution that you propose might work, I haven't dug any deeper. Thanks!

**Comment by jackzampolin** [comment]
Closing this as complete.
