### ISSUE TITLE
API endpoint doesn't start: No module named blockstack_client

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#409]
Starting with commit 76e755f9822286af16356ae423b893a7c1b6f590 from #408 all the way to the most recent commit in `rc-0.14.2` 5bab713635a40ef166829b4c61e0fb20c47be6e3,  I get the following error on macOS:

```
Vanquish:macos larry$ /tmp/blockstack-venv/bin/blockstack -y --password <secret>  --config ~/Library/Application\ Support/Blockstack/config/client.ini --debug api start --api_password <secret>
Set BLOCKSTACK_CLIENT_INTERACTIVE_YES to 1
Set BLOCKSTACK_CLIENT_CONFIG to /Users/larry/Library/Application Support/Blockstack/config/client.ini
Set BLOCKSTACK_DEBUG to 1
Re-exec as `"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python", "/tmp/blockstack-venv/bin/blockstack", "api", "start", "--secrets", "3"`
[2017-05-03 13:37:39,986] [DEBUG] [spv:103] (37255.140735749067712) Using mainnet
[2017-05-03 13:37:40,221] [DEBUG] [cli:419] (37255.140735749067712) Load secrets from 3
[2017-05-03 13:37:40,271] [DEBUG] [client:87] (37255.140735749067712) Connect to node.blockstack.org:6264
[2017-05-03 13:37:40,281] [DEBUG] [client:121] (37255.140735749067712) Loaded storage driver "disk"
[2017-05-03 13:37:40,284] [DEBUG] [client:121] (37255.140735749067712) Loaded storage driver "blockstack_resolver"
[2017-05-03 13:37:40,287] [DEBUG] [client:121] (37255.140735749067712) Loaded storage driver "blockstack_server"
[2017-05-03 13:37:40,290] [DEBUG] [client:121] (37255.140735749067712) Loaded storage driver "http"
[2017-05-03 13:37:40,292] [DEBUG] [client:121] (37255.140735749067712) Loaded storage driver "dht"
[2017-05-03 13:37:40,332] [ERROR] [rpc:4253] (37255.140735749067712) Failed to start API endpoint: exit code 1
[2017-05-03 13:37:40,336] [ERROR] [rpc:4254] (37255.140735749067712) Error log:
  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named blockstack_client
  
{
    "error": "Failed to start API endpoint (exit code 1)"
}
Vanquish:macos larry$
```

The API endpoint starts properly in commit 9f32190ceb634f9b471e193e7e295bd65359ff9b

**Comment by kantai** [comment]
Can you try invoking blockstack by calling the Python executable in the venv/bin directory? So instead of `venv/bin/blockstack api start` something like `venv/bin/python venv/bin/blockstack api start` ? Because the Python executable in that log file wasn't the one in the venv

**Comment by larrysalibra** [comment]
I'll give it a try.

**Comment by larrysalibra** [comment]
@kantai Calling the python executable worked!

```
Vanquish:macos larry$ /tmp/blockstack-venv/bin/blockstack -y --password <secret> --config ~/Library/Application\ Support/Blockstack/config/client.ini --debug api start --api_password <secret>
Set BLOCKSTACK_CLIENT_INTERACTIVE_YES to 1
Set BLOCKSTACK_CLIENT_CONFIG to /Users/larry/Library/Application Support/Blockstack/config/client.ini
Set BLOCKSTACK_DEBUG to 1
Re-exec as "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python", "/tmp/blockstack-venv/bin/blockstack", "api", "start", "--secrets", "3"`
[2017-05-03 23:20:33,842] [DEBUG] [spv:103] (40201.140735749067712) Using mainnet
[2017-05-03 23:20:34,083] [DEBUG] [cli:419] (40201.140735749067712) Load secrets from 3
[2017-05-03 23:20:34,138] [DEBUG] [client:87] (40201.140735749067712) Connect to node.blockstack.org:6264
[2017-05-03 23:20:34,148] [DEBUG] [client:121] (40201.140735749067712) Loaded storage driver "disk"
[2017-05-03 23:20:34,152] [DEBUG] [client:121] (40201.140735749067712) Loaded storage driver "blockstack_resolver"
[2017-05-03 23:20:34,155] [DEBUG] [client:121] (40201.140735749067712) Loaded storage driver "blockstack_server"
[2017-05-03 23:20:34,158] [DEBUG] [client:121] (40201.140735749067712) Loaded storage driver "http"
[2017-05-03 23:20:34,161] [DEBUG] [client:121] (40201.140735749067712) Loaded storage driver "dht"
[2017-05-03 23:20:34,197] [ERROR] [rpc:4253] (40201.140735749067712) Failed to start API endpoint: exit code 1
[2017-05-03 23:20:34,201] [ERROR] [rpc:4254] (40201.140735749067712) Error log:
  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named blockstack_client
  
{
    "error": "Failed to start API endpoint (exit code 1)"
}
```

``` 
Vanquish:macos larry$ /tmp/blockstack-venv/bin/python2.7 /tmp/blockstack-venv/bin/blockstack -y --password <secret>  --config ~/Library/Application\ Support/Blockstack/config/client.ini --debug api start --api_password <secret>
Set BLOCKSTACK_CLIENT_INTERACTIVE_YES to 1
Set BLOCKSTACK_CLIENT_CONFIG to /Users/larry/Library/Application Support/Blockstack/config/client.ini
Set BLOCKSTACK_DEBUG to 1
Re-exec as `"/tmp/blockstack-venv/bin/python2.7", "/tmp/blockstack-venv/bin/blockstack", "api", "start", "--secrets", "3"`
[2017-05-03 23:21:08,333] [DEBUG] [spv:103] (40213.140735749067712) Using mainnet
[2017-05-03 23:21:08,578] [DEBUG] [cli:419] (40213.140735749067712) Load secrets from 3
[2017-05-03 23:21:08,632] [DEBUG] [client:87] (40213.140735749067712) Connect to node.blockstack.org:6264
[2017-05-03 23:21:08,641] [DEBUG] [client:121] (40213.140735749067712) Loaded storage driver "disk"
[2017-05-03 23:21:08,644] [DEBUG] [client:121] (40213.140735749067712) Loaded storage driver "blockstack_resolver"
[2017-05-03 23:21:08,648] [DEBUG] [client:121] (40213.140735749067712) Loaded storage driver "blockstack_server"
[2017-05-03 23:21:08,651] [DEBUG] [client:121] (40213.140735749067712) Loaded storage driver "http"
[2017-05-03 23:21:08,654] [DEBUG] [client:121] (40213.140735749067712) Loaded storage driver "dht"
{
    "status": true
}
Vanquish:macos larry$

**Comment by jackzampolin** [comment]
I'm running into this same error trying to vendor `blockstack` using python:

```
Traceback (most recent call last):
  File "/Users/johnzampolin/go_work/src/github.com/jackzampolin/blockstack-cli/venv/bin/blockstack-cli", line 11, in <module>
    load_entry_point('blockstack-cli', 'console_scripts', 'blockstack-cli')()
  File "/Users/johnzampolin/go_work/src/github.com/jackzampolin/blockstack-cli/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/johnzampolin/go_work/src/github.com/jackzampolin/blockstack-cli/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/Users/johnzampolin/go_work/src/github.com/jackzampolin/blockstack-cli/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/Users/johnzampolin/go_work/src/github.com/jackzampolin/blockstack-cli/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/johnzampolin/go_work/src/github.com/jackzampolin/blockstack-cli/cli.py", line 2, in <module>
    import blockstack
  File "/Users/johnzampolin/go_work/src/github.com/jackzampolin/blockstack-cli/venv/lib/python2.7/site-packages/blockstack/__init__.py", line 24, in <module>
    from .lib import *
  File "/Users/johnzampolin/go_work/src/github.com/jackzampolin/blockstack-cli/venv/lib/python2.7/site-packages/blockstack/lib/__init__.py", line 24, in <module>
    from .atlas import *
  File "/Users/johnzampolin/go_work/src/github.com/jackzampolin/blockstack-cli/venv/lib/python2.7/site-packages/blockstack/lib/atlas.py", line 39, in <module>
    from blockstack_client.config import semver_newer
ImportError: No module named blockstack_client.config
```

**Comment by kantai** [comment]
Hey @jackzampolin, How are you calling blockstack? How did you install it?

**Comment by jackzampolin** [comment]
I’m starting a python project and I’m trying to `import blockstack`. I’ve got a `virtualenv` and I’m using `setuptools`. I’ve added `blockstack` in my `install_requires` but when I try to `import blockstack` and run the program it errors out as above.

**Comment by jcnelson** [comment]
Don't use `install_requires`.  Just do `pip install blockstack`.

**Comment by jackzampolin** [comment]
So I can't use python's vendoring system to import `blockstack`?

**Comment by kantai** [comment]
What happens when you pip install the project with the `install_requires`? What output do you see?

**Comment by jackzampolin** [comment]
```pip install --editable .
Obtaining file:///Users/johnzampolin/go_work/src/github.com/jackzampolin/blockstack-cli
Requirement already satisfied: Click in ./venv/lib/python2.7/site-packages (from blockstack-cli==0.1)
Requirement already satisfied: blockstack in ./venv/lib/python2.7/site-packages (from blockstack-cli==0.1)
Requirement already satisfied: defusedxml>=0.4.1 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: simplejson>=3.8.2 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: keylib>=0.1.1 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: jsonschema>=2.5.1 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: mixpanel>=4.3.1 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: jsontokens>=0.0.3 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: keychain>=0.14.2.0 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: scrypt>=0.8.0 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: pyparsing>=2.2.0 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: onedrivesdk>=1.1.8 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: dropbox>=7.1.1 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: blockstack-profiles>=0.14.1 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: basicrpc>=0.0.2 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: protocoin>=0.2 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: virtualchain>=0.14.3 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: blockstack-zones>=0.14.3 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: pydrive>=1.3.1 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: boto>=2.38.0 in ./venv/lib/python2.7/site-packages (from blockstack->blockstack-cli==0.1)
Requirement already satisfied: ecdsa>=0.13 in ./venv/lib/python2.7/site-packages (from keylib>=0.1.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: utilitybelt>=0.2.6 in ./venv/lib/python2.7/site-packages (from keylib>=0.1.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: functools32; python_version == "2.7" in ./venv/lib/python2.7/site-packages (from jsonschema>=2.5.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: six>=1.9.0 in ./venv/lib/python2.7/site-packages (from mixpanel>=4.3.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: cryptography>=1.9 in ./venv/lib/python2.7/site-packages (from jsontokens>=0.0.3->blockstack->blockstack-cli==0.1)
Requirement already satisfied: requests>=2.9.1 in ./venv/lib/python2.7/site-packages (from jsontokens>=0.0.3->blockstack->blockstack-cli==0.1)
Requirement already satisfied: bitmerchant>=0.1.8 in ./venv/lib/python2.7/site-packages (from keychain>=0.14.2.0->blockstack->blockstack-cli==0.1)
Requirement already satisfied: urllib3 in ./venv/lib/python2.7/site-packages (from dropbox>=7.1.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: warlock>=1.3.0 in ./venv/lib/python2.7/site-packages (from blockstack-profiles>=0.14.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: google-api-python-client>=1.2 in ./venv/lib/python2.7/site-packages (from pydrive>=1.3.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: PyYAML>=3.0 in ./venv/lib/python2.7/site-packages (from pydrive>=1.3.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: oauth2client>=4.0.0 in ./venv/lib/python2.7/site-packages (from pydrive>=1.3.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: idna>=2.1 in ./venv/lib/python2.7/site-packages (from cryptography>=1.9->jsontokens>=0.0.3->blockstack->blockstack-cli==0.1)
Requirement already satisfied: enum34 in ./venv/lib/python2.7/site-packages (from cryptography>=1.9->jsontokens>=0.0.3->blockstack->blockstack-cli==0.1)
Requirement already satisfied: ipaddress in ./venv/lib/python2.7/site-packages (from cryptography>=1.9->jsontokens>=0.0.3->blockstack->blockstack-cli==0.1)
Requirement already satisfied: cffi>=1.7 in ./venv/lib/python2.7/site-packages (from cryptography>=1.9->jsontokens>=0.0.3->blockstack->blockstack-cli==0.1)
Requirement already satisfied: asn1crypto>=0.21.0 in ./venv/lib/python2.7/site-packages (from cryptography>=1.9->jsontokens>=0.0.3->blockstack->blockstack-cli==0.1)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python2.7/site-packages (from requests>=2.9.1->jsontokens>=0.0.3->blockstack->blockstack-cli==0.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./venv/lib/python2.7/site-packages (from requests>=2.9.1->jsontokens>=0.0.3->blockstack->blockstack-cli==0.1)
Requirement already satisfied: base58>=0.2.1 in ./venv/lib/python2.7/site-packages (from bitmerchant>=0.1.8->keychain>=0.14.2.0->blockstack->blockstack-cli==0.1)
Requirement already satisfied: cachetools>=1.1.1 in ./venv/lib/python2.7/site-packages (from bitmerchant>=0.1.8->keychain>=0.14.2.0->blockstack->blockstack-cli==0.1)
Requirement already satisfied: jsonpatch<2,>=0.10 in ./venv/lib/python2.7/site-packages (from warlock>=1.3.0->blockstack-profiles>=0.14.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: httplib2<1dev,>=0.9.2 in ./venv/lib/python2.7/site-packages (from google-api-python-client>=1.2->pydrive>=1.3.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in ./venv/lib/python2.7/site-packages (from google-api-python-client>=1.2->pydrive>=1.3.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: pyasn1-modules>=0.0.5 in ./venv/lib/python2.7/site-packages (from oauth2client>=4.0.0->pydrive>=1.3.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: pyasn1>=0.1.7 in ./venv/lib/python2.7/site-packages (from oauth2client>=4.0.0->pydrive>=1.3.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: rsa>=3.1.4 in ./venv/lib/python2.7/site-packages (from oauth2client>=4.0.0->pydrive>=1.3.1->blockstack->blockstack-cli==0.1)
Requirement already satisfied: pycparser in ./venv/lib/python2.7/site-packages (from cffi>=1.7->cryptography>=1.9->jsontokens>=0.0.3->blockstack->blockstack-cli==0.1)
Requirement already satisfied: jsonpointer>=1.9 in ./venv/lib/python2.7/site-packages (from jsonpatch<2,>=0.10->warlock>=1.3.0->blockstack-profiles>=0.14.1->blockstack->blockstack-cli==0.1)
Installing collected packages: blockstack-cli
  Found existing installation: blockstack-cli 0.1
    Uninstalling blockstack-cli-0.1:
      Successfully uninstalled blockstack-cli-0.1
  Running setup.py develop for blockstack-cli
Successfully installed blockstack-cli
```

**Comment by jackzampolin** [comment]
A `pip uninstall blockstack` and a `pip install .` fixed this. Closing.
