### ISSUE TITLE
blockstack info error

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#416]
I wanted to check the status of my pending name registration and ran into the following error:

```
Vanquish:~ larry$ /tmp/blockstack-venv/bin/python2.7 /tmp/blockstack-venv/bin/blockstack -y --password <wallet password> --config ~/Library/Application\ Support/Blockstack/config/client.ini --debug info
Set BLOCKSTACK_CLIENT_INTERACTIVE_YES to 1
Set BLOCKSTACK_CLIENT_CONFIG to /Users/larry/Library/Application Support/Blockstack/config/client.ini
Set BLOCKSTACK_DEBUG to 1
Re-exec as `"/tmp/blockstack-venv/bin/python2.7", "/tmp/blockstack-venv/bin/blockstack", "info", "--secrets", "3"`
[2017-05-09 23:13:22,169] [DEBUG] [spv:103] (84951.140735749067712) Using mainnet
[2017-05-09 23:13:22,488] [DEBUG] [cli:419] (84951.140735749067712) Load secrets from 3
[2017-05-09 23:13:22,548] [DEBUG] [client:87] (84951.140735749067712) Connect to node.blockstack.org:6264
[2017-05-09 23:13:22,548] [DEBUG] [client:121] (84951.140735749067712) Loaded storage driver "disk"
[2017-05-09 23:13:22,549] [DEBUG] [client:121] (84951.140735749067712) Loaded storage driver "blockstack_resolver"
[2017-05-09 23:13:22,549] [DEBUG] [client:121] (84951.140735749067712) Loaded storage driver "blockstack_server"
[2017-05-09 23:13:22,550] [DEBUG] [client:121] (84951.140735749067712) Loaded storage driver "http"
[2017-05-09 23:13:22,550] [DEBUG] [client:121] (84951.140735749067712) Loaded storage driver "dht"
[2017-05-09 23:13:23,220] [DEBUG] [rpc:4209] (84951.140735749067712) Connect to API at localhost:6270
[2017-05-09 23:13:23,256] [DEBUG] [rpc:3585] (84951.140735749067712) Remote API endpoint is running version 0.14.2
[2017-05-09 23:13:23,286] [ERROR] [blockstack:69] (84951.140735749067712) string indices must be integers, not str
Traceback (most recent call last):
  File "/tmp/blockstack-venv/bin/blockstack", line 55, in <module>
    result = run_cli()
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/cli.py", line 567, in run_cli
    result = method(args, config_path=config_path)
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py", line 855, in cli_info
    return get_server_info(config_path=config_path, get_local_info=True)
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py", line 843, in get_server_info
    queue_info = cli_get_registrar_info(None, config_path=config_path)
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py", line 757, in cli_get_registrar_info
    entry_type = entry['type']
TypeError: string indices must be integers, not str
{
    "error": "Unexpected error:\nTraceback (most recent call last):\n  File \"/tmp/blockstack-venv/bin/blockstack\", line 55, in <module>\n    result = run_cli()\n  File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/cli.py\", line 567, in run_cli\n    result = method(args, config_path=config_path)\n  File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py\", line 855, in cli_info\n    return get_server_info(config_path=config_path, get_local_info=True)\n  File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py\", line 843, in get_server_info\n    queue_info = cli_get_registrar_info(None, config_path=config_path)\n  File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py\", line 757, in cli_get_registrar_info\n    entry_type = entry['type']\nTypeError: string indices must be integers, not str\n",
    "help": "Try getting latest version of CLI with \"sudo pip install blockstack --upgrade\""
}
Vanquish:~ larry
```

**Comment by kantai** [comment]
Do you have a  `/Users/larry/Library/Application Support/Blockstack/config/api_endpoint.log` ? 

That might help point to the error that ultimately led to this one.

**Comment by larrysalibra** [comment]
Thanks @kantai ! 

It looks like I need to pass the `--api_password` to use `blockstack info` - it works when I add that. 

Can we improve the error message?

Relevant part of `api_endpoint.log`
```
[2017-05-10 00:17:58,613] [DEBUG] [app:100] (80611.140735749067712) Not a valid token
[2017-05-10 00:17:58,618] [DEBUG] [rpc:327] (80611.140735749067712) Wrong API password
[2017-05-10 00:17:58,623] [DEBUG] [rpc:3286] (80611.140735749067712) No authentication needed
127.0.0.1 - - [10/May/2017 00:17:58] "GET /v1/node/ping HTTP/1.1" 200 -
[2017-05-10 00:17:58,634] [DEBUG] [rpc:3269] (80611.140735749067712) 
full path: /v1/node/registrar/state
method: GET
path: /v1/node/registrar/state
qs: {}
headers:
 accept-encoding: gzip, deflate
connection: keep-alive
accept: */*
user-agent: python-requests/2.13.0
host: localhost:6270
content-type: application/json
authorization: bearer 2573b54cb674e0c83c95293daa3c5a946a24fe6ae2870089830e110db94225ff

[2017-05-10 00:17:58,639] [DEBUG] [app:100] (80611.140735749067712) Not a valid token
[2017-05-10 00:17:58,647] [DEBUG] [rpc:327] (80611.140735749067712) Wrong API password
[2017-05-10 00:17:58,651] [INFO] [rpc:3309] (80611.140735749067712) Failed to authenticate caller
127.0.0.1 - - [10/May/2017 00:17:58] "GET /v1/node/registrar/state HTTP/1.1" 403 -```

**Comment by kantai** [comment]
Yep, better error messages are always good, so as of PR #419, the error looks like:

```
$ blockstack info --api_password WRONG_PASSWORD
{
    "error": "Authentication to API service failed. Are you using the correct API password or do you need to pass the correct one with --api_password ?"
}
```

Closing this for now.
