### ISSUE TITLE
blockstack command "price" fails on Win 10 (Bash)

### ISSUE THREAD

**Issue by Almusamim** [blockstack/blockstack-core#429]
`$ blockstack price patrick.id` :
```
{
    "error": "Failed to get some operation fees: Some fee-query tasks failed: preorder_tx_fee,register_tx_fee,update_tx_fee.  Try again with `--debug` for details."
}
```
`$ blockstack price patrick.id --debug` :

```
Re-exec /usr/local/bin/blockstack with ['/usr/local/bin/blockstack', 'price', 'patrick.id']
[2017-05-24 06:25:36,388] [DEBUG] [spv:103] (4615.140657564714816) Using mainnet
[2017-05-24 06:25:37,474] [DEBUG] [client:86] (4615.140657564714816) Connect to node.blockstack.org:6264
[2017-05-24 06:25:37,706] [DEBUG] [client:120] (4615.140657564714816) Loaded storage driver "disk"
[2017-05-24 06:25:37,710] [DEBUG] [client:120] (4615.140657564714816) Loaded storage driver "s3"
[2017-05-24 06:25:37,713] [DEBUG] [client:120] (4615.140657564714816) Loaded storage driver "blockstack_resolver"
[2017-05-24 06:25:37,714] [DEBUG] [client:120] (4615.140657564714816) Loaded storage driver "blockstack_server"
[2017-05-24 06:25:37,716] [DEBUG] [client:120] (4615.140657564714816) Loaded storage driver "http"
[2017-05-24 06:25:37,719] [DEBUG] [client:120] (4615.140657564714816) Loaded storage driver "dht"
[2017-05-24 06:25:37,727] [DEBUG] [rpc:3862] (4615.140657564714816) No PID file /root/.blockstack/api_endpoint.pid
[2017-05-24 06:25:37,729] [DEBUG] [safety:429] (4615.140657564714816) Get total operation fees for running 'preorder,register,update' on patrick.id owned by 3FDZRnKi7twciCaaDAXK36VNKbm457u2Am paid by 32Tt6cF8E29aGQ3qm1NkZCmbV2Y72k3Hot
[2017-05-24 06:25:37,732] [DEBUG] [safety:126] (4615.140657564714816) Run task <function _estimate_update_tx at 0x7fed5e7d26e0>
[2017-05-24 06:25:37,734] [WARNING] [keys:720] (4615.140657564714816) No private key info given, assuming (2, 3) key config
[2017-05-24 06:25:39,945] [WARNING] [nameops:196] (4615.140657564714816) Guessing that owner address 3FDZRnKi7twciCaaDAXK36VNKbm457u2Am requires 2 signatures
[2017-05-24 06:25:41,543] [WARNING] [nameops:165] (4615.140657564714816) Assuming 2 signatures required from p2sh payment address
[2017-05-24 06:25:41,555] [DEBUG] [blockchain:57] (4615.140657564714816) Connect to bitcoind at bitcoin.blockstack.com:8332 (/root/.blockstack/client.ini)
[2017-05-24 06:25:41,560] [DEBUG] [session:129] (4615.140657564714816) [4615] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2017-05-24 06:25:42,064] [ERROR] [blockchain:144] (4615.140657564714816) -342: non-JSON HTTP response with '401 Unauthorized' from server
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/backend/blockchain.py", line 129, in get_tx_fee
    fee = bitcoind_client.estimatefee(2)
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 139, in __call__
    response = self._get_response()
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 187, in _get_response
    'code': -342, 'message': 'non-JSON HTTP response with \'%i %s\' from server' % (http_response.status, http_response.reason)})
JSONRPCException: -342: non-JSON HTTP response with '401 Unauthorized' from server
[2017-05-24 06:25:42,081] [DEBUG] [blockchain:145] (4615.140657564714816) Failed to estimate fee
[2017-05-24 06:25:42,082] [ERROR] [nameops:430] (4615.140657564714816) Failed to get tx fee
[2017-05-24 06:25:42,089] [DEBUG] [blockchain:57] (4615.140657564714816) Connect to bitcoind at bitcoin.blockstack.com:8332 (/root/.blockstack/client.ini)
[2017-05-24 06:25:42,096] [DEBUG] [session:129] (4615.140657564714816) [4615] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2017-05-24 06:25:42,605] [ERROR] [blockchain:144] (4615.140657564714816) -342: non-JSON HTTP response with '401 Unauthorized' from server
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/backend/blockchain.py", line 129, in get_tx_fee
    fee = bitcoind_client.estimatefee(2)
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 139, in __call__
    response = self._get_response()
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 187, in _get_response
    'code': -342, 'message': 'non-JSON HTTP response with \'%i %s\' from server' % (http_response.status, http_response.reason)})
JSONRPCException: -342: non-JSON HTTP response with '401 Unauthorized' from server
[2017-05-24 06:25:42,616] [DEBUG] [blockchain:145] (4615.140657564714816) Failed to estimate fee
[2017-05-24 06:25:42,622] [DEBUG] [safety:128] (4615.140657564714816) Task exit <function _estimate_update_tx at 0x7fed5e7d26e0>
[2017-05-24 06:25:42,628] [DEBUG] [safety:126] (4615.140657564714816) Run task <function _estimate_register_tx at 0x7fed5e7d2668>
[2017-05-24 06:25:42,630] [WARNING] [keys:720] (4615.140657564714816) No private key info given, assuming (2, 3) key config
[2017-05-24 06:25:44,781] [WARNING] [nameops:196] (4615.140657564714816) Guessing that owner address 3FDZRnKi7twciCaaDAXK36VNKbm457u2Am requires 2 signatures
[2017-05-24 06:25:46,238] [WARNING] [nameops:165] (4615.140657564714816) Assuming 2 signatures required from p2sh payment address
[2017-05-24 06:25:46,243] [DEBUG] [blockchain:57] (4615.140657564714816) Connect to bitcoind at bitcoin.blockstack.com:8332 (/root/.blockstack/client.ini)
[2017-05-24 06:25:46,244] [DEBUG] [session:129] (4615.140657564714816) [4615] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2017-05-24 06:25:46,747] [ERROR] [blockchain:144] (4615.140657564714816) -342: non-JSON HTTP response with '401 Unauthorized' from server
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/backend/blockchain.py", line 129, in get_tx_fee
    fee = bitcoind_client.estimatefee(2)
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 139, in __call__
    response = self._get_response()
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 187, in _get_response
    'code': -342, 'message': 'non-JSON HTTP response with \'%i %s\' from server' % (http_response.status, http_response.reason)})
JSONRPCException: -342: non-JSON HTTP response with '401 Unauthorized' from server
[2017-05-24 06:25:46,795] [DEBUG] [blockchain:145] (4615.140657564714816) Failed to estimate fee
[2017-05-24 06:25:46,796] [ERROR] [nameops:318] (4615.140657564714816) Failed to get tx fee
[2017-05-24 06:25:46,799] [DEBUG] [blockchain:57] (4615.140657564714816) Connect to bitcoind at bitcoin.blockstack.com:8332 (/root/.blockstack/client.ini)
[2017-05-24 06:25:46,806] [DEBUG] [session:129] (4615.140657564714816) [4615] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2017-05-24 06:25:47,323] [ERROR] [blockchain:144] (4615.140657564714816) -342: non-JSON HTTP response with '401 Unauthorized' from server
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/backend/blockchain.py", line 129, in get_tx_fee
    fee = bitcoind_client.estimatefee(2)
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 139, in __call__
    response = self._get_response()
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 187, in _get_response
    'code': -342, 'message': 'non-JSON HTTP response with \'%i %s\' from server' % (http_response.status, http_response.reason)})
JSONRPCException: -342: non-JSON HTTP response with '401 Unauthorized' from server
[2017-05-24 06:25:47,331] [DEBUG] [blockchain:145] (4615.140657564714816) Failed to estimate fee
[2017-05-24 06:25:47,332] [DEBUG] [safety:128] (4615.140657564714816) Task exit <function _estimate_register_tx at 0x7fed5e7d2668>
[2017-05-24 06:25:47,335] [DEBUG] [safety:126] (4615.140657564714816) Run task <function _estimate_preorder_tx at 0x7fed5e7d25f0>
[2017-05-24 06:25:47,679] [WARNING] [keys:720] (4615.140657564714816) No private key info given, assuming (2, 3) key config
[2017-05-24 06:25:49,037] [WARNING] [nameops:196] (4615.140657564714816) Guessing that owner address 3FDZRnKi7twciCaaDAXK36VNKbm457u2Am requires 2 signatures
[2017-05-24 06:25:50,560] [WARNING] [nameops:165] (4615.140657564714816) Assuming 2 signatures required from p2sh payment address
[2017-05-24 06:25:50,563] [DEBUG] [blockchain:57] (4615.140657564714816) Connect to bitcoind at bitcoin.blockstack.com:8332 (/root/.blockstack/client.ini)
[2017-05-24 06:25:50,564] [DEBUG] [session:129] (4615.140657564714816) [4615] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2017-05-24 06:25:51,063] [ERROR] [blockchain:144] (4615.140657564714816) -342: non-JSON HTTP response with '401 Unauthorized' from server
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/backend/blockchain.py", line 129, in get_tx_fee
    fee = bitcoind_client.estimatefee(2)
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 139, in __call__
    response = self._get_response()
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 187, in _get_response
    'code': -342, 'message': 'non-JSON HTTP response with \'%i %s\' from server' % (http_response.status, http_response.reason)})
JSONRPCException: -342: non-JSON HTTP response with '401 Unauthorized' from server
[2017-05-24 06:25:51,082] [DEBUG] [blockchain:145] (4615.140657564714816) Failed to estimate fee
[2017-05-24 06:25:51,085] [ERROR] [nameops:273] (4615.140657564714816) Failed to get tx fee
[2017-05-24 06:25:51,090] [DEBUG] [blockchain:57] (4615.140657564714816) Connect to bitcoind at bitcoin.blockstack.com:8332 (/root/.blockstack/client.ini)
[2017-05-24 06:25:51,094] [DEBUG] [session:129] (4615.140657564714816) [4615] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2017-05-24 06:25:51,603] [ERROR] [blockchain:144] (4615.140657564714816) -342: non-JSON HTTP response with '401 Unauthorized' from server
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/backend/blockchain.py", line 129, in get_tx_fee
    fee = bitcoind_client.estimatefee(2)
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 139, in __call__
    response = self._get_response()
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 187, in _get_response
    'code': -342, 'message': 'non-JSON HTTP response with \'%i %s\' from server' % (http_response.status, http_response.reason)})
JSONRPCException: -342: non-JSON HTTP response with '401 Unauthorized' from server
[2017-05-24 06:25:51,618] [DEBUG] [blockchain:145] (4615.140657564714816) Failed to estimate fee
[2017-05-24 06:25:51,621] [DEBUG] [safety:128] (4615.140657564714816) Task exit <function _estimate_preorder_tx at 0x7fed5e7d25f0>
[2017-05-24 06:25:51,627] [DEBUG] [safety:126] (4615.140657564714816) Run task <function _get_balance at 0x7fed5e7d2578>
[2017-05-24 06:25:52,371] [DEBUG] [safety:128] (4615.140657564714816) Task exit <function _get_balance at 0x7fed5e7d2578>
[2017-05-24 06:25:52,379] [DEBUG] [safety:751] (4615.140657564714816) Balance is 0 satoshis
[2017-05-24 06:25:52,381] [ERROR] [safety:765] (4615.140657564714816) Task preorder failed to get tx fee
[2017-05-24 06:25:52,382] [ERROR] [safety:765] (4615.140657564714816) Task register failed to get tx fee
[2017-05-24 06:25:52,385] [ERROR] [safety:765] (4615.140657564714816) Task update failed to get tx fee
[2017-05-24 06:25:52,386] [DEBUG] [safety:783] (4615.140657564714816) Total cost of preorder,register,update is 0 satoshis
[2017-05-24 06:25:52,388] [ERROR] [safety:799] (4615.140657564714816) Some fee-query tasks failed: preorder_tx_fee,register_tx_fee,update_tx_fee
[2017-05-24 06:25:52,392] [ERROR] [actions:570] (4615.140657564714816) Failed to get all operation fees: Some fee-query tasks failed: preorder_tx_fee,register_tx_fee,update_tx_fee
{
    "error": "Failed to get some operation fees: Some fee-query tasks failed: preorder_tx_fee,register_tx_fee,update_tx_fee.  Try again with `--debug` for details."
}
```

**Comment by jcnelson** [comment]
Hey @Almusamim, apologies for the late reply.

Please check your `~/.blockstack/client.ini` to confirm that your `[bitcoind]` section looks like this:

```
[bitcoind]
passwd = blockstacksystem
regtest = False
spv_path = /home/jude/.virtualchain-spv-headers.dat
server = bitcoin.blockstack.com
user = blockstack
timeout = 300.0
port = 8332
```

**Comment by Almusamim** [comment]
@jcnelson sorry got this working by running the blockstack setup again.. 
I only had different password but changing it to blockstacksystem made it work i guess.

Thanks for your help :)

**Comment by jackzampolin** [comment]
Closing as working!
