### ISSUE TITLE
Problems with Blockstack integration test

### ISSUE THREAD

**Issue by qzhang90** [blockstack/blockstack-core#434]
I am trying to setup Blockstack on a single machine and encountered the following 2 problems. I looked up the Blockstack forums on github, the slack channel, as well as going though the Blockstack papers, but still have not solve them. Can you please help me to fix these problems?  Thanks a lot!

The problems are as following:

**Problem 1:** 

I followed the instructions in README of https://github.com/blockstack/blockstack-integration-tests. After executing "blockstack-test-scenario blockstack_integration_tests.scenarios.rpc_register", the system shows:

SUCCESS blockstack_integration_tests.scenarios.rpc_register
Not running (/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.rpc_register/client/api_endpoint.pid)
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

I am wondering how to solve the error above. 

**Problem 2:**

I was following the instructions described at https://github.com/blockstack/blockstack-integration-tests. A wallet with the following information was created using "./blockstack-core/bin/blockstack setup_wallet"
{...
"payment_addresses": [
"2N7qjaCYNd8CVvQA71Dsqw5nhr6DqzY4dLM"
],
"version": "0.14.1"
},
"wallet_password": "12345678"
}

Then, I ran ./blockstack-core/bin/blockstack api start, and it asked for the wallet password. I entered "12345678", but the system complained:

**[2017-05-23 11:00:43,646] [ERROR] [rpc:3523] (4478.139654815393536) Failed to start API endpoint: exit code 1
[2017-05-23 11:00:43,649] [ERROR] [rpc:3524] (4478.139654815393536) Error log:
[2017-05-23 11:00:43,303] [DEBUG] [spv:110] (4485.140583757747968) Using testnet/regtest
[2017-05-23 11:00:43,568] [WARNING] [config:112] (4485.140583757747968) TX_MIN_CONFIRMATIONS = 0
[2017-05-23 11:00:43,568] [WARNING] [config:300] (4485.140583757747968) CONFIG_PATH = /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.name_preorder_register/client/client.ini
[2017-05-23 11:00:43,584] [ERROR] [wallet:368] (4485.140583757747968) 'encrypted_master_private_key'
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/blockstack_client-0.14.0.12-py2.7.egg/blockstack_client/wallet.py", line 364, in decrypt_wallet
hex_privkey = aes_decrypt(data['encrypted_master_private_key'], hex_password)
KeyError: 'encrypted_master_private_key'
[2017-05-23 11:00:43,585] [ERROR] [rpc:612] (4485.140583757747968) Failed to load wallet: Incorrect password
Failed to load wallet: Incorrect password

{
"error": "Failed to start API server"
}**

**Comment by jcnelson** [comment]
Hi @qzhang90, thanks for reporting!

Re: Problem 1

> I am wondering how to solve the error above.

That's not an error :)  If you see `SUCCESS`, then everything worked.  The remaining messages are just debugging information relating to shutting the test framework down.

Re: Problem 2:

```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/blockstack_client-0.14.0.12-py2.7.egg/blockstack_client/wallet.py"
```
This file is from an old version of Blockstack.  Please be sure that you're using the latest stable software (0.14.1), and that you have uninstalled the old versions.  Alternatively, you can try from a virtualenv with the latest version so it won't affect your system Python files.

Hope this helps!

**Comment by qzhang90** [comment]
Thanks @jcnelson . I was using the get_started.sh (https://github.com/blockstack/blockstack-integration-tests/blob/master/get_started.sh). Lines 3 is "BRANCH="rc-0.14.0". In order to use the latest stable software (0.14.1), shall I simply switch the "rc-0.14.0" to "rc-0.14.1"?

**Comment by jcnelson** [comment]
Ah, I see.  I just fixed the `get_started.sh` script to use `master` and I cleaned up the list of package dependencies.  Looks like we didn't clean that script up for the 0.14.1 release.  Thanks!

**Comment by qzhang90** [comment]
Thanks @jcnelson . I will try that out and let you know. 

BTW, the blockstack_integration_tests directory is currently under the blockstack-core directory. Shall I move the blockstack_integration_tests out to a separate place, or I can do everything with the current directory hierarchy？

**Comment by qzhang90** [comment]
Hi @jcnelson . When I ran the "blockstack-test-scenario --interactive 10 blockstack_integration_tests.scenarios.rpc_register" in blockstack_integration_tests, the following error occurs. Can you please let me know how to solve it? Thanks!

[2017-05-27 19:49:07,327] [DEBUG] [session:129] (47270.140191801001728) [47270] Connect to bitcoind at http://blockstack@localhost:18332, timeout=60.0
127.0.0.1 - - [27/May/2017 19:49:07] "POST /RPC2 HTTP/1.0" 200 -
Traceback (most recent call last):
  File "./bin/blockstack-test-scenario", line 1077, in <module>
    rc = run_scenario( scenario, config_file, client_config_file, interactive=interactive, blocktime=blocktime )
  File "./bin/blockstack-test-scenario", line 533, in run_scenario
    res = rpcclient.getinfo()
  File "/usr/local/lib/python2.7/dist-packages/blockstack_integration_tests-0.14.1-py2.7.egg/blockstack_integration_tests/scenarios/testlib.py", line 145, in inner
    r = c(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/blockstack-0.14.1.7-py2.7.egg/blockstack_client/proxy.py", line 138, in inner
    res = func(*args, **kw)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<type 'exceptions.AttributeError'>:'NoneType' object has no attribute 'gc_event'">

**Comment by jackzampolin** [comment]
Closing this as stale. Much of this code has changed since this issue was open. We also have a docker setup that helps avoid issues like this. Please reopen if you continue experience problems.
