### ISSUE TITLE
AttributeError: 'module' object has no attribute 'packages'

### ISSUE THREAD

**Issue by qzhang90** [blockstack/blockstack-core#437]
Python 2.7.12
Ubuntu: 16.04.2

After installing the Blockstack using pip2, I tried "blockstack info", but the following error occurs:

root@ubuntu:/home/qi# blockstack info
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/__init__.py", line 24, in <module>
    import app
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/app.py", line 40, in <module>
    import wallet
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/wallet.py", line 48, in <module>
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'

**Comment by jcnelson** [comment]
Thanks for reporting!  I think you're using an older version of `requests`.  Which `requests` are you on?

**Comment by shadowsyntax** [comment]
I'm having similar issues.

Installed gmp, libffi and openssl with `brew install --force`

```
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/__init__.py", line 24, in <module>
    import app
  File "/usr/local/lib/python2.7/site-packages/blockstack_client/app.py", line 31, in <module>
    import jsonschema
  File "/usr/local/lib/python2.7/site-packages/jsonschema/__init__.py", line 18, in <module>
    from jsonschema.validators import (
  File "/usr/local/lib/python2.7/site-packages/jsonschema/validators.py", line 8, in <module>
    import requests
  File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 78, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 124, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

**Comment by jcnelson** [comment]
Thanks for reporting the stack trace.  I've seen this before when `requests` is out of date.  Can you try `pip install --upgrade requests` and seeing if this goes away?  You may also want to upgrading `pyopenssl` in the same way, if that doesn't work.

**Comment by shadowsyntax** [comment]
@jcnelson thanks ... It was actually the `pyopenssl` that was giving the issue. After the upgrade everything works fine.

**Comment by Jyouhou** [comment]
@jcnelson thanks.

I was working with another package when the same error message prompted.  After upgrading `requests`, it works.

**Comment by vhosakot** [comment]
I saw the `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error too and `sudo pip install pyOpenSSL==16.2.0` resolved it for me!
