### ISSUE TITLE
ImportError: No module named multibackend

### ISSUE THREAD

**Issue by sunnya97** [blockstack/blockstack-core#443]
Python 2.7.13
Ubuntu: 17.04

Followed all the instructions for installing blockstack, but run into this import error.

Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/__init__.py", line 24, in <module>
    import app
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/app.py", line 37, in <module>
    import jsontokens
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/__init__.py", line 10, in <module>
    from token_signer import TokenSigner
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/token_signer.py", line 24, in <module>
    from .key_loading import load_signing_key
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/key_loading.py", line 14, in <module>
    from cryptography.hazmat.backends.multibackend import MultiBackend
ImportError: No module named multibackend

**Comment by kantai** [comment]
Thanks for finding this -- 
the latest Cryptography release removed this interface, and we'll update jsontokens to remove the dependence on it.

In the meantime, you can either install a developer version of `jsontokens` with

```
$ pip install git+https://github.com/kantai/jsontokens-py.git --upgrade
```

or try to downgrade Cryptography.

**Comment by jcnelson** [comment]
Looks like Cryptography 1.9 was just released.  You'll need Cryptography 1.8.x or lower for the time being. We'll patch jsontokens-py as soon as we can :)

**Comment by sunnya97** [comment]
Ok thanks!  Also, I'm getting the error ImportError: cannot import name tx_serialize.
Is there a another version of virtualchain I'm supposed to be using?  I'm currently using git+https://github.com/blockstack/virtualchain.git@rc-0.14.2

Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/__init__.py", line 24, in <module>
    import app
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/app.py", line 40, in <module>
    import wallet
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/wallet.py", line 50, in <module>
    from .backend.crypto.utils import get_address_from_privkey
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/backend/__init__.py", line 21, in <module>
    import registrar
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/backend/registrar.py", line 49, in <module>
    from .queue import get_queue_state, in_queue, queue_removeall
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/backend/queue.py", line 33, in <module>
    from ..proxy import get_default_proxy
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/proxy.py", line 42, in <module>
    import storage
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/storage.py", line 47, in <module>
    from scripts import is_name_valid
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/scripts.py", line 34, in <module>
    from virtualchain import tx_serialize, tx_deserialize, tx_script_to_asm, tx_output_parse_scriptPubKey
ImportError: cannot import name tx_serialize

**Comment by jcnelson** [comment]
Hi @sunnya97, can you try pulling from `rc-0.14.2`, as well as from `virtualchain`'s `rc-0.14.2` branch?  Looks like you're using an outdated package.

**Comment by jcnelson** [comment]
Just pushed `jsontokens-py` to PyPI, which is compatible with cryptography 1.9

**Comment by jcnelson** [comment]
We upgraded everything to use cryptography 1.9 in the 0.14.2 release.  I'm going to go ahead and close this; please re-open if the problem has persisted in this release.
