### ISSUE TITLE
error: Failed to save keys

### ISSUE THREAD

**Issue by dantrevino** [blockstack/blockstack-core#448]
```
dan  ⋯  scripts  blockstack  bin  blockstack price foo.id --debug                                                                                                                                                                                         
Re-exec /home/dan/.local/bin/blockstack with ['/home/dan/.local/bin/blockstack', 'price', 'foo.id']
[2017-06-02 14:07:36,866] [DEBUG] [spv:103] (21771.139688835729152) Using mainnet
[2017-06-02 14:07:36,931] [DEBUG] [client:86] (21771.139688835729152) Connect to node.blockstack.org:6264
[2017-06-02 14:07:36,945] [DEBUG] [client:120] (21771.139688835729152) Loaded storage driver "disk"
[2017-06-02 14:07:36,946] [DEBUG] [client:120] (21771.139688835729152) Loaded storage driver "blockstack_resolver"
[2017-06-02 14:07:36,946] [DEBUG] [client:120] (21771.139688835729152) Loaded storage driver "blockstack_server"
[2017-06-02 14:07:36,947] [DEBUG] [client:120] (21771.139688835729152) Loaded storage driver "http"
[2017-06-02 14:07:36,947] [DEBUG] [client:120] (21771.139688835729152) Loaded storage driver "dht"
[2017-06-02 14:07:36,947] [DEBUG] [rpc:3797] (21771.139688835729152) Not running: 5631 (/home/dan/.blockstack/api_endpoint.pid)
[2017-06-02 14:07:36,947] [DEBUG] [rpc:3873] (21771.139688835729152) RPC running (/home/dan/.blockstack/api_endpoint.pid)
[2017-06-02 14:07:36,947] [DEBUG] [actions:541] (21771.139688835729152) Try to get wallet keys from API server
[2017-06-02 14:07:36,947] [DEBUG] [rpc:3797] (21771.139688835729152) Not running: 5631 (/home/dan/.blockstack/api_endpoint.pid)
[2017-06-02 14:07:36,947] [DEBUG] [rpc:3873] (21771.139688835729152) RPC running (/home/dan/.blockstack/api_endpoint.pid)
[2017-06-02 14:07:36,951] [DEBUG] [rpc:3474] (21771.139688835729152) Connect to API at localhost:6270
[2017-06-02 14:07:36,957] [DEBUG] [actions:993] (21771.139688835729152) unlocking wallet (/home/dan/.blockstack)
[2017-06-02 14:07:36,960] [DEBUG] [rpc:3474] (21771.139688835729152) Connect to API at localhost:6270
Enter wallet password: 
[2017-06-02 14:07:40,913] [DEBUG] [rpc:3474] (21771.139688835729152) Connect to API at localhost:6270
[2017-06-02 14:07:40,913] [DEBUG] [wallet:895] (21771.139688835729152) Saving keys to memory
[2017-06-02 14:07:40,914] [ERROR] [wallet:900] (21771.139688835729152) <module 'blockstack_client.wallet' from '/home/dan/.local/lib/python2.7/site-packages/blockstack_client/wallet.pyc'> is not JSON serializable
Traceback (most recent call last):
  File "/home/dan/.local/lib/python2.7/site-packages/blockstack_client/wallet.py", line 897, in save_keys_to_memory
    data = proxy.backend_set_wallet(wallet_keys)
  File "/home/dan/.local/lib/python2.7/site-packages/blockstack_client/rpc.py", line 3226, in backend_set_wallet
    req = requests.put( 'http://localhost:{}/v1/wallet/keys'.format(self.port), timeout=self.timeout, data=json.dumps(wallet), headers=headers )
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <module 'blockstack_client.wallet' from '/home/dan/.local/lib/python2.7/site-packages/blockstack_client/wallet.pyc'> is not JSON serializable
[2017-06-02 14:07:40,914] [ERROR] [actions:996] (21771.139688835729152) unlock_wallet: Failed to save keys
{
    "error": "Failed to save keys"
}
```

**Comment by jackzampolin** [comment]
We have had a number of new versions since this issue. Closing. If you continue to experience this problem please re-open
