### ISSUE TITLE
Fee calculation is too low in current rc-0.14.2

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#459]
Testing the current version in rc-0.14.2 (the alpha bundle posted by @larrysalibra on Mac, which uses Core at 6cdf12bd529c00f9e829f2d9bca8b4fceba32d16) 

My UPDATE transaction is still in the mempool after a couple of hours. Looks like the fee rate of the tx is ~120 satoshis/byte, while https://bitcoinfees.21.co currently recommends ~390 satoshis/byte.

**Comment by jcnelson** [comment]
Can you post the output of `blockstack --debug price YOUR_NAME.id`?

**Comment by kantai** [comment]
```
$ python2.7 blockstack price shayna.id --debug
Set BLOCKSTACK_DEBUG to 1
Re-exec as `"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python", "blockstack", "price", "shayna.id"`
[2017-06-16 18:23:06,665] [DEBUG] [spv:103] (1710.140736650040256) Using mainnet
[2017-06-16 18:23:06,805] [DEBUG] [config:887] (1710.140736650040256) Override blockstack-client.port from 6264 to 6264
[2017-06-16 18:23:06,807] [DEBUG] [client:94] (1710.140736650040256) Connect to node.blockstack.org:6264
[2017-06-16 18:23:06,807] [DEBUG] [client:128] (1710.140736650040256) Loaded storage driver "disk"
[2017-06-16 18:23:06,808] [DEBUG] [client:128] (1710.140736650040256) Loaded storage driver "blockstack_resolver"
[2017-06-16 18:23:06,809] [DEBUG] [client:128] (1710.140736650040256) Loaded storage driver "blockstack_server"
[2017-06-16 18:23:06,809] [DEBUG] [client:128] (1710.140736650040256) Loaded storage driver "http"
[2017-06-16 18:23:06,809] [DEBUG] [client:128] (1710.140736650040256) Loaded storage driver "dht"
[2017-06-16 18:23:06,810] [DEBUG] [rpc:4674] (1710.140736650040256) RPC running (/Users/aaron/.blockstack/api_endpoint.pid)
[2017-06-16 18:23:06,810] [DEBUG] [actions:630] (1710.140736650040256) Try to get wallet keys from API server
[2017-06-16 18:23:06,811] [DEBUG] [rpc:4674] (1710.140736650040256) RPC running (/Users/aaron/.blockstack/api_endpoint.pid)
[2017-06-16 18:23:06,812] [DEBUG] [config:887] (1710.140736650040256) Override blockstack-client.port from 6264 to 6264
[2017-06-16 18:23:06,814] [DEBUG] [rpc:4180] (1710.140736650040256) Connect to API at localhost:6270
[2017-06-16 18:23:06,815] [DEBUG] [config:887] (1710.140736650040256) Override blockstack-client.port from 6264 to 6264
[2017-06-16 18:23:06,923] [DEBUG] [rpc:3568] (1710.140736650040256) Remote API endpoint is running version 0.14.2
[2017-06-16 18:23:06,989] [DEBUG] [config:887] (1710.140736650040256) Override blockstack-client.port from 6264 to 6264
[2017-06-16 18:23:06,991] [DEBUG] [rpc:4180] (1710.140736650040256) Connect to API at localhost:6270
[2017-06-16 18:23:06,992] [DEBUG] [config:887] (1710.140736650040256) Override blockstack-client.port from 6264 to 6264
[2017-06-16 18:23:07,016] [DEBUG] [rpc:3568] (1710.140736650040256) Remote API endpoint is running version 0.14.2
[2017-06-16 18:23:07,082] [DEBUG] [blockchain:46] (1710.140736650040256) Connect to bitcoind at bitcoin.blockstack.com:8332 (/Users/aaron/.blockstack/client.ini)
[2017-06-16 18:23:07,082] [DEBUG] [session:103] (1710.140736650040256) [1710] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2017-06-16 18:23:07,130] [DEBUG] [blockchain:128] (1710.140736650040256) Bitcoin estimatefee(2) is 0.00387659
[2017-06-16 18:23:07,130] [DEBUG] [actions:537] (1710.140736650040256) Get operation fees for preorder, register, update
[2017-06-16 18:23:07,135] [DEBUG] [config:887] (1710.140736650040256) Override blockstack-client.port from 6264 to 6264
[2017-06-16 18:23:07,137] [DEBUG] [safety:685] (1710.140736650040256) Getting UTXOs for 3E1DpCz8RLmNmtNh8jENTDxmi4a39Ui6bz
[2017-06-16 18:23:07,138] [DEBUG] [insight_api:41] (1710.140736650040256) GET https://utxo.blockstack.org/insight-api/addr/3E1DpCz8RLmNmtNh8jENTDxmi4a39Ui6bz/utxo
[2017-06-16 18:23:07,606] [DEBUG] [insight_api:52] (1710.140736650040256) 3E1DpCz8RLmNmtNh8jENTDxmi4a39Ui6bz has 1 UTXOs
[2017-06-16 18:23:07,606] [DEBUG] [insight_api:41] (1710.140736650040256) GET https://utxo.blockstack.org/insight-api/addr/39cRw6iMETgz9vpqGfQzCcfdcujWat9rPU/utxo
[2017-06-16 18:23:08,023] [DEBUG] [insight_api:52] (1710.140736650040256) 39cRw6iMETgz9vpqGfQzCcfdcujWat9rPU has 2 UTXOs
[2017-06-16 18:23:08,023] [DEBUG] [safety:697] (1710.140736650040256) Balance of 39cRw6iMETgz9vpqGfQzCcfdcujWat9rPU is 687742 satoshis
[2017-06-16 18:23:08,023] [ERROR] [blockstack:69] (1710.140736650040256) list index out of range
Traceback (most recent call last):
  File "blockstack", line 55, in <module>
    result = run_cli()
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/cli.py", line 567, in run_cli
    result = method(args, config_path=config_path)
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py", line 661, in cli_price
    payment_address=payment_address, owner_address=owner_address, transfer_address=transfer_address, config_path=config_path, proxy=proxy )
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py", line 542, in get_price_and_fees
    owner_address=owner_address, transfer_address=transfer_address )
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/safety.py", line 701, in get_operation_fees
    estimated_owner_inputs = estimate_transaction_inputs(operations, owner_utxos, owner_address=owner_address)['inputs']
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/safety.py", line 588, in estimate_transaction_inputs
    one_input = _consolidate(inputs)
  File "/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/safety.py", line 583, in _consolidate
    ret = inps[0]
IndexError: list index out of range
{
    "error": "Unexpected error:\nTraceback (most recent call last):\n  File \"blockstack\", line 55, in <module>\n    result = run_cli()\n  File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/cli.py\", line 567, in run_cli\n    result = method(args, config_path=config_path)\n  File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py\", line 661, in cli_price\n    payment_address=payment_address, owner_address=owner_address, transfer_address=transfer_address, config_path=config_path, proxy=proxy )\n  File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py\", line 542, in get_price_and_fees\n    owner_address=owner_address, transfer_address=transfer_address )\n  File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/safety.py\", line 701, in get_operation_fees\n    estimated_owner_inputs = estimate_transaction_inputs(operations, owner_utxos, owner_address=owner_address)['inputs']\n  File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/safety.py\", line 588, in estimate_transaction_inputs\n    one_input = _consolidate(inputs)\n  File \"/private/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/safety.py\", line 583, in _consolidate\n    ret = inps[0]\nIndexError: list index out of range\n",
    "help": "Try getting latest version of CLI with \"sudo pip install blockstack --upgrade\""
}
```

**Comment by jcnelson** [comment]
Thanks; pushed a fix to `rc-0.14.2-portal`.

This line is interesting however:
```
[2017-06-16 18:23:07,130] [DEBUG] [blockchain:128] (1710.140736650040256) Bitcoin estimatefee(2) is 0.00387659
```

This is the BTC fee per KB, which works out to about 388 satoshis per byte (as 21.co expects).

Do you have:

* the `NAME_UPDATE` txid?
* the `api_endpoint.log` file for your Core node?

**Comment by kantai** [comment]
Transaction:

https://explorer.blockstack.org/tx/c4a4d2faaaed0c9193cbd8661eb1e60053a46195ae81aa2b4c084070e18330ce

**Comment by kantai** [comment]
Closing with the merging in of #461
