### ISSUE TITLE
Core doesn't accept currently deployed authentication request tokens

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#463]
@jcnelson @kantai fixed a few problems with this yesterday -  i'm still having problems on 15b0a779448aeaf84db9a7ae701b3f999f540a45

```
[2017-06-23 15:08:47,750] [ERROR] [rpc:3439] (1954.140736935191488) '' does not match '.+'

Failed validating 'pattern' in schema['properties']['device_id']:
    {'pattern': '.+', 'type': 'string'}

On instance['device_id']:
    ''
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 3436, in _dispatch
    return route_method( session, path_info, *route_args )
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 512, in GET_auth
    session_lifetime=session_lifetime, config_path=self.server.config_path)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/app.py", line 86, in app_make_session
    jsonschema.validate(ses, APP_SESSION_SCHEMA)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: '' does not match '.+'

Failed validating 'pattern' in schema['properties']['device_id']:
    {'pattern': '.+', 'type': 'string'}

On instance['device_id']:
    ''
127.0.0.1 - - [23/Jun/2017 15:08:47] "GET /v1/auth?authRequest=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJhcHBfZG9tYWluIjoiaGVsbG9ibG9ja3N0YWNrLmNvbSIsIm1ldGhvZHMiOltdLCJhcHBfcHVibGljX2tleSI6IjAyZDcxMjM3NWRiMWU0NGYxYTM0MTUyN2U2ZDFhNTIyZGZkOWU4ODU1ZDFlZTdlNjFkYWRlMDQ2ZWFkYWE1MTNhYiJ9.MrEVp-eesstfQPs9juDdugpS3XQtuRZYNLGCcR3jXsAVARsp9-etMH0cAX3Pt0HGTVN91y_YIhDLpUsks07ShQ HTTP/1.1" 500 -
```

**Comment by kantai** [comment]
Closing this with merger of #465 and the correct circleCI test failure behavior.
