### ISSUE TITLE
Time out issue, potential SYN flooding

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#493]
I recently upgraded a few production servers to the 0.14.2 release and I'm noticing that the servers are timing out. Here is the log:

```
[2017-07-12 15:24:40,530] [ERROR] [proxy:1918] (12101.140348105152256) timed out
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/proxy.py", line 1900, in get_zonefile_inventory
    zf_inv = proxy.get_zonefile_inventory(bit_offset, bit_count)
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/proxy.py", line 136, in inner
    res = func(*args, **kw)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1313, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/proxy.py", line 80, in getresponse
    return self._conn.getresponse(**kw)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
[2017-07-12 15:24:40,531] [ERROR] [proxy:1920] (12101.140348105152256) Caught exception while connecting to Blockstack node: timed out
[2017-07-12 15:24:40,531] [ERROR] [atlas:1852] (12101.140348105152256) Failed to get inventory for 0-524288 from 52.171.219.167:6264: Failed to contact Blockstack node.  Try again with `--debug`.
[2017-07-12 15:24:40,531] [DEBUG] [atlas:1890] (12101.140348105152256) Failed to sync inventory for 52.171.219.167:6264 from 0 to 524288
[2017-07-12 15:24:40,532] [DEBUG] [atlas:1942] (12101.140348105152256) Set zonefile inventory 52.171.219.167:6264: 
[2017-07-12 15:24:40,532] [DEBUG] [atlas:1996] (12101.140348105152256) blockstack-14-2-registrar-broadcast:6264: inventory of 52.171.219.167:6264 is now ''
```

I installed via pip2 and here are the relevant packages:
```
blockstack==0.14.2.0
blockstack-profiles==0.14.1
blockstack-zones==0.14.1
```

**Comment by jcnelson** [comment]
Some context: the node works for a few hours and then this behavior starts.

**Comment by muneeb-ali** [comment]
Seems to be caused by SYN flooding protection: 

```
[37477.661930] TCP: request_sock_TCP: Possible SYN flooding on port 6264. Sending cookies.  Check SNMP counters.
[59687.700648] TCP: request_sock_TCP: Possible SYN flooding on port 6264. Sending cookies.  Check SNMP counters.
```

**Comment by jcnelson** [comment]
Try adding these to your `/etc/sysctl.conf`:

```
net.ipv4.tcp_max_syn_backlog = 32765
net.ipv4.tcp_fin_timeout=30
```

If you're feeling adventurous, you can also disable SYN cookies:

```
net.ipv4.tcp_syncookies=0
```

To activate, run `sudo sysctl -p /etc/sysctl.conf`.

**Comment by muneeb-ali** [comment]
UPDATE: I increased the SYN backlog on a server and disabled SYN cookies and still running into the timeout issue.

**Comment by jcnelson** [comment]
Looks like we also have to increase `net.core.somaxconn`.  As per https://blog.dubbelboer.com/2012/04/09/syn-cookies.html, this is not an obvious thing.

**Comment by jackzampolin** [comment]
I'm closing this as Won't Fix. This is an issue with some core Python libraries. If you run into this issue put an `nginx` instance in front of the node. This solves the issue.
