### ISSUE TITLE
Zone file replication error: "ValidationError: 0 is less than the minimum of 1"

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#494]
Saw this error "ValidationError: 0 is less than the minimum of 1"

Not sure if this is a problem or not. 
```
[2017-07-12 22:08:07,025] [DEBUG] [registrar:532] (81541.123145521098752) Zone file update on 'zhongnanhai.id' (f488e14c5e4eb30d14a0614c492ec67f84bdbfc31ef3837ad7e5c34c28362ca5) is confirmed!  New hash is 8a5f9c1f7e164d6330fe281fddc4cefb4bed72ed
[2017-07-12 22:08:07,635] [DEBUG] [config:881] (81541.123145521098752) Override blockstack-client.port from 6264 to 6264
[2017-07-12 22:08:07,641] [DEBUG] [storage:947] (81533.123145521098752) put_immutable_data(8a5f9c1f7e164d6330fe281fddc4cefb4bed72ed), required=disk,dropbox, skip=
[2017-07-12 22:08:07,641] [DEBUG] [storage:965] (81533.123145521098752) Try "disk"
[2017-07-12 22:08:07,643] [DEBUG] [disk:220] (81533) Stored to '/Users/larry/.blockstack/storage-disk/immutable/8a5f9c1f7e164d6330fe281fddc4cefb4bed72ed'
[2017-07-12 22:08:07,643] [DEBUG] [storage:985] (81533.123145521098752) Replication succeeded with "disk"
[2017-07-12 22:08:07,643] [DEBUG] [storage:965] (81533.123145521098752) Try "dropbox"
[2017-07-12 22:08:07,643] [DEBUG] [common:895] (81533) Store 115 bytes to /immutable-8a5f9c1f7e164d6330fe281fddc4cefb4bed72ed
[2017-07-12 22:08:09,473] [DEBUG] [dropbox:97] (81541) /immutable-8a5f9c1f7e164d6330fe281fddc4cefb4bed72ed available at https://www.dropbox.com/s/0hret5nlamyqzqo/immutable-8a5f9c1f7e164d6330fe281fddc4cefb4bed72ed?dl=1
[2017-07-12 22:08:09,476] [DEBUG] [common:905] (81533) Insert (/immutable-8a5f9c1f7e164d6330fe281fddc4cefb4bed72ed, https://www.dropbox.com/s/0hret5nlamyqzqo/immutable-8a5f9c1f7e164d6330fe281fddc4cefb4bed72ed?dl=1) into index
[2017-07-12 22:08:09,478] [DEBUG] [common:245] (81533) Index page for /immutable-8a5f9c1f7e164d6330fe281fddc4cefb4bed72ed is /index/c
[2017-07-12 22:08:09,478] [DEBUG] [common:658] (81533) Fetch index page /index/c via driver
[2017-07-12 22:08:10,703] [DEBUG] [common:668] (81533) Fetched 28 bytes
[2017-07-12 22:08:10,704] [DEBUG] [common:579] (81533) Cache 1 bytes for c
[2017-07-12 22:08:10,704] [DEBUG] [common:690] (81533) Set index page /index/c
[2017-07-12 22:08:13,158] [DEBUG] [dropbox:97] (81541) /index/c available at https://www.dropbox.com/s/t4lyf060s3msdu6/c?dl=1
[2017-07-12 22:08:13,162] [DEBUG] [storage:985] (81533.123145521098752) Replication succeeded with "dropbox"
[2017-07-12 22:08:13,162] [DEBUG] [storage:965] (81533.123145521098752) Try "s3"
[2017-07-12 22:08:13,162] [DEBUG] [s3:118] (81533) No AWS key set, cannot write
[2017-07-12 22:08:13,162] [DEBUG] [storage:977] (81533.123145521098752) Failed to replicate with "s3"
[2017-07-12 22:08:13,162] [DEBUG] [storage:965] (81533.123145521098752) Try "blockstack_resolver"
[2017-07-12 22:08:13,162] [DEBUG] [storage:977] (81533.123145521098752) Failed to replicate with "blockstack_resolver"
[2017-07-12 22:08:13,162] [DEBUG] [storage:965] (81533.123145521098752) Try "blockstack_server"
[2017-07-12 22:08:13,189] [ERROR] [blockstack_server:175] (81533) Driver does not support putting a zonefile
[2017-07-12 22:08:13,189] [DEBUG] [storage:977] (81533.123145521098752) Failed to replicate with "blockstack_server"
[2017-07-12 22:08:13,189] [DEBUG] [storage:965] (81533.123145521098752) Try "http"
[2017-07-12 22:08:13,190] [DEBUG] [storage:977] (81533.123145521098752) Failed to replicate with "http"
[2017-07-12 22:08:13,190] [DEBUG] [storage:965] (81533.123145521098752) Try "dht"
[2017-07-12 22:08:13,772] [DEBUG] [storage:985] (81533.123145521098752) Replication succeeded with "dht"
[2017-07-12 22:08:13,773] [DEBUG] [zonefile:416] (81541.123145521098752) Replicate zonefile to 157.56.11.112:6264
[2017-07-12 22:08:14,695] [DEBUG] [zonefile:430] (81541.123145521098752) Replicated zonefile to 157.56.11.112:6264
[2017-07-12 22:08:14,699] [DEBUG] [zonefile:416] (81541.123145521098752) Replicate zonefile to 188.165.204.220:6264
[2017-07-12 22:08:15,617] [DEBUG] [zonefile:430] (81541.123145521098752) Replicated zonefile to 188.165.204.220:6264
[2017-07-12 22:08:15,625] [DEBUG] [zonefile:416] (81541.123145521098752) Replicate zonefile to 13.93.206.109:6264
[2017-07-12 22:08:16,156] [ERROR] [proxy:2111] (81541.123145521098752) 0 is less than the minimum of 1

Failed validating 'minimum' in schema['properties']['saved']['items']:
    {'maximum': 1, 'minimum': 1, 'type': 'integer'}

On instance['saved'][0]:
    0
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/proxy.py", line 2105, in put_zonefiles
    push_info = json_validate(schema, push_info)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/proxy.py", line 258, in json_validate
    jsonschema.validate(resp, schema)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: 0 is less than the minimum of 1

Failed validating 'minimum' in schema['properties']['saved']['items']:
    {'maximum': 1, 'minimum': 1, 'type': 'integer'}

On instance['saved'][0]:
    0
[2017-07-12 22:08:16,161] [DEBUG] [zonefile:421] (81541.123145521098752) server returned {'traceback': ['Traceback (most recent call last):', '  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/proxy.py", line 2105, in put_zonefiles', '    push_info = json_validate(schema, push_info)', '  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/proxy.py", line 258, in json_validate', '    jsonschema.validate(resp, schema)', '  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate', '    cls(schema, *args, **kwargs).validate(instance)', '  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate', '    raise error', 'ValidationError: 0 is less than the minimum of 1', '', "Failed validating 'minimum' in schema['properties']['saved']['items']:", "    {'maximum': 1, 'minimum': 1, 'type': 'integer'}", '', "On instance['saved'][0]:", '    0'], 'error': '    0'}
[2017-07-12 22:08:16,176] [ERROR] [zonefile:427] (81541.123145521098752) Failed to publish zonefile to 13.93.206.109:6264:     0
[2017-07-12 22:08:16,180] [DEBUG] [zonefile:416] (81541.123145521098752) Replicate zonefile to 168.62.238.158:6264
[2017-07-12 22:08:16,823] [DEBUG] [zonefile:430] (81541.123145521098752) Replicated zonefile to 168.62.238.158:6264
[2017-07-12 22:08:16,832] [DEBUG] [zonefile:416] (81541.123145521098752) Replicate zonefile to 23.96.218.65:6264
[2017-07-12 22:08:17,768] [DEBUG] [zonefile:430] (81541.123145521098752) Replicated zonefile to 23.96.218.65:6264
[2017-07-12 22:08:17,774] [DEBUG] [zonefile:416] (81541.123145521098752) Replicate zonefile to 40.121.156.215:6264
[2017-07-12 22:08:18,450] [DEBUG] [zonefile:430] (81541.123145521098752) Replicated zonefile to 40.121.156.215:6264
[2017-07-12 22:08:18,474] [DEBUG] [zonefile:416] (81541.123145521098752) Replicate zonefile to 40.76.194.199:6264
[2017-07-12 22:08:19,116] [DEBUG] [zonefile:430] (81541.123145521098752) Replicated zonefile to 40.76.194.199:6264
[2017-07-12 22:08:19,124] [DEBUG] [zonefile:416] (81541.123145521098752) Replicate zonefile to localhost:6264
[2017-07-12 22:08:19,129] [ERROR] [proxy:2117] (81541.123145521098752) [Errno 61] Connection refused
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/proxy.py", line 2104, in put_zonefiles
    push_info = proxy.put_zonefiles(zonefile_data_list)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/proxy.py", line 136, in inner
    res = func(*args, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1308, in single_request
    self.send_content(h, request_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1456, in send_content
    connection.endheaders(request_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/proxy.py", line 69, in connect
    httplib.HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 61] Connection refused
[2017-07-12 22:08:19,135] [ERROR] [proxy:2119] (81541.123145521098752) Caught exception while connecting to Blockstack node: [Errno 61] Connection refused
[2017-07-12 22:08:19,139] [DEBUG] [zonefile:421] (81541.123145521098752) server returned {'error': 'Failed to contact Blockstack node.  Try again with `--debug`.'}
[2017-07-12 22:08:19,143] [ERROR] [zonefile:427] (81541.123145521098752) Failed to publish zonefile to localhost:6264: Failed to contact Blockstack node.  Try again with `--debug`.
[2017-07-12 22:08:19,147] [DEBUG] [zonefile:416] (81541.123145521098752) Replicate zonefile to node.blockstack.org:6264
[2017-07-12 22:08:19,729] [ERROR] [proxy:2111] (81541.123145521098752) 0 is less than the minimum of 1

Failed validating 'minimum' in schema['properties']['saved']['items']:
    {'maximum': 1, 'minimum': 1, 'type': 'integer'}

On instance['saved'][0]:
    0
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/proxy.py", line 2105, in put_zonefiles
    push_info = json_validate(schema, push_info)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/proxy.py", line 258, in json_validate
    jsonschema.validate(resp, schema)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: 0 is less than the minimum of 1

Failed validating 'minimum' in schema['properties']['saved']['items']:
    {'maximum': 1, 'minimum': 1, 'type': 'integer'}

On instance['saved'][0]:
    0
[2017-07-12 22:08:19,730] [DEBUG] [zonefile:421] (81541.123145521098752) server returned {'traceback': ['Traceback (most recent call last):', '  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/proxy.py", line 2105, in put_zonefiles', '    push_info = json_validate(schema, push_info)', '  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/proxy.py", line 258, in json_validate', '    jsonschema.validate(resp, schema)', '  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate', '    cls(schema, *args, **kwargs).validate(instance)', '  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate', '    raise error', 'ValidationError: 0 is less than the minimum of 1', '', "Failed validating 'minimum' in schema['properties']['saved']['items']:", "    {'maximum': 1, 'minimum': 1, 'type': 'integer'}", '', "On instance['saved'][0]:", '    0'], 'error': '    0'}
[2017-07-12 22:08:19,735] [ERROR] [zonefile:427] (81541.123145521098752) Failed to publish zonefile to node.blockstack.org:6264:     0
[2017-07-12 22:08:19,739] [DEBUG] [zonefile:416] (81541.123145521098752) Replicate zonefile to 13.77.96.229:6264
[2017-07-12 22:08:20,569] [DEBUG] [zonefile:430] (81541.123145521098752) Replicated zonefile to 13.77.96.229:6264
[2017-07-12 22:08:20,574] [DEBUG] [zonefile:416] (81541.123145521098752) Replicate zonefile to 40.121.158.86:6264
[2017-07-12 22:08:21,187] [DEBUG] [zonefile:430] (81541.123145521098752) Replicated zonefile to 40.121.158.86:6264
[2017-07-12 22:08:21,191] [INFO] [registrar:457] (81541.123145521098752) Replicated zonefile data for zhongnanhai.id to 8 server(s)
[2017-07-12 22:08:21,195] [INFO] [registrar:504] (81541.123145521098752) No profile to replicate for 'zhongnanhai.id'
[2017-07-12 22:08:21,200] [DEBUG] [config:881] (81541.123145521098752) Override blockstack-client.port from 6264 to 6264
```

**Comment by jackzampolin** [comment]
Closing this as stale. Please reopen if this is still an issue.
