### ISSUE TITLE
Bitcoin withdraw error on 0.14.3.0

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#503]
I'm trying to withdraw bitcoin from the core wallet as part of testing the fix for: https://github.com/blockstack/blockstack-browser/issues/612

Browser is POSTing the following JSON to http://localhost:6270/v1/wallet/balance

```JSON
{"address":"1CoWHE4gQP2RygR6QapoXE751iqyDC8upM","min_confs":0,"amount":587000}
```

It looks like an error in working with unspent transaction inputs: 
`TypeError: 'NoneType' object is not iterable`

api_endpoint.log:
```
[2017-07-22 14:57:06,470] [DEBUG] [rpc:3564] (12358.123145446838272) 
full path: /v1/wallet/balance
method: POST
path: /v1/wallet/balance
qs: {}
headers:
origin: http://localhost:3000
content-length: 78
accept-language: en-US,en;q=0.8
accept-encoding: gzip, deflate, br
connection: keep-alive
accept: application/json
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
host: localhost:6270
referer: http://localhost:3000/wallet/send
content-type: application/json
authorization: bearer redacted

[2017-07-22 14:57:06,479] [DEBUG] [app:113] (12358.123145446838272) Not a valid token
[2017-07-22 14:57:06,486] [DEBUG] [rpc:3608] (12358.123145446838272) Authenticated with password
[2017-07-22 14:57:06,504] [WARNING] [blockchain:182] (12358.123145446838272) Using a different number of confirmations (0) instead of default (6)
[2017-07-22 14:57:06,525] [DEBUG] [config:881] (12358.123145446838272) Override blockstack-client.port from 6264 to 6264
[2017-07-22 14:57:06,541] [WARNING] [scripts:377] (12358.123145446838272) Using UTXOs with 0 confirmations instead of the default 6
[2017-07-22 14:57:06,552] [DEBUG] [insight_api:41] (12350.123145446838272) GET https://utxo.blockstack.org/insight-api/addr/3Ht2PzmsT4gy4EpBTp7FKco239ZiHvXdUP/utxo
[2017-07-22 14:57:07,674] [DEBUG] [insight_api:52] (12350.123145446838272) 3Ht2PzmsT4gy4EpBTp7FKco239ZiHvXdUP has 2 UTXOs
[2017-07-22 14:57:07,674] [ERROR] [rpc:3643] (12358.123145446838272) 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 3640, in _dispatch
    return route_method( session, path_info, *route_args )
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 2069, in POST_wallet_balance
    res = internal.cli_withdraw(address, amount, message, min_confs, tx_only, config_path=self.server.config_path, interactive=False, wallet_keys=self.server.wallet_keys)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 165, in argwrapper
    result = run_cli_api(method_info, list(args), config_path=cf, check_rpc=check_rpc, **kw)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 149, in run_cli_api
    res = command_info['method'](args, config_path=config_path, **kw)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py", line 521, in cli_withdraw
    tx = mktx(amount, 0)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py", line 497, in mktx
    change = virtualchain.calculate_change_amount(selected_inputs, amt, tx_fee)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/virtualchain/lib/blockchain/bitcoin_blockchain/keys.py", line 309, in calculate_change_amount
    total_amount_in = sum([input['value'] for input in inputs])
TypeError: 'NoneType' object is not iterable
127.0.0.1 - - [22/Jul/2017 14:57:07] "POST /v1/wallet/balance HTTP/1.1" 500 -
```

**Comment by larrysalibra** [comment]
@kantai If i remove the `min_conf` parameter I get same error. Removing the `amount` parameter as well "fixes" the error as core tries to send my entire balance to the given address.

**Comment by jcnelson** [comment]
@larrysalibra I see the bug.  The amount you're putting in is too high, but the `select_utxos()` method returns `None` for its list of inputs if that happens.  This in turn triggers the bug you're seeing.  Does the method work if you use a lesser amount?

**Comment by jcnelson** [comment]
Pushed a possible fix to `hotfix-0.14.3-issue-503`

**Comment by larrysalibra** [comment]
> Does the method work if you use a lesser amount?

Yes, it does.

**Comment by larrysalibra** [comment]
https://github.com/blockstack/blockstack-core/commit/50a64766e6a4212ba25f74a210a35c0bf0b2bf93

This fixes the earlier problem for me - however it still gives me a `500` error which isn't the right error type for this situation. For now, I'm going to ship a patch version with this commit of core since it is an improvement over what is out there now.

**Comment by jackzampolin** [comment]
Closing this as fixed per @larrysalibra
