### ISSUE TITLE
`blockstack register` fails with `AttributeError: 'NoneType' object has no attribute 'lower'`

### ISSUE THREAD

**Issue by Jabbslad** [blockstack/blockstack-core#508]
Hey,

Clean install of 0.14.3.0 in virtualenv and getting `AttributeError: 'NoneType' object has no attribute 'lower'` when trying to register. Any ideas?

* OS:	                Mac OS X 10.12.5 (16F73)
* python:                 2.7.13
* pip:                       9.0.1
* virtualenv:            15.1.0
* blockstack:          0.14.3.0

1. `pip install blockstack`
2. `blockstack info`
```
{
    "cli_version": "0.14.3.0",
    "consensus_hash": "251e20ed8b3a8b74362265f05f621c54",
    "last_block_processed": 478024,
    "last_block_seen": 478032,
    "queues": {},
    "server_alive": true,
    "server_host": "node.blockstack.org",
    "server_port": 6264,
    "server_version": "0.14.1.5"
}
```
3. `blockstack setup`
```
Would you like to receive an email when there is a new release of this software available?
Email address (leave blank to opt out):
---------------------------------------------------------
Your client does not have enough information to connect
to a Blockstack server.  Please supply the following
parameters, or press [ENTER] to select the default value.
---------------------------------------------------------
api_endpoint_host (default: "localhost"):
blockchain_writer (default: "blockstack_utxo"):
queue_path (default: "/Users/jabbslad/.blockstack/queues.db"):
api_password (default: "<<<REDACTED>>>"):
poll_interval (default: "300"):
server (default: "node.blockstack.org"):
anonymous_statistics (default: "True"):
storage_drivers_required_write (default: "disk,dropbox"):
api_endpoint_port (default: "6270"):
storage_drivers (default: "disk,dropbox,s3,blockstack_resolver,blockstack_server,http,dht"):
blockchain_reader (default: "blockstack_utxo"):
client_version (default: "0.14.3.0"):
api_endpoint_bind (default: "localhost"):
port (default: "6264"):
metadata (default: "metadata"):
--------------------------------------------------------
Blockstack does not have enough information to connect
to bitcoind.  Please supply the following parameters, or
press [ENTER] to select the default value.
--------------------------------------------------------
passwd (default: "blockstacksystem"):
regtest (default: "False"):
spv_path (default: "/Users/jabbslad/.virtualchain-spv-headers.dat"):
server (default: "bitcoin.blockstack.com"):
p2p_port (default: "8333"):
user (default: "blockstack"):
timeout (default: "300"):
port (default: "8332"):
-------------------------------
Blockchain reader configuration
----------------------------------------------
Please enter your Blockstack UTXO service info
----------------------------------------------
url (default: "https://utxo.blockstack.org"):
-------------------------------
Blockchain writer configuration
----------------------------------------------
Please enter your Blockstack UTXO service info
----------------------------------------------
url (default: "https://utxo.blockstack.org"):
--------------------------------------------
Would you like to receive notifications
from the developers when there are critical
updates available to install?

If so, please enter your email address here.
If not, leave this field blank.

Your email address will be used solely
for this purpose.

--------------------------------------------
email (default: ""):
Saving configuration to /Users/jabbslad/.blockstack/client.ini
Initializing new wallet ...
Enter new password:
Confirm new password:
Wallet created. Make sure to backup the following:
<<<REDACTED>>>
{
    "status": true
}
```
4. `blockstack api start`
```
Enter wallet password:
{
    "status": true
}
```
5. `blockstack register jabbslad.id --debug`
```
Set BLOCKSTACK_DEBUG to 1
Re-exec as `"/tmp/blockstack/bin/python2.7", "/tmp/blockstack/bin/blockstack", "register", "jabbslad.id"`
[2017-07-29 01:19:28,175] [DEBUG] [spv:103] (53016.140736886850496) Using mainnet
[2017-07-29 01:19:28,332] [DEBUG] [config:881] (53016.140736886850496) Override blockstack-client.port from 6264 to 6264
[2017-07-29 01:19:28,335] [DEBUG] [client:94] (53016.140736886850496) Connect to node.blockstack.org:6264
[2017-07-29 01:19:28,557] [WARNING] [dropbox:184] (53016) Config file '/Users/jabbslad/.blockstack/client.ini': section 'dropbox' is missing 'token'.  Write access will be disabled
[2017-07-29 01:19:28,558] [DEBUG] [client:109] (53016.140736886850496) Loaded storage drivers ['disk', 'dropbox', 's3', 'blockstack_resolver', 'blockstack_server', 'http', 'dht']
[2017-07-29 01:19:28,558] [DEBUG] [rpc:5109] (53016.140736886850496) RPC running (/Users/jabbslad/.blockstack/api_endpoint.pid)
[2017-07-29 01:19:28,559] [DEBUG] [config:881] (53016.140736886850496) Override blockstack-client.port from 6264 to 6264
[2017-07-29 01:19:28,561] [ERROR] [blockstack:66] (53016.140736886850496) 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/tmp/blockstack/bin/blockstack", line 52, in <module>
    result = run_cli()
  File "/tmp/blockstack/lib/python2.7/site-packages/blockstack_client/cli.py", line 567, in run_cli
    result = method(args, config_path=config_path)
  File "/tmp/blockstack/lib/python2.7/site-packages/blockstack_client/actions.py", line 1280, in cli_register
    if unsafe_reg.lower() in ('true', 't', 'yes', '1'):
AttributeError: 'NoneType' object has no attribute 'lower'
{
    "error": "Unexpected error:\nTraceback (most recent call last):\n  File \"/tmp/blockstack/bin/blockstack\", line 52, in <module>\n    result = run_cli()\n  File \"/tmp/blockstack/lib/python2.7/site-packages/blockstack_client/cli.py\", line 567, in run_cli\n    result = method(args, config_path=config_path)\n  File \"/tmp/blockstack/lib/python2.7/site-packages/blockstack_client/actions.py\", line 1280, in cli_register\n    if unsafe_reg.lower() in ('true', 't', 'yes', '1'):\nAttributeError: 'NoneType' object has no attribute 'lower'\n",
    "help": "Try getting latest version of CLI with \"sudo pip install blockstack --upgrade\""
}
```

* `sed -n '1278,1280p' /tmp/blockstack/lib/python2.7/site-packages/blockstack_client/actions.py`
```
    unsafe_reg = getattr(args, 'unsafe_reg', 'False')

    if unsafe_reg.lower() in ('true', 't', 'yes', '1'):
```

**Comment by Jabbslad** [comment]
On further investigation it appears this issue is caused due to the way the `args` are built up for the `cli_register` function in `blockstack_client/actions.py`

```
def cli_register(args, config_path=CONFIG_PATH, force_data=False,
                 cost_satoshis=None, interactive=True, password=None, proxy=None,
                 make_profile = None):
    """
    command: register
    help: Register a blockchain ID
    arg: name (str) 'The blockchain ID to register'
    opt: zonefile (str) 'The path to the zone file for this name'
    opt: recipient (str) 'The recipient address, if not this wallet'
    opt: min_confs (int) 'The minimum number of confirmations on the initial preorder'
    opt: unsafe_reg (str) 'Should we aggressively register the name (ie, use low min confs)'
    """
```
`args` is made up of the following values:-
```
Namespace(action='register', min_confs=None, name='jabbslad.id', recipient=None, unsafe_reg=None, zonefile=None)
```
From a cursory glance it looks like the value of `args` is automatically set by parsing the string literal doc underneath the method declaration and pulling out all the args. 

I think this will mean the following variables will never get set correctly using `getattr` because the attributes will always exist with a value of `None`:-

```
L1277: min_payment_confs = getattr(args, 'min_confs', TX_MIN_CONFIRMATIONS)
L1278: unsafe_reg = getattr(args, 'unsafe_reg', 'False')
```

**Comment by dantrevino** [comment]
same issue here

**Comment by shea256** [comment]
Hey @Jabbslad @dantrevino sorry you've been having problems here and thanks for reporting.

cc'ing @jackzampolin @jcnelson and @kantai on this one.

**Comment by jcnelson** [comment]
Thanks for reporting!  Just pushed a fix to `master`

**Comment by shea256** [comment]
Woot!

**Comment by jcnelson** [comment]
Fix is now in APT and pip.

**Comment by Jabbslad** [comment]
@jcnelson awesome, thanks. I confirm that I can no longer reproduce the issue with `blockstack-0.14.3.1` (pip)
