### ISSUE TITLE
ImportError: No module named _scrypt

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack-core#517]
I installed a fresh version of Blockstack via `pip` (currently `0.14.3.1`) in a clean virtualenv (on Archlinux). It doesn't find `scrypt` although it's installed.

```
Traceback (most recent call last):
  File "./blockstack_gpg/main.py", line 4, in <module>
    from blockstack.profile import profile_list_accounts
  File "/home/me/blockstack-gpg/venv-gpg-dev/lib/python2.7/site-packages/blockstack-0.14.3.1-py2.7.egg/blockstack/__init__.py", line 24, in <module>
    from .lib import *
  File "/home/me/blockstack-gpg/venv-gpg-dev/lib/python2.7/site-packages/blockstack-0.14.3.1-py2.7.egg/blockstack/lib/__init__.py", line 24, in <module>
    from .atlas import *
  File "/home/me/blockstack-gpg/venv-gpg-dev/lib/python2.7/site-packages/blockstack-0.14.3.1-py2.7.egg/blockstack/lib/atlas.py", line 39, in <module>
    from blockstack_client.config import semver_newer
  File "/home/me/blockstack-gpg/venv-gpg-dev/lib/python2.7/site-packages/blockstack-0.14.3.1-py2.7.egg/blockstack_client/__init__.py", line 32, in <module>
    import rpc
  File "/home/me/blockstack-gpg/venv-gpg-dev/lib/python2.7/site-packages/blockstack-0.14.3.1-py2.7.egg/blockstack_client/rpc.py", line 71, in <module>
    from .wallet import make_wallet
  File "/home/me/blockstack-gpg/venv-gpg-dev/lib/python2.7/site-packages/blockstack-0.14.3.1-py2.7.egg/blockstack_client/wallet.py", line 50, in <module>
    from .backend.crypto.utils import aes_decrypt, aes_encrypt
  File "/home/me/blockstack-gpg/venv-gpg-dev/lib/python2.7/site-packages/blockstack-0.14.3.1-py2.7.egg/blockstack_client/backend/crypto/__init__.py", line 22, in <module>
    from utils import aes_encrypt, aes_decrypt
  File "/home/me/blockstack-gpg/venv-gpg-dev/lib/python2.7/site-packages/blockstack-0.14.3.1-py2.7.egg/blockstack_client/backend/crypto/utils.py", line 26, in <module>
    import scrypt
  File "build/bdist.linux-x86_64/egg/scrypt.py", line 11, in <module>
ImportError: No module named _scrypt
```

**Comment by kantai** [comment]
The python `scrypt` library is strangely packaged. In a lot of fresh installs, it fails to correctly install it's C library portions. For me, running `pip install scrypt` outside of the virtualenv usually solves the problem.

**Comment by vsund** [comment]
`scrypt" was already installed outside the virtualenv. But I remembered that I already had this issue and your solution :D

Removing and reinstalling `scrypt` fixed the issue. (And now it's documented here for the next time I run into this.)

**Comment by kantai** [comment]
Looking into this a little more closely, I found this issue from elsewhere:

https://github.com/mozilla/fxa-scrypt-helper/issues/28#issuecomment-24634110

We already have a fork of the python scrypt library that we use for packaging on macOS, so I might be able to fix this issue by switch it's installer to use setuptools.

**Comment by jcnelson** [comment]
One possible work-around is to install `scrypt` in your system, and copy the `_scrypt.so` library into your virtualenv.  It's a kludge, but it will work.

**Comment by kitefishlabs** [comment]
FYI, uninstall-reinstall of scrypt from within the virtualenv was necessary to get tests running on Ubuntu 16.04.

**Comment by ashburry-chat-irc** [comment]
I am getting this error on Python 3.10 after uninstall/reinstall still getting the error
```
> (base) ashburry@ashburry-ThinkCentre-M92P:~/Documents/trio_ircproxy$ python3.10 trio_ircproxy.py 
> Traceback (most recent call last):
>   File "/home/ashburry/Documents/trio_ircproxy/trio_ircproxy.py", line 42, in <module>
>     from scrypt import hash as chash
>   File "/usr/lib/python3/dist-packages/scrypt.py", line 11, in <module>
>     _scrypt = cdll.LoadLibrary(imp.find_module('_scrypt')[1])
>   File "/usr/lib/python3.10/imp.py", line 297, in find_module
>     raise ImportError(_ERR_MSG.format(name), name=name)
> ImportError: No module named '_scrypt'
> 
```
