### ISSUE TITLE
Windows 10 Linux Installation Setup Error

### ISSUE THREAD

**Issue by imine4coin** [blockstack/blockstack-core#607]
My Windows 10 installation was successful but calls to "blockstack", " blockstack cli version", "blockstack setup", "info", "blockstack balance" etc returns the below error
Robert@DESKTOP-8AD8G6M:~$ blockstack setup
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/__init__.py", line 23, in <module>
    import app
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/app.py", line 34, in <module>
    import jsontokens
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/__init__.py", line 10, in <module>
    from token_signer import TokenSigner
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/token_signer.py", line 24, in <module>
    from .key_loading import load_signing_key
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/key_loading.py", line 42, in <module>
    def load_signing_key(signing_key, crypto_backend=default_backend()):
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 53, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_openssl.so: cannot enable executable stack as shared object requires: Invalid argument

**Comment by kantai** [comment]
Hi --

glad to see you testing this out on Windows.

How did you install blockstack? Are you using Windows Subsystem For Linux? Did you use pip?

**Comment by imine4coin** [comment]
Yes I am using Windows Subsystem For Linux on Windows 10(with Ubuntu 16.04) and I used pip2 as per the video  and install instructions.  it appears that there maybe two installs( the one above under usr/local/bin/blockstack and the one below under tmp/blockstack/bin.  At any rate, the error messages show.

Robert@DESKTOP-8AD8G6M:~$ cd /tmp/blockstack/bin
Robert@DESKTOP-8AD8G6M:/tmp/blockstack/bin$ ls
activate                        bundle_image      glacier          pip                    pyrsa-verify
activate.csh                    cfadmin           instance_events  pip2                   python
activate.fish                   chardetect        jsondiff         pip2.7                 python2
activate_this.py                cq                jsonpatch        pyami_sendmail         python2.7
asadmin                         cwutil            jsonpointer      pyrsa-decrypt          python-config
base58                          dynamodb_dump     jsonschema       pyrsa-decrypt-bigfile  route53
blockstack                      dynamodb_load     kill_instance    pyrsa-encrypt          s3put
blockstack-core                 easy_install      launch_instance  pyrsa-encrypt-bigfile  sdbadmin
blockstack-server               easy_install-2.7  list_instances   pyrsa-keygen           taskadmin
blockstack-snapshots            elbadmin          lss3             pyrsa-priv2pub         wheel
blockstack-subdomain-registrar  fetch_file        mturk            pyrsa-sign
Robert@DESKTOP-8AD8G6M:/tmp/blockstack/bin$ ^V

**Comment by kantai** [comment]
That's strange-- I'm not sure why it would have installed to /tmp/

Can you try installing via these instructions (they are for Ubuntu, but they should be compatible for you)

```
# Install dependancies
$ sudo apt-get update && sudo apt-get install -y python-pip python-dev libssl-dev libffi-dev rng-tools libgmp3-dev
$ sudo pip2 install pyparsing

# Install blockstack
$ sudo pip2 install blockstack --upgrade
```

Also, which video are you referring to? If there's a bug in the setup instructions in that video, we'll try to fix it.

**Comment by imine4coin** [comment]
Ok Docker install worked!  Now I can open the Blockstack Browser in Microsoft Edge.  I have exported my onename.id to the userid of the browser but the wallet in the browser shows 0.00 even though there is money in the associated imine4coin.id wallet.  What must I do now to access the applications other than forum and Openbazaar?

**Comment by imine4coin** [comment]
Robert@DESKTOP-8AD8G6M:~$ which blockstack
/usr/local/bin/blockstack
Robert@DESKTOP-8AD8G6M:~$ blockstack lookup imine4coin.id
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/__init__.py", line 23, in <module>
    import app
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/app.py", line 34, in <module>
    import jsontokens
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/__init__.py", line 10, in <module>
    from token_signer import TokenSigner
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/token_signer.py", line 24, in <module>
    from .key_loading import load_signing_key
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/key_loading.py", line 42, in <module>
    def load_signing_key(signing_key, crypto_backend=default_backend()):
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 53, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_openssl.so: cannot enable executable stack as shared object requires: Invalid argument
Robert@DESKTOP-8AD8G6M:~$ blockstack price imine4coin.id
Traceback (most recent call last):
  File "/usr/local/bin/blockstack", line 42, in <module>
    from blockstack_client.cli import run_cli, exit_with_error
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/__init__.py", line 23, in <module>
    import app
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/app.py", line 34, in <module>
    import jsontokens
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/__init__.py", line 10, in <module>
    from token_signer import TokenSigner
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/token_signer.py", line 24, in <module>
    from .key_loading import load_signing_key
  File "/usr/local/lib/python2.7/dist-packages/jsontokens/key_loading.py", line 42, in <module>
    def load_signing_key(signing_key, crypto_backend=default_backend()):
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 53, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_openssl.so: cannot enable executable stack as shared object requires: Invalid argument

Same error even though blockstack is installed on my windows system I cannot see the wallet or price of the id, imine4coin.id on Ubuntu for windows.  Any suggestions?

**Comment by kantai** [comment]
The error you are seeing there is the same as the original, because I think that's still the install in linux4windows. To access the blockstack CLI from the docker installer, you have to execute it from within the docker container. If you open the "docker shell" link that the installer provides, that will allow you to get to the docker container by entering these commands:

```
CC=$(docker ps -f name=$corecontainer -q)
docker exec -it $CC /bin/bash
```

And then you'll be able to run blockstack CLI commands.

**Comment by jackzampolin** [comment]
@imine4coin If this is still an issue please re-open. I'm closing this as we have shipped an install for windows that doesn't include the docker pieces and is much easier to use.
