### ISSUE TITLE
Inconsistent wallet transfer behavior

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#636]
My wallet has a balance of 349199 bitcoins:

If I try to send 349200 bitcoins, it responds with `400` bad request saying that the amount I'm trying to send is more than the balance. (correct behavior)

If I try to send 349199 bitcoins, it responds with `500` internal server error (because there's not enough to send that amount + a fee). 

It should always respond with 400 if there's not enough money to send the amount+fee the user has entered.

Logs for both of the above situations are below:

```
full path: /v1/wallet/balance
method: POST
path: /v1/wallet/balance
qs: {}
headers:
origin: http://localhost:8888
content-length: 161
accept-language: en-US,en;q=0.8
accept-encoding: gzip, deflate, br
connection: keep-alive
accept: application/json
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
host: localhost:6270
referer: http://localhost:8888/wallet/send
content-type: application/json
authorization: bearer REDACTED

[2017-10-07 22:31:43,794] [DEBUG] [app:152] (31808.123145531961344) Not a valid token
[2017-10-07 22:31:43,904] [DEBUG] [rpc:3964] (31808.123145531961344) Authenticated with password
[2017-10-07 22:31:44,169] [WARNING] [blockchain:134] (31808.123145531961344) Using a different number of confirmations (0) instead of default (6)
[2017-10-07 22:31:44,286] [WARNING] [scripts:383] (31808.123145531961344) Using UTXOs with 0 confirmations instead of the default 6
[2017-10-07 22:31:44,399] [DEBUG] [insight_api:41] (31797.123145531961344) GET https://utxo.blockstack.org/insight-api/addr/1ocXpu8pTzHEq4KQkgYNe7W6fwzAvyYT8/utxo
[2017-10-07 22:31:45,645] [DEBUG] [insight_api:52] (31797.123145531961344) 1ocXpu8pTzHEq4KQkgYNe7W6fwzAvyYT8 has 2 UTXOs
[2017-10-07 22:31:45,646] [DEBUG] [actions:561] (31808.123145531961344) Withdraw 349199, tx fee 0
[2017-10-07 22:31:47,825] [DEBUG] [session:189] (31797.123145531961344) Connect to bitcoind at bitcoin.blockstack.com:8332 (/Users/larry/Library/Application Support/Blockstack/config/client.ini)
[2017-10-07 22:31:47,826] [DEBUG] [session:104] (31797.123145531961344) [31808] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
[2017-10-07 22:31:48,437] [DEBUG] [fees:87] (31797.123145531961344) Bitcoin estimatefee(2) is 0.00149672
[2017-10-07 22:31:48,438] [DEBUG] [fees:93] (31797.123145531961344) Bitcoin estimatefee(2) is 0.00149672 (146 satoshi/byte)
[2017-10-07 22:31:48,438] [ERROR] [rpc:3999] (31808.123145531961344) Not enough inputs for transaction (total: 349199, to spend: 349199, fee: 49494).
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 3996, in _dispatch
    return route_method( session, path_info, *route_args )
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 2303, in POST_wallet_balance
    wallet_keys=self.server.wallet_keys)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 189, in argwrapper
    result = run_cli_api(method_info, list(args), config_path=cf, check_rpc=check_rpc, **kw)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 173, in run_cli_api
    res = command_info['method'](args, config_path=config_path, **kw)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py", line 590, in cli_withdraw
    tx = mktx(amount, tx_fee)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/actions.py", line 560, in mktx
    change = virtualchain.calculate_change_amount(selected_inputs, amt, tx_fee)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/virtualchain/lib/blockchain/bitcoin_blockchain/keys.py", line 355, in calculate_change_amount
    raise ValueError('Not enough inputs for transaction (total: {}, to spend: {}, fee: {}).'.format(total_amount_in, send_amount, fee))
ValueError: Not enough inputs for transaction (total: 349199, to spend: 349199, fee: 49494).
127.0.0.1 - - [07/Oct/2017 22:31:48] "POST /v1/wallet/balance HTTP/1.1" 500 -
[2017-10-07 22:33:56,233] [DEBUG] [proxy:222] (31808.123145527754752) Default proxy to https://node.blockstack.org:6263
[2017-10-07 22:33:56,345] [DEBUG] [client:95] (31808.123145527754752) Connect to https://node.blockstack.org:6263
[2017-10-07 22:33:56,456] [WARNING] [dropbox:188] (31808) Config file '/Users/larry/Library/Application Support/Blockstack/config/client.ini': section 'dropbox' is missing 'token'.  Write access will be disabled
[2017-10-07 22:33:56,459] [DEBUG] [client:110] (31808.123145527754752) Loaded storage drivers ['disk', 'dropbox', 's3', 'blockstack_resolver', 'blockstack_server', 'http', 'dht']
[2017-10-07 22:33:56,581] [DEBUG] [registrar:1043] (31808.123145527754752) Registrar sleeping for 300
```

```
[2017-10-07 22:36:16,382] [DEBUG] [rpc:3917] (31808.123145531961344) 
full path: /v1/wallet/balance
method: POST
path: /v1/wallet/balance
qs: {}
headers:
origin: http://localhost:8888
content-length: 161
accept-language: en-US,en;q=0.8
accept-encoding: gzip, deflate, br
connection: keep-alive
accept: application/json
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
host: localhost:6270
referer: http://localhost:8888/wallet/send
content-type: application/json
authorization: bearer REDACTED

[2017-10-07 22:36:16,493] [DEBUG] [app:152] (31808.123145531961344) Not a valid token
[2017-10-07 22:36:16,602] [DEBUG] [rpc:3964] (31808.123145531961344) Authenticated with password
[2017-10-07 22:36:16,875] [WARNING] [blockchain:134] (31808.123145531961344) Using a different number of confirmations (0) instead of default (6)
[2017-10-07 22:36:16,991] [WARNING] [scripts:383] (31808.123145531961344) Using UTXOs with 0 confirmations instead of the default 6
[2017-10-07 22:36:17,101] [DEBUG] [insight_api:41] (31797.123145531961344) GET https://utxo.blockstack.org/insight-api/addr/1ocXpu8pTzHEq4KQkgYNe7W6fwzAvyYT8/utxo
[2017-10-07 22:36:17,980] [DEBUG] [insight_api:52] (31797.123145531961344) 1ocXpu8pTzHEq4KQkgYNe7W6fwzAvyYT8 has 2 UTXOs
[2017-10-07 22:36:17,981] [DEBUG] [rpc:2305] (31808.123145531961344) Failed to transfer balance: Requested withdraw value 349200 exceeds balance 349199
127.0.0.1 - - [07/Oct/2017 22:36:18] "POST /v1/wallet/balance HTTP/1.1" 400 -
```

**Comment by kantai** [comment]
This is fixed in PR #638 --

the API will respond with a 400 status code and 

```
{'error' : 'Not enough inputs for transaction (total: 4999292165, to spend: 4999292165, fee: 955)'}
```
