### ISSUE TITLE
Error when trying to pip2 install the core

### ISSUE THREAD

**Issue by Akito13** [blockstack/blockstack-core#652]
```
sudo pip2 install blockstack --upgrade
Downloading/unpacking blockstack
  Downloading blockstack-0.17.0.8.tar.gz (467kB): 467kB downloaded
  Running setup.py (path:/tmp/pip-build-VaD8UF/blockstack/setup.py) egg_info for package blockstack

Downloading/unpacking virtualchain>=0.17.0 (from blockstack)
  Downloading virtualchain-0.17.0.4.tar.gz (62kB): 62kB downloaded
  Running setup.py (path:/tmp/pip-build-VaD8UF/virtualchain/setup.py) egg_info for package virtualchain

Downloading/unpacking keychain>=0.14.2.0 (from blockstack)
  Downloading keychain-0.14.2.0.tar.gz
  Running setup.py (path:/tmp/pip-build-VaD8UF/keychain/setup.py) egg_info for package keychain

Downloading/unpacking protocoin>=0.2 (from blockstack)
  Downloading protocoin-0.2.tar.gz
  Running setup.py (path:/tmp/pip-build-VaD8UF/protocoin/setup.py) egg_info for package protocoin

    warning: no previously-included files matching '*.pyc' found under directory 'protocoin'
    warning: no previously-included files matching '*.pyo' found under directory 'protocoin'
    warning: no previously-included files matching '*' found under directory 'docs'
Downloading/unpacking blockstack-profiles>=0.14.1 (from blockstack)
  Downloading blockstack-profiles-0.14.1.tar.gz
  Running setup.py (path:/tmp/pip-build-VaD8UF/blockstack-profiles/setup.py) egg_info for package blockstack-profiles

Downloading/unpacking blockstack-zones>=0.14.3 (from blockstack)
  Downloading blockstack-zones-0.14.3.tar.gz
  Running setup.py (path:/tmp/pip-build-VaD8UF/blockstack-zones/setup.py) egg_info for package blockstack-zones

Downloading/unpacking defusedxml>=0.4.1 (from blockstack)
  Downloading defusedxml-0.5.0-py2.py3-none-any.whl
Downloading/unpacking keylib>=0.1.1 (from blockstack)
  Downloading keylib-0.1.1.tar.gz
  Running setup.py (path:/tmp/pip-build-VaD8UF/keylib/setup.py) egg_info for package keylib

Downloading/unpacking simplejson>=3.8.2 (from blockstack)
  Downloading simplejson-3.11.1.tar.gz (78kB): 78kB downloaded
  Running setup.py (path:/tmp/pip-build-VaD8UF/simplejson/setup.py) egg_info for package simplejson

Downloading/unpacking jsonschema>=2.5.1 (from blockstack)
  Downloading jsonschema-2.6.0-py2.py3-none-any.whl
Downloading/unpacking jsontokens>=0.0.4 (from blockstack)
  Downloading jsontokens-0.0.4.tar.gz
  Running setup.py (path:/tmp/pip-build-VaD8UF/jsontokens/setup.py) egg_info for package jsontokens

Downloading/unpacking scrypt>=0.8.0 (from blockstack)
  Downloading scrypt-0.8.0.tar.gz
  Running setup.py (path:/tmp/pip-build-VaD8UF/scrypt/setup.py) egg_info for package scrypt

Requirement already up-to-date: pyparsing>=2.2.0 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Downloading/unpacking basicrpc>=0.0.2 (from blockstack)
  Downloading basicrpc-0.0.2.tar.gz
  Running setup.py (path:/tmp/pip-build-VaD8UF/basicrpc/setup.py) egg_info for package basicrpc

Downloading/unpacking boto>=2.38.0 (from blockstack)
  Downloading boto-2.48.0-py2.py3-none-any.whl (1.4MB): 1.4MB downloaded
Downloading/unpacking dropbox>=7.1.1 (from blockstack)
  Downloading dropbox-8.4.0-py2-none-any.whl (427kB): 427kB downloaded
Downloading/unpacking pydrive>=1.3.1 (from blockstack)
  Downloading PyDrive-1.3.1-py2-none-any.whl
Downloading/unpacking onedrivesdk>=1.1.8 (from blockstack)
  Downloading onedrivesdk-1.1.8.zip (203kB): 203kB downloaded
  Running setup.py (path:/tmp/pip-build-VaD8UF/onedrivesdk/setup.py) egg_info for package onedrivesdk

    warning: no files found matching '*' under directory 'src\python2'
    warning: no files found matching '*' under directory 'src\python3'
Downloading/unpacking cryptography>=1.9 (from virtualchain>=0.17.0->blockstack)
  Downloading cryptography-2.1.1.tar.gz (441kB): 441kB downloaded
  Running setup.py (path:/tmp/pip-build-VaD8UF/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-VaD8UF/cryptography
Storing debug log for failure in /root/.pip/pip.log
```

/root/.pip/pip.log output:
```
  Using version 2.1.1 (newest of versions: 2.1.1, 2.1, 2.0.3, 2.0.2, 2.0.1, 2.0, 1.9)
  Downloading from URL https://pypi.python.org/packages/bf/da/6a9f49cc7a970380c8235b3adab0c08c7c3d4814876f7383b33e3882a577/cryptography-2.1.1.tar.gz#md5=fa98118b468020349a798776aac6d572 (from https://pypi.python.org/simple/cryptography/)
  Running setup.py (path:/tmp/pip-build-VaD8UF/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-VaD8UF/cryptography
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-VaD8UF/cryptography
```

Linux hostname 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux
Raspbian on Raspi0W

python2 is available and used every day, so it works.

**Comment by kantai** [comment]
It looks like a recent version of python-cryptography triggered a bug in python setuptools (see this issue: https://github.com/pyca/cryptography/issues/3981) which needs an upgrade.

Try running:
```
pip install --upgrade pip setuptools
```

And then running the pip install again.

**Comment by Akito13** [comment]
@kantai It installed successfully now, thanks!

**Comment by woshiyushengzhou** [comment]
@kantai thanks ,i love you, i love you, love love love memeda

**Comment by woshiyushengzhou** [comment]
@kantai @Akito13      i love you
