### ISSUE TITLE
blockstack-core not working with gaia.

### ISSUE THREAD

**Issue by inzig** [blockstack/blockstack-core#653]
Blockstack-core are not working with Gaia storage driver.
System capabities:
64-bit processor.
win 10.

**Comment by larrysalibra** [comment]
@inzig Can you provide more information? How are you trying to use it? What error messages are you seeing?

**Comment by inzig** [comment]
i am trying to install Blockstack core , blockstack browser and gaia on local server. I have tried to install gaia with python. but it needs visual studio build tools. i have installed them too but it is not working again. Ca you please provide a simple guide how to setup everything on local machine and store data on gaia locally.

**Comment by inzig** [comment]
@larrysalibra here is the link of screenshot. https://screenshots.firefox.com/Z8ymylasERJKjmkp/localhost

when i am trying to click on"use default storage" button it doesn't work. before this default storage option is not showing up but when i trying to install gaia using python this default storage option shows but its not working now.
Following is the error showing in the console:
TypeError: NetworkError when attempting to fetch resource.

**Comment by larrysalibra** [comment]
@inzig that message sounds like what happens when blockstack core stops running or never starts.

I'm not that familiar with the set up on windows or why that might be happening. (I assume you're using windows because you mentioned visual studio build tools). Tagging @jackzampolin & @kantai who have more experience with our windows set up.

**Comment by inzig** [comment]
Thanks @larrysalibra  Actually for i have downloaded the latest version of 64 bit MSI of blockstack-core from github. installed that on Win 10. Than cloned the Gaia driver , installed python run setup.py, Than run browser link, created the password for core it sych up with the system then it ask for strorage. on the following link 

> http://localhost:8888/account/storage#gaiahub

Than stuck on that screen forever i am trying my best from last 4 days but unable to resolve that i have tried to uninstall and reinstall core again. But have no idea how to fix or uninstall gaia. Which seems to be the real problem as Core is running ok apparently. Please let me know if you guys need more information about the issue.

**Comment by kantai** [comment]
Hi @inzig --

Right now, the browser does not support connecting to a local gaia hub for providing storage. Before trying to setup a local Python environment with custom settings, try to run the standard Blockstack windows installer and see if the storage connections are working for you.

**Comment by inzig** [comment]
Thanks Aaron @kantai  for follow up--

Local gaia hub for providing storage, is not working but it is also not working with drop box either. 
I have run todo demo app on local machine after select dropbox from storage provider option.
After adding todo in todo app it calls the following url in network

> http://0.0.0.0:6270/v1/stores/1H2dSGjMQcnjBXdzdZpsjxdx65rjvM3jDX?device_ids=0&blockchain_id=a271cf03a676f1459881097b5b468eead55bbc1db0cf25454984eb1d2ce92407

which returns error.
But when when i change the address to my local vault

> http://localhost:6270/v1/stores/1H2dSGjMQcnjBXdzdZpsjxdx65rjvM3jDX?device_ids=0&blockchain_id=a271cf03a676f1459881097b5b468eead55bbc1db0cf25454984eb1d2ce92407

which returns the following

> {"errno": 2, "error": "Failed to load public datastore record"}

and following comes in the console

>  Error in console:TypeError: NetworkError when attempting to fetch resource.

**Comment by kantai** [comment]
Hi @inzig -- can you update to the latest version of the browser release (v0.18.0)

https://github.com/blockstack/blockstack-browser/releases

On upgrades, you need to clear the local storage in your browser (on the Blockstack home page, you can go to Settings->Remove Account or go to your browser's settings and wipe local storage from there). Then, if you still see errors, can you please obtain:

1. a log from your browser's javascript console (hit Ctrl-Shift-C in Chrome or Firefox)
2. a log from the local api endpoint -- stored in `C:/Users/<your_user>/.blockstack/api_endpoint.log`

The api endpoint log _does_ contain your secret password. Search for and remove the phrase `bearer <password>`.

**Comment by inzig** [comment]
Hello Aaron @kantai  Thanks for the follow up---
New Release (v0.18.0 for win 10) is has solved few issues.
Now Core is working on one windows machine and mac in our team but on one windows 10 machine there is still some issues are persisting. It crashes at the point where to ask for password of core. With authrize : false flage here is is log from file api_endpoint.log

[2017-10-20 12:57:57,377] [DEBUG] [rpc:5195] (29.140183764866816) Attempt 1 to ping API server
[2017-10-20 12:57:57,379] [DEBUG] [rpc:5378] (29.140183764866816) Loading drivers
[2017-10-20 12:57:57,380] [DEBUG] [client:95] (29.140183764866816) Connect to https://node.blockstack.org:6263
[2017-10-20 12:57:57,420] [DEBUG] [rpc:5015] (29.140183764866816) Connect to API at 0.0.0.0:6270
[2017-10-20 12:57:57,432] [DEBUG] [rpc:5206] (29.140183764866816) API server is not responding; trying again in 1 seconds
[2017-10-20 12:57:57,615] [DEBUG] [client:110] (29.140183764866816) Loaded storage drivers ['disk', 'dropbox', 's3', 'blockstack_resolver', 'blockstack_server', 'http', 'dht']
[2017-10-20 12:57:57,706] [DEBUG] [rpc:5380] (29.140183764866816) Loaded drivers
[2017-10-20 12:57:57,750] [DEBUG] [rpc:4146] (29.140183764866816) Set SO_REUSADDR
[2017-10-20 12:57:58,065] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_add_device" as "cli_add_device"
[2017-10-20 12:57:58,069] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_api" as "cli_api"
[2017-10-20 12:57:58,070] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_app_delete_resource" as "cli_app_delete_resource"
[2017-10-20 12:57:58,072] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_app_get_config" as "cli_app_get_config"
[2017-10-20 12:57:58,074] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_app_get_resource" as "cli_app_get_resource"
[2017-10-20 12:57:58,076] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_app_publish" as "cli_app_publish"
[2017-10-20 12:57:58,078] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_app_put_resource" as "cli_app_put_resource"
[2017-10-20 12:57:58,080] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_app_signin" as "cli_app_signin"
[2017-10-20 12:57:58,082] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_balance" as "cli_balance"
[2017-10-20 12:57:58,084] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_collection_getitem" as "cli_collection_getitem"
[2017-10-20 12:57:58,085] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_collection_listitems" as "cli_collection_items"
[2017-10-20 12:57:58,087] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_collection_putitem" as "cli_collection_putitem"
[2017-10-20 12:57:58,089] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_collection_statitem" as "cli_collection_statitem"
[2017-10-20 12:57:58,092] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_configure" as "cli_configure"
[2017-10-20 12:57:58,094] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_consensus" as "cli_consensus"
[2017-10-20 12:57:58,097] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_convert_legacy_profile" as "cli_convert_legacy_profile"
[2017-10-20 12:57:58,099] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_create_collection" as "cli_create_collection"
[2017-10-20 12:57:58,100] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_create_datastore" as "cli_create_datastore"
[2017-10-20 12:57:58,102] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_datastore_deletefile" as "cli_datastore_deletefile"
[2017-10-20 12:57:58,104] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_datastore_get_id" as "cli_datastore_get_id"
[2017-10-20 12:57:58,106] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_datastore_get_privkey" as "cli_datastore_get_privkey"
[2017-10-20 12:57:58,108] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_datastore_getfile" as "cli_datastore_getfile"
[2017-10-20 12:57:58,110] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_datastore_getinode" as "cli_datastore_getinode"
[2017-10-20 12:57:58,111] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_datastore_listdir" as "cli_datastore_listdir"
[2017-10-20 12:57:58,114] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_datastore_mkdir" as "cli_datastore_mkdir"
[2017-10-20 12:57:58,116] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_datastore_putfile" as "cli_datastore_putfile"
[2017-10-20 12:57:58,118] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_datastore_rmdir" as "cli_datastore_rmdir"
[2017-10-20 12:57:58,119] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_datastore_rmtree" as "cli_datastore_rmtree"
[2017-10-20 12:57:58,121] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_datastore_stat" as "cli_datastore_stat"
[2017-10-20 12:57:58,124] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_delete_account" as "cli_delete_account"
[2017-10-20 12:57:58,126] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_delete_collection" as "cli_delete_collection"
[2017-10-20 12:57:58,127] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_delete_datastore" as "cli_delete_datastore"
[2017-10-20 12:57:58,129] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_delete_immutable" as "cli_delete_immutable"
[2017-10-20 12:57:58,130] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_delete_mutable" as "cli_delete_mutable"
[2017-10-20 12:57:58,132] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_delete_profile" as "cli_delete_profile"
[2017-10-20 12:57:58,134] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_deposit" as "cli_deposit"
[2017-10-20 12:57:58,136] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_account" as "cli_get_account"
[2017-10-20 12:57:58,138] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_all_names" as "cli_get_all_names"
[2017-10-20 12:57:58,140] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_all_namespaces" as "cli_get_all_namespaces"
[2017-10-20 12:57:58,142] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_collection" as "cli_get_collection"
[2017-10-20 12:57:58,144] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_datastore" as "cli_get_datastore"
[2017-10-20 12:57:58,146] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_device_keys" as "cli_get_device_keys"
[2017-10-20 12:57:58,147] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_immutable" as "cli_get_immutable"
[2017-10-20 12:57:58,149] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_mutable" as "cli_get_mutable"
[2017-10-20 12:57:58,151] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_name_blockchain_history" as "cli_get_name_blockchain_history"
[2017-10-20 12:57:58,152] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_name_blockchain_record" as "cli_get_name_blockchain_record"
[2017-10-20 12:57:58,154] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_name_zonefile" as "cli_get_name_zonefile"
[2017-10-20 12:57:58,156] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_nameops_at" as "cli_get_nameops_at"
[2017-10-20 12:57:58,158] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_names_in_namespace" as "cli_get_names_in_namespace"
[2017-10-20 12:57:58,160] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_names_owned_by_address" as "cli_get_names_owned_by_address"
[2017-10-20 12:57:58,161] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_namespace_blockchain_record" as "cli_get_namespace_blockchain_record"
[2017-10-20 12:57:58,163] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_namespace_cost" as "cli_get_namespace_cost"
[2017-10-20 12:57:58,165] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_public_key" as "cli_get_public_key"
[2017-10-20 12:57:58,168] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_get_registrar_info" as "cli_get_registrar_info"
[2017-10-20 12:57:58,170] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_import" as "cli_import"
[2017-10-20 12:57:58,172] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_import_wallet" as "cli_import_wallet"
[2017-10-20 12:57:58,177] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_info" as "cli_info"
[2017-10-20 12:57:58,178] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_list_accounts" as "cli_list_accounts"
[2017-10-20 12:57:58,180] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_list_devices" as "cli_list_devices"
[2017-10-20 12:57:58,182] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_list_immutable_data_history" as "cli_list_immutable_data_history"
[2017-10-20 12:57:58,183] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_list_update_history" as "cli_list_update_history"
[2017-10-20 12:57:58,185] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_list_zonefile_history" as "cli_list_zonefile_history"
[2017-10-20 12:57:58,187] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_lookup" as "cli_lookup"
[2017-10-20 12:57:58,189] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_lookup_snv" as "cli_lookup_snv"
[2017-10-20 12:57:58,191] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_migrate" as "cli_migrate"
[2017-10-20 12:57:58,192] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_name_import" as "cli_name_import"
[2017-10-20 12:57:58,194] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_names" as "cli_names"
[2017-10-20 12:57:58,195] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_namespace_preorder" as "cli_namespace_preorder"
[2017-10-20 12:57:58,197] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_namespace_ready" as "cli_namespace_ready"
[2017-10-20 12:57:58,198] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_namespace_reveal" as "cli_namespace_reveal"
[2017-10-20 12:57:58,200] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_ping" as "cli_ping"
[2017-10-20 12:57:58,202] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_price" as "cli_price"
[2017-10-20 12:57:58,204] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_put_account" as "cli_put_account"
[2017-10-20 12:57:58,206] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_put_immutable" as "cli_put_immutable"
[2017-10-20 12:57:58,208] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_put_mutable" as "cli_put_mutable"
[2017-10-20 12:57:58,210] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_put_profile" as "cli_put_profile"
[2017-10-20 12:57:58,211] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_register" as "cli_register"
[2017-10-20 12:57:58,213] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_remove_device" as "cli_remove_device"
[2017-10-20 12:57:58,215] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_renew" as "cli_renew"
[2017-10-20 12:57:58,216] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_revoke" as "cli_revoke"
[2017-10-20 12:57:58,218] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_set_zonefile_hash" as "cli_set_zonefile_hash"
[2017-10-20 12:57:58,220] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_setup" as "cli_setup"
[2017-10-20 12:57:58,221] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_setup_wallet" as "cli_setup_wallet"
[2017-10-20 12:57:58,223] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_sign_data" as "cli_sign_data"
[2017-10-20 12:57:58,225] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_sign_profile" as "cli_sign_profile"
[2017-10-20 12:57:58,227] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_start_server" as "cli_start_server"
[2017-10-20 12:57:58,229] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_stop_server" as "cli_stop_server"
[2017-10-20 12:57:58,231] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_sync_zonefile" as "cli_sync_zonefile"
[2017-10-20 12:57:58,233] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_transfer" as "cli_transfer"
[2017-10-20 12:57:58,234] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_unqueue" as "cli_unqueue"
[2017-10-20 12:57:58,236] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_update" as "cli_update"
[2017-10-20 12:57:58,238] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_validate_zone_file" as "cli_validate_zone_file"
[2017-10-20 12:57:58,240] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_verify_data" as "cli_verify_data"
[2017-10-20 12:57:58,242] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_verify_profile" as "cli_verify_profile"
[2017-10-20 12:57:58,244] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_wallet" as "cli_wallet"
[2017-10-20 12:57:58,245] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_wallet_password" as "cli_wallet_password"
[2017-10-20 12:57:58,247] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_whois" as "cli_whois"
[2017-10-20 12:57:58,249] [DEBUG] [rpc:4111] (44.140183764866816) Register CLI method "cli_withdraw" as "cli_withdraw"
[2017-10-20 12:57:58,251] [DEBUG] [rpc:5405] (44.140183764866816) Initializing registrar...
[2017-10-20 12:57:58,253] [DEBUG] [registrar:107] (44.140183764866816) RegistrarWorker already initialized
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/rpc_runner.py", line 70, in <module>
    res = local_api_start(port=portnum, config_dir=config_dir, api_pass=api_pass, password=passwd)
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/rpc.py", line 5408, in local_api_start
    log.error("Failed to initialize registrar: {}".format(res['error']))
TypeError: 'int' object has no attribute '__getitem__'
[2017-10-20 12:57:58,256] [DEBUG] [rpc:5163] (44.140183764866816) Atexit handler invoked; shutting down
[2017-10-20 12:57:58,258] [DEBUG] [rpc:4976] (44.140183764866816) Server shutdown
[2017-10-20 12:57:58,443] [DEBUG] [rpc:5195] (29.140183764866816) Attempt 2 to ping API server
[2017-10-20 12:57:58,474] [DEBUG] [rpc:5015] (29.140183764866816) Connect to API at 0.0.0.0:6270
[2017-10-20 12:57:58,476] [DEBUG] [rpc:5206] (29.140183764866816) API server is not responding; trying again in 2 seconds
[2017-10-20 12:58:00,479] [DEBUG] [rpc:5195] (29.140183764866816) Attempt 3 to ping API server
[2017-10-20 12:58:00,490] [DEBUG] [rpc:5015] (29.140183764866816) Connect to API at 0.0.0.0:6270
[2017-10-20 12:58:00,492] [DEBUG] [rpc:5206] (29.140183764866816) API server is not responding; trying again in 3 seconds
[2017-10-20 12:58:03,496] [DEBUG] [rpc:5195] (29.140183764866816) Attempt 4 to ping API server
[2017-10-20 12:58:03,515] [DEBUG] [rpc:5015] (29.140183764866816) Connect to API at 0.0.0.0:6270
[2017-10-20 12:58:03,518] [DEBUG] [rpc:5206] (29.140183764866816) API server is not responding; trying again in 4 seconds
[2017-10-20 12:58:07,522] [DEBUG] [rpc:5195] (29.140183764866816) Attempt 5 to ping API server
[2017-10-20 12:58:07,543] [DEBUG] [rpc:5015] (29.140183764866816) Connect to API at 0.0.0.0:6270
[2017-10-20 12:58:07,545] [DEBUG] [rpc:5206] (29.140183764866816) API server is not responding; trying again in 5 seconds
[2017-10-20 12:58:12,549] [DEBUG] [rpc:5195] (29.140183764866816) Attempt 6 to ping API server
[2017-10-20 12:58:12,584] [DEBUG] [rpc:5015] (29.140183764866816) Connect to API at 0.0.0.0:6270
[2017-10-20 12:58:12,587] [DEBUG] [rpc:5206] (29.140183764866816) API server is not responding; trying again in 6 seconds
[2017-10-20 12:58:18,593] [DEBUG] [rpc:5195] (29.140183764866816) Attempt 7 to ping API server
[2017-10-20 12:58:18,609] [DEBUG] [rpc:5015] (29.140183764866816) Connect to API at 0.0.0.0:6270
[2017-10-20 12:58:18,611] [DEBUG] [rpc:5206] (29.140183764866816) API server is not responding; trying again in 7 seconds
[2017-10-20 12:58:25,619] [DEBUG] [rpc:5195] (29.140183764866816) Attempt 8 to ping API server
[2017-10-20 12:58:25,646] [DEBUG] [rpc:5015] (29.140183764866816) Connect to API at 0.0.0.0:6270
[2017-10-20 12:58:25,648] [DEBUG] [rpc:5206] (29.140183764866816) API server is not responding; trying again in 8 seconds
[2017-10-20 12:58:33,656] [DEBUG] [rpc:5195] (29.140183764866816) Attempt 9 to ping API server
[2017-10-20 12:58:33,680] [DEBUG] [rpc:5015] (29.140183764866816) Connect to API at 0.0.0.0:6270
[2017-10-20 12:58:33,684] [DEBUG] [rpc:5206] (29.140183764866816) API server is not responding; trying again in 9 seconds
[2017-10-20 12:58:42,693] [ERROR] [rpc:5224] (29.140183764866816) API endpoint did not initialize

**Comment by kantai** [comment]
Hi @inzig,

Thanks for posting this logfile.

It looks like the daemons are failing to start because a copy of the blockstack daemon is already running. Can you try rebooting that machine and running blockstack again?

**Comment by inzig** [comment]
Hello Aaron @kantai ,
Thanks for follow up Aaron. The issue is resolved and i am closing it but for record i am mention few things if anybody come across the same error.

> Here is the thing Gaia storage do not work with release 0.17.0
and if you guys have installed blockstack-core once on your Windows PC and you want to reinstall the same or another version keep in mind.

> To installed new version you have uninstall the current blockstack-core from your PC as well as Dropbox. and Install blockstack-core from scratch.
other wise Dropbox will keep running the older daemon which will conflict with new install.
