### ISSUE TITLE
Trying to run core instance fails

### ISSUE THREAD

**Issue by Akito13** [blockstack/blockstack-core#654]
tail -f -n 40 ~/.blockstack-server/blockstack-server.log output:
```
[2017-10-17 23:52:50,751] [DEBUG] [atlas:3125] (26161.-1307921312) Peer 176.223.226.92:6264 has a stale zonefile inventory
[2017-10-17 23:52:50,753] [DEBUG] [atlas:3125] (26161.-1307921312) Peer 40.121.158.86:6264 has a stale zonefile inventory
[2017-10-17 23:52:50,755] [DEBUG] [atlas:3125] (26161.-1307921312) Peer 40.76.194.199:6264 has a stale zonefile inventory
[2017-10-17 23:52:50,756] [DEBUG] [atlas:3125] (26161.-1307921312) Peer localhost:6264 has a stale zonefile inventory
[2017-10-17 23:52:50,758] [DEBUG] [atlas:3125] (26161.-1307921312) Peer 176.58.115.89:6264 has a stale zonefile inventory
[2017-10-17 23:52:50,760] [DEBUG] [atlas:3125] (26161.-1307921312) Peer 40.118.132.60:6264 has a stale zonefile inventory
[2017-10-17 23:52:50,762] [DEBUG] [atlas:3125] (26161.-1307921312) Peer 13.64.158.139:6264 has a stale zonefile inventory
[2017-10-17 23:52:50,764] [DEBUG] [atlas:3125] (26161.-1307921312) Peer node.blockstack.org:6264 has a stale zonefile inventory
[2017-10-17 23:52:50,765] [DEBUG] [atlas:3125] (26161.-1307921312) Peer 40.123.44.241:6264 has a stale zonefile inventory
[2017-10-17 23:52:50,767] [DEBUG] [atlas:3125] (26161.-1307921312) Peer 104.45.147.193:6264 has a stale zonefile inventory
[2017-10-17 23:52:50,769] [DEBUG] [atlas:3125] (26161.-1307921312) Peer 165.227.14.56:6264 has a stale zonefile inventory
[2017-10-17 23:52:50,778] [DEBUG] [atlas:3009] (26161.-1316309920) hostname:6264: crawl 40.121.156.215:6264
[2017-10-17 23:52:50,771] [DEBUG] [atlas:3128] (26161.-1307921312) Refresh zonefile inventories for 19 peers
[2017-10-17 23:52:50,819] [DEBUG] [atlas:3132] (26161.-1307921312) hostname:6264: Refresh zonefile inventory for 52.225.128.191:6264
[2017-10-17 23:52:51,321] [WARNING] [proxy:153] (26161.-1316309920) RPC constructor called without a protocol, defaulting to HTTP, this could be an issue if connection is on :6263
[2017-10-17 23:52:51,493] [DEBUG] [namedb:92] (26161.-1225568256) Connect to database '/home/pi/.blockstack-server/blockstack-server.db'
[2017-10-17 23:52:51,511] [DEBUG] [indexer:175] (26161.-1225568256) consensus snapshots at '/home/pi/.blockstack-server/blockstack-server.snapshots'
[2017-10-17 23:52:54,994] [DEBUG] [indexer:210] (26161.-1225568256) lastblock at '/home/pi/.blockstack-server/blockstack-server.lastblock'
[2017-10-17 23:52:55,004] [DEBUG] [indexer:213] (26161.-1225568256) Lastblock: 490320 (/home/pi/.blockstack-server/blockstack-server.lastblock)
[2017-10-17 23:52:55,008] [DEBUG] [atlas:2152] (26161.-1324698528) Missing 256 zonefiles
[2017-10-17 23:52:55,254] [DEBUG] [blockstackd:2363] (26161.-1225568256) Begin indexing (up to 490361)
[2017-10-17 23:52:55,257] [INFO] [virtualchain_hooks:506] (26161.-1225568256) Synchronizing database up to block 490361
[2017-10-17 23:52:55,259] [DEBUG] [namedb:92] (26161.-1225568256) Connect to database '/home/pi/.blockstack-server/blockstack-server.db'
[2017-10-17 23:52:55,474] [DEBUG] [indexer:175] (26161.-1225568256) consensus snapshots at '/home/pi/.blockstack-server/blockstack-server.snapshots'
[2017-10-17 23:52:58,425] [DEBUG] [indexer:210] (26161.-1225568256) lastblock at '/home/pi/.blockstack-server/blockstack-server.lastblock'
[2017-10-17 23:52:58,427] [DEBUG] [indexer:213] (26161.-1225568256) Lastblock: 490320 (/home/pi/.blockstack-server/blockstack-server.lastblock)
[2017-10-17 23:52:58,518] [DEBUG] [atlas:1944] (26161.-1307921312) Download zonefile inventory 0-10451 from 52.225.128.191:6264
[2017-10-17 23:52:58,844] [DEBUG] [indexer:1125] (26161.-1225568256) Sync virtualchain state from 490321 to 490362
[2017-10-17 23:52:58,867] [WARNING] [proxy:153] (26161.-1307921312) RPC constructor called without a protocol, defaulting to HTTP, this could be an issue if connection is on :6263
[2017-10-17 23:52:58,871] [DEBUG] [atlas:1895] (26161.-1307921312) Get zonefile inventory range 0-524288 from 52.225.128.191:6264
[2017-10-17 23:52:58,859] [ERROR] [virtualchain:64] (26161.-1225568256) Python int too large to convert to C long
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/virtualchain.py", line 60, in sync_virtualchain
    rc = indexer.StateEngine.build(bitcoind_opts, last_block + 1, state_engine, expected_snapshots=expected_snapshots, tx_filter=tx_filter )
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/indexer.py", line 1133, in build
    block_ids_and_txs = transactions.get_virtual_transactions( bitcoind_opts, block_id, last_block_id, spv_last_block=end_block_id - 1, tx_filter=tx_filter )
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/transactions.py", line 82, in get_virtual_transactions
    for i in xrange(0, 100000000000, 1):
OverflowError: Python int too large to convert to C long
[2017-10-17 23:52:58,914] [ERROR] [virtualchain:65] (26161.-1225568256) Failed to synchronize chain; exiting to safety
```

**Comment by jcnelson** [comment]
Hey @Akito13, thanks for reporting!

This is an interesting bug.  Are you using a 32-bit processor?

**Comment by Akito13** [comment]
@jcnelson Running on Raspi0W, running Raspbian.
Linux hostname 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux

**Comment by jcnelson** [comment]
Yup, 32-bit.  Not sure if it's the exact reason (I don't have a Pi available at the moment), but that's my best guess.

Anyway, the bug is in `virtualchain`.  I have a hotfix branch going for it here: https://github.com/blockstack/virtualchain/tree/hotfix/compat32

**Comment by Akito13** [comment]
How do I apply it?

**Comment by jcnelson** [comment]
You can get it now by checking out the branch and installing it on your machine.

I'll have it packaged up in PyPI in a day or two (need to verify it passes our tests first).

**Comment by Akito13** [comment]
So do I just run the setup.py or is anything else necessary? Don't want to break something.

**Comment by jcnelson** [comment]
Just the `setup.py install` should work (once you've done the `git clone` and `git checkout hotfix/compat32`).

**Comment by Akito13** [comment]
I don't understand the `git checkout hotfix/compat32` quite yet.

**Comment by Akito13** [comment]
I think it works now.
```
[2017-10-18 01:09:12,209] [DEBUG] [db:1861] (29674.-1225211904) 0 name-preorder/import states at 490270
[2017-10-18 01:09:17,683] [DEBUG] [db:1916] (29674.-1225211904) 0 name-change states at 490270
[2017-10-18 01:09:17,719] [DEBUG] [db:1962] (29674.-1225211904) 0 preorders created at 490270
[2017-10-18 01:09:17,723] [DEBUG] [db:2006] (29674.-1225211904) 0 namespace-preorder states at 490270
[2017-10-18 01:09:18,045] [DEBUG] [db:2054] (29674.-1225211904) 0 namespace-change states at 490270
[2017-10-18 01:09:18,049] [DEBUG] [namedb:775] (29674.-1225211904) Get all ops at 490271 in /home/pi/.blockstack-server/
blockstack-server.db
```

If that means that it works. (?)

**Comment by jackzampolin** [comment]
We have made significant changes to the software since this issue was active. Closing this as stale. If this was closed in error please be sure to re-open.

**Comment by Akito13** [comment]
Just to confirm: the OverflowError was fixed and the core starts on Raspi 0W now.
