### ISSUE TITLE
Problem installing core via pip instructions

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#657]
I was trying to install via docker #656 without success on a Ubuntu 16.04.3 virtual machine.

Decided to try the pip install instructions instead.

Got further than docker, but core fails to start with some sort of SSL error:

```
root@blockstack:~#  sudo apt-get update && sudo apt-get install -y python-pip python-dev libssl-dev libffi-dev rng-tools libgmp3-dev
Hit:1 http://hk.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://hk.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                           
Hit:3 http://hk.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                         
Hit:4 https://download.docker.com/linux/ubuntu xenial InRelease                                                                  
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                                                       
Hit:6 http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu xenial InRelease
Fetched 102 kB in 1s (64.9 kB/s)                              
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version (3.2.1-4).
python-dev is already the newest version (2.7.11-1).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.8).
python-pip is already the newest version (8.1.1-2ubuntu0.4).
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-18 linux-headers-4.4.0-18-generic linux-headers-4.4.0-21 linux-headers-4.4.0-21-generic linux-image-4.4.0-18-generic linux-image-4.4.0-21-generic
  linux-image-extra-4.4.0-18-generic linux-image-extra-4.4.0-21-generic ubuntu-core-launcher
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libgmp-dev libgmpxx4ldbl
Suggested packages:
  gmp-doc libgmp10-doc libmpfr-dev
The following NEW packages will be installed:
  libgmp-dev libgmp3-dev libgmpxx4ldbl rng-tools
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 347 kB of archives.
After this operation, 1,855 kB of additional disk space will be used.
Get:1 http://hk.archive.ubuntu.com/ubuntu xenial/main amd64 libgmpxx4ldbl amd64 2:6.1.0+dfsg-2 [8,948 B]
Get:2 http://hk.archive.ubuntu.com/ubuntu xenial/main amd64 libgmp-dev amd64 2:6.1.0+dfsg-2 [314 kB]
Get:3 http://hk.archive.ubuntu.com/ubuntu xenial/main amd64 libgmp3-dev amd64 2:6.1.0+dfsg-2 [1,920 B]
Get:4 http://hk.archive.ubuntu.com/ubuntu xenial/universe amd64 rng-tools amd64 5-0ubuntu3 [21.9 kB]
Fetched 347 kB in 0s (1,181 kB/s)    
Selecting previously unselected package libgmpxx4ldbl:amd64.
(Reading database ... 170574 files and directories currently installed.)
Preparing to unpack .../libgmpxx4ldbl_2%3a6.1.0+dfsg-2_amd64.deb ...
Unpacking libgmpxx4ldbl:amd64 (2:6.1.0+dfsg-2) ...
Selecting previously unselected package libgmp-dev:amd64.
Preparing to unpack .../libgmp-dev_2%3a6.1.0+dfsg-2_amd64.deb ...
Unpacking libgmp-dev:amd64 (2:6.1.0+dfsg-2) ...
Selecting previously unselected package libgmp3-dev.
Preparing to unpack .../libgmp3-dev_2%3a6.1.0+dfsg-2_amd64.deb ...
Unpacking libgmp3-dev (2:6.1.0+dfsg-2) ...
Selecting previously unselected package rng-tools.
Preparing to unpack .../rng-tools_5-0ubuntu3_amd64.deb ...
Unpacking rng-tools (5-0ubuntu3) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for systemd (229-4ubuntu19) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up libgmpxx4ldbl:amd64 (2:6.1.0+dfsg-2) ...
Setting up libgmp-dev:amd64 (2:6.1.0+dfsg-2) ...
Setting up libgmp3-dev (2:6.1.0+dfsg-2) ...
Setting up rng-tools (5-0ubuntu3) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for systemd (229-4ubuntu19) ...
Processing triggers for ureadahead (0.100.0-19) ...
root@blockstack:~# sudo pip2 install pyparsing
Collecting pyparsing
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 2.1MB/s 
Installing collected packages: pyparsing
Successfully installed pyparsing-2.2.0
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@blockstack:~# sudo pip2 install blockstack --upgrade
Collecting blockstack
  Downloading blockstack-0.17.0.9.tar.gz (470kB)
    100% |████████████████████████████████| 471kB 1.8MB/s 
Collecting virtualchain>=0.17.0 (from blockstack)
  Downloading virtualchain-0.17.0.4.tar.gz (62kB)
    100% |████████████████████████████████| 71kB 5.6MB/s 
Collecting keychain>=0.14.2.0 (from blockstack)
  Downloading keychain-0.14.2.0.tar.gz
Collecting protocoin>=0.2 (from blockstack)
  Downloading protocoin-0.2.tar.gz
Collecting blockstack-profiles>=0.14.1 (from blockstack)
  Downloading blockstack-profiles-0.14.1.tar.gz
Collecting blockstack-zones>=0.14.3 (from blockstack)
  Downloading blockstack-zones-0.14.3.tar.gz
Collecting defusedxml>=0.4.1 (from blockstack)
  Downloading defusedxml-0.5.0-py2.py3-none-any.whl
Collecting keylib>=0.1.1 (from blockstack)
  Downloading keylib-0.1.1.tar.gz
Collecting simplejson>=3.8.2 (from blockstack)
  Downloading simplejson-3.11.1.tar.gz (78kB)
    100% |████████████████████████████████| 81kB 5.7MB/s 
Collecting jsonschema>=2.5.1 (from blockstack)
  Downloading jsonschema-2.6.0-py2.py3-none-any.whl
Collecting jsontokens>=0.0.4 (from blockstack)
  Downloading jsontokens-0.0.4.tar.gz
Collecting scrypt>=0.8.0 (from blockstack)
  Downloading scrypt-0.8.0.tar.gz
Requirement already up-to-date: pyparsing>=2.2.0 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Requirement already up-to-date: basicrpc>=0.0.2 in /usr/local/lib/python2.7/dist-packages (from blockstack)
Collecting boto>=2.38.0 (from blockstack)
  Downloading boto-2.48.0-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 722kB/s 
Collecting dropbox>=7.1.1 (from blockstack)
  Downloading dropbox-8.4.0-py2-none-any.whl (427kB)
    100% |████████████████████████████████| 430kB 2.5MB/s 
Collecting pydrive>=1.3.1 (from blockstack)
  Downloading PyDrive-1.3.1-py2-none-any.whl
Collecting onedrivesdk>=1.1.8 (from blockstack)
  Downloading onedrivesdk-1.1.8.zip (203kB)
    100% |████████████████████████████████| 204kB 4.9MB/s 
Collecting cryptography>=1.9 (from virtualchain>=0.17.0->blockstack)
  Downloading cryptography-2.1.1-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 509kB/s 
Requirement already up-to-date: ecdsa>=0.13 in /usr/local/lib/python2.7/dist-packages (from virtualchain>=0.17.0->blockstack)
Collecting six>=1.10.0 (from virtualchain>=0.17.0->blockstack)
  Downloading six-1.11.0-py2.py3-none-any.whl
Requirement already up-to-date: bitmerchant>=0.1.8 in /usr/local/lib/python2.7/dist-packages (from keychain>=0.14.2.0->blockstack)
Collecting warlock>=1.3.0 (from blockstack-profiles>=0.14.1->blockstack)
  Downloading warlock-1.3.0.tar.gz
Requirement already up-to-date: utilitybelt>=0.2.6 in /usr/local/lib/python2.7/dist-packages (from keylib>=0.1.1->blockstack)
Collecting functools32; python_version == "2.7" (from jsonschema>=2.5.1->blockstack)
  Downloading functools32-3.2.3-2.zip
Collecting requests>=2.16.2 (from dropbox>=7.1.1->blockstack)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 5.4MB/s 
Collecting PyYAML>=3.0 (from pydrive>=1.3.1->blockstack)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 3.9MB/s 
Collecting google-api-python-client>=1.2 (from pydrive>=1.3.1->blockstack)
  Downloading google_api_python_client-1.6.4-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 8.9MB/s 
Collecting oauth2client>=4.0.0 (from pydrive>=1.3.1->blockstack)
  Downloading oauth2client-4.1.2-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 6.8MB/s 
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.9->virtualchain>=0.17.0->blockstack)
  Downloading cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl (405kB)
    100% |████████████████████████████████| 409kB 2.7MB/s 
Requirement already up-to-date: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.9->virtualchain>=0.17.0->blockstack)
Collecting idna>=2.1 (from cryptography>=1.9->virtualchain>=0.17.0->blockstack)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 5.3MB/s 
Collecting asn1crypto>=0.21.0 (from cryptography>=1.9->virtualchain>=0.17.0->blockstack)
  Downloading asn1crypto-0.23.0-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 7.3MB/s 
Collecting ipaddress; python_version < "3" (from cryptography>=1.9->virtualchain>=0.17.0->blockstack)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Collecting cachetools>=1.1.1 (from bitmerchant>=0.1.8->keychain>=0.14.2.0->blockstack)
  Downloading cachetools-2.0.1-py2.py3-none-any.whl
Collecting base58>=0.2.1 (from bitmerchant>=0.1.8->keychain>=0.14.2.0->blockstack)
  Downloading base58-0.2.5-py2-none-any.whl
Collecting jsonpatch<2,>=0.10 (from warlock>=1.3.0->blockstack-profiles>=0.14.1->blockstack)
  Downloading jsonpatch-1.16-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.16.2->dropbox>=7.1.1->blockstack)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 6.3MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.16.2->dropbox>=7.1.1->blockstack)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 7.3MB/s 
Collecting certifi>=2017.4.17 (from requests>=2.16.2->dropbox>=7.1.1->blockstack)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 3.2MB/s 
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client>=1.2->pydrive>=1.3.1->blockstack)
  Downloading uritemplate-3.0.0-py2.py3-none-any.whl
Collecting httplib2<1dev,>=0.9.2 (from google-api-python-client>=1.2->pydrive>=1.3.1->blockstack)
  Downloading httplib2-0.10.3.tar.gz (204kB)
    100% |████████████████████████████████| 204kB 3.6MB/s 
Collecting rsa>=3.1.4 (from oauth2client>=4.0.0->pydrive>=1.3.1->blockstack)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 6.8MB/s 
Collecting pyasn1-modules>=0.0.5 (from oauth2client>=4.0.0->pydrive>=1.3.1->blockstack)
  Downloading pyasn1_modules-0.1.5-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 5.6MB/s 
Collecting pyasn1>=0.1.7 (from oauth2client>=4.0.0->pydrive>=1.3.1->blockstack)
  Downloading pyasn1-0.3.7-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 6.6MB/s 
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.9->virtualchain>=0.17.0->blockstack)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 3.9MB/s 
Collecting jsonpointer>=1.9 (from jsonpatch<2,>=0.10->warlock>=1.3.0->blockstack-profiles>=0.14.1->blockstack)
  Downloading jsonpointer-1.12-py2.py3-none-any.whl
Building wheels for collected packages: blockstack, virtualchain, keychain, protocoin, blockstack-profiles, blockstack-zones, keylib, simplejson, jsontokens, scrypt, onedrivesdk, warlock, functools32, PyYAML, httplib2, pycparser
  Running setup.py bdist_wheel for blockstack ... done
  Stored in directory: /root/.cache/pip/wheels/d7/c3/0f/9896c412d2f53f6fc6c38be9e7401c916fedf3bd0c26ebcdbb
  Running setup.py bdist_wheel for virtualchain ... done
  Stored in directory: /root/.cache/pip/wheels/56/93/c4/fa21f67516274d35a217f5b38106e1bce90a087163be69d55f
  Running setup.py bdist_wheel for keychain ... done
  Stored in directory: /root/.cache/pip/wheels/2a/f4/1d/2f9ad798cd7c22666b238b81403a43223bf5a0564c38e91452
  Running setup.py bdist_wheel for protocoin ... done
  Stored in directory: /root/.cache/pip/wheels/df/46/25/01df6cf56cb21713c67710c75964fed3d73fd8d7dcba4a6924
  Running setup.py bdist_wheel for blockstack-profiles ... done
  Stored in directory: /root/.cache/pip/wheels/00/84/bd/611328585bbcf83631b2f054d682db04a9ce43d2c34a5f5928
  Running setup.py bdist_wheel for blockstack-zones ... done
  Stored in directory: /root/.cache/pip/wheels/5f/f5/99/d47fa1e90af1603470e1b4810fb9eb2982dc5c506902e386f1
  Running setup.py bdist_wheel for keylib ... done
  Stored in directory: /root/.cache/pip/wheels/4b/c9/e8/bedd7ba162a82ba999bf40ee2ecb781574a3b29b0dc49e04a9
  Running setup.py bdist_wheel for simplejson ... done
  Stored in directory: /root/.cache/pip/wheels/bf/0a/27/5d5e337ed16a175fd483a8c1486b4343ea2632be7ac57bad5d
  Running setup.py bdist_wheel for jsontokens ... done
  Stored in directory: /root/.cache/pip/wheels/d6/f4/6b/d08ce25cef13c929eaaef6d03b7cd737a8db33a3bea6be6a2a
  Running setup.py bdist_wheel for scrypt ... done
  Stored in directory: /root/.cache/pip/wheels/b5/c3/ce/7657994854be4cc96ca64c33d24685b0d28a9b7f8c0f105590
  Running setup.py bdist_wheel for onedrivesdk ... done
  Stored in directory: /root/.cache/pip/wheels/c5/29/8a/972d3bacb2e134f9d4c106a1f9338adba21f1395127bd73bf6
  Running setup.py bdist_wheel for warlock ... done
  Stored in directory: /root/.cache/pip/wheels/30/fb/b4/9e2241eab889a3b8964b9f2b7cad077bb775cb574c1fdecc01
  Running setup.py bdist_wheel for functools32 ... done
  Stored in directory: /root/.cache/pip/wheels/3c/d0/09/cd78d0ff4d6cfecfbd730782a7815a4571cd2cd4d2ed6e69d9
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /root/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for httplib2 ... done
  Stored in directory: /root/.cache/pip/wheels/ca/ac/5f/749651f7925b231103f5316cacca82a487810c22d30f011c0c
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /root/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
Successfully built blockstack virtualchain keychain protocoin blockstack-profiles blockstack-zones keylib simplejson jsontokens scrypt onedrivesdk warlock functools32 PyYAML httplib2 pycparser
Installing collected packages: protocoin, simplejson, functools32, jsonschema, six, pycparser, cffi, idna, asn1crypto, ipaddress, cryptography, keylib, virtualchain, keychain, jsontokens, blockstack-zones, jsonpointer, jsonpatch, warlock, blockstack-profiles, defusedxml, scrypt, boto, urllib3, chardet, certifi, requests, dropbox, PyYAML, uritemplate, pyasn1, rsa, httplib2, pyasn1-modules, oauth2client, google-api-python-client, pydrive, onedrivesdk, blockstack, cachetools, base58
  Found existing installation: protocoin 0.1
    Uninstalling protocoin-0.1:
      Successfully uninstalled protocoin-0.1
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: pycparser 2.14
    DEPRECATION: Uninstalling a distutils installed project (pycparser) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pycparser-2.14:
      Successfully uninstalled pycparser-2.14
  Found existing installation: cffi 1.6.0
    Uninstalling cffi-1.6.0:
      Successfully uninstalled cffi-1.6.0
  Found existing installation: idna 2.1
    Uninstalling idna-2.1:
      Successfully uninstalled idna-2.1
  Found existing installation: ipaddress 1.0.16
    Uninstalling ipaddress-1.0.16:
      Successfully uninstalled ipaddress-1.0.16
  Found existing installation: cryptography 1.3.2
    Uninstalling cryptography-1.3.2:
      Successfully uninstalled cryptography-1.3.2
  Found existing installation: keylib 0.0.4
    Uninstalling keylib-0.0.4:
      Successfully uninstalled keylib-0.0.4
  Found existing installation: virtualchain 0.0.6
    Uninstalling virtualchain-0.0.6:
      Successfully uninstalled virtualchain-0.0.6
  Found existing installation: keychain 0.1.4
    Uninstalling keychain-0.1.4:
      Successfully uninstalled keychain-0.1.4
  Found existing installation: jsontokens 0.0.2
    Uninstalling jsontokens-0.0.2:
      Successfully uninstalled jsontokens-0.0.2
  Found existing installation: scrypt 0.7.1
    Uninstalling scrypt-0.7.1:
      Successfully uninstalled scrypt-0.7.1
  Found existing installation: boto 2.38.0
    Uninstalling boto-2.38.0:
      Successfully uninstalled boto-2.38.0
  Found existing installation: urllib3 1.13.1
    Uninstalling urllib3-1.13.1:
      Successfully uninstalled urllib3-1.13.1
  Found existing installation: chardet 2.3.0
    Uninstalling chardet-2.3.0:
      Successfully uninstalled chardet-2.3.0
  Found existing installation: requests 2.4.3
    Uninstalling requests-2.4.3:
      Successfully uninstalled requests-2.4.3
  Found existing installation: pyasn1 0.1.9
    Uninstalling pyasn1-0.1.9:
      Successfully uninstalled pyasn1-0.1.9
  Found existing installation: cachetools 1.1.6
    Uninstalling cachetools-1.1.6:
      Successfully uninstalled cachetools-1.1.6
  Found existing installation: base58 0.2.2
    Uninstalling base58-0.2.2:
      Successfully uninstalled base58-0.2.2
Successfully installed PyYAML-3.12 asn1crypto-0.23.0 base58-0.2.5 blockstack-0.17.0.9 blockstack-profiles-0.14.1 blockstack-zones-0.14.3 boto-2.48.0 cachetools-2.0.1 certifi-2017.7.27.1 cffi-1.11.2 chardet-3.0.4 cryptography-2.1.1 defusedxml-0.5.0 dropbox-8.4.0 functools32-3.2.3.post2 google-api-python-client-1.6.4 httplib2-0.10.3 idna-2.6 ipaddress-1.0.18 jsonpatch-1.16 jsonpointer-1.12 jsonschema-2.6.0 jsontokens-0.0.4 keychain-0.14.2.0 keylib-0.1.1 oauth2client-4.1.2 onedrivesdk-1.1.8 protocoin-0.2 pyasn1-0.3.7 pyasn1-modules-0.1.5 pycparser-2.18 pydrive-1.3.1 requests-2.18.4 rsa-3.4.2 scrypt-0.8.0 simplejson-3.11.1 six-1.11.0 uritemplate-3.0.0 urllib3-1.22 virtualchain-0.17.0.4 warlock-1.3.0
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@blockstack:~# blockstack-core --debug start
Traceback (most recent call last):
  File "/usr/local/bin/blockstack-core", line 39, in <module>
    from blockstack.blockstackd import run_blockstackd
  File "/usr/local/lib/python2.7/dist-packages/blockstack/__init__.py", line 24, in <module>
    from .lib import *
  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/__init__.py", line 24, in <module>
    from .atlas import *
  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/atlas.py", line 37, in <module>
    import virtualchain
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/__init__.py", line 23, in <module>
    from virtualchain import setup_virtualchain, sync_virtualchain, virtualchain_set_opfields, connect_bitcoind
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/virtualchain.py", line 27, in <module>
    from .lib import config, indexer
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/__init__.py", line 30, in <module>
    import blockchain
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/__init__.py", line 24, in <module>
    import transactions 
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/transactions.py", line 24, in <module>
    from bitcoin_blockchain import BlockchainDownloader, SPVClient
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/__init__.py", line 24, in <module>
    from .keys import BitcoinPublicKey, BitcoinPrivateKey, hex_hash160_to_address, script_hex_to_address, version_byte, is_multisig_script, \
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/keys.py", line 27, in <module>
    import jsonschema
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/__init__.py", line 18, in <module>
    from jsonschema.validators import (
  File "/usr/local/lib/python2.7/dist-packages/jsonschema/validators.py", line 8, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
root@blockstack:~# 
```

**Comment by larrysalibra** [comment]
I tried the pip install again with a clean install of Ubuntu 16.04.3 LTS it worked without problem. I must have had some broken ssl libraries on the old machine.

**Comment by paradigma-cl** [comment]
Just in case, the problem was solved reinstalling pyopenssl to newer version
You need to reinstall the pip package.

pip uninstall pyOpenSSL
pip install pyOpenSSL==17.3.0
