### ISSUE TITLE
sync issues

### ISSUE THREAD

**Issue by pip010** [blockstack/blockstack-core#670]
(1) blockstack-core --debug fast_sync http://fast-sync.blockstack.org/snapshot.bsk

(2) tail -f ~/.blockstack-server/blockstack-server.log

<code>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockstack/blockstackd.py", line 2508, in run_server
    running = index_blockchain(expected_snapshots=expected_snapshots)
  File "/usr/local/lib/python2.7/dist-packages/blockstack/blockstackd.py", line 2352, in index_blockchain
    start_block, current_block = get_index_range()
  File "/usr/local/lib/python2.7/dist-packages/blockstack/blockstackd.py", line 183, in get_index_range
    assert bitcoind_session is not None
AssertionError
[2017-11-02 09:46:10,586] [DEBUG] [atlas:3125] (10348.139695885379328) Peer 176.9.147.41:6264 has a stale zonefile inventory
[2017-11-02 09:46:10,586] [ERROR] [blockstackd:2511] (10348.139696123528960) FATAL: caught exception while indexing
</code>

**Comment by jackzampolin** [comment]
It looks like this issue was with connecting to the `bitcoind` node specified in your `~/.blockstack-server/blockstack-server.ini`.

I've personally synced a number of `blockstack-core` nodes since this issue report and haven't run into the issue. Please reopen if you continue to see problems here.
