### ISSUE TITLE
new docker install fails with "error": "Failed to start API endpoint (exit code 1)"

### ISSUE THREAD

**Issue by aliencam** [blockstack/blockstack-core#671]
Using the docker "launcher" script to set up blockstack-core fails with an error on my Arch Linux system

Steps taken to install: 
download the docker launcher script from  https://raw.githubusercontent.com/blockstack/packaging/master/browser-core-docker/launcher 
`chmod +x ./launcher`
`./launcher pull`  
(everything in the pull succeeds with Status: Image is up to date for quay.io/blockstack/blockstack-core:latest ) 
`./launcher start`
asks for a password, then after password is entered hangs with:
```
[2017-11-03 01:57:27,258] [DEBUG] [rpc:5355] (33.140715831277312) Running in the background
  [2017-11-03 01:58:12,486] [ERROR] [utils:171] (33.140715831277312) Child exit status 256
  [2017-11-03 01:58:12,486] [ERROR] [rpc:5362] (33.140715831277312) API server failed to start
  
{
    "error": "Failed to start API endpoint (exit code 1)"
}
Failed to start Blockstack daemon -- is your password correct?
stopping the running blockstack-api container
````
since this is the same time I have created the blockstack wallet, yes the password is correct. 

I have tried starting from scratch by deleting the docker containers with 
`docker ps -a`
`docker rm [container_names]`
and removing the folder at /user/.blockstack

but setting up new client folders does not fix the problem. 

Here is the full error log:

```
./blockstack-launcher start


Please enter a password to protect your Blockstack core node.
IMPORTANT: This will be used to encrypt information stored within the containers
           which may include private keys for your Blockstack wallet.
           It is important that you remember this password.
           This will be the password you use to "pair" your Blockstack Browser
           with your Blockstack core node.

           Legal characters:
               letters (upper and lowercase), numbers, '_', and '-'

Password: 
Repeat: 
Wallet does not exist yet. Setting up wallet
Saving configuration to /root/.blockstack/client.ini
Wallet is encrypted using your password and stored  at "/root/.blockstack/wallet.json", please make sure you create a backup.
{
    "status": true
}
Set BLOCKSTACK_DEBUG to 1
Re-exec as `"/usr/bin/python", "/usr/local/bin/blockstack", "api", "start", "--secrets", "3"`
[2017-11-03 01:57:21,956] [DEBUG] [spv:103] (11.140460213643008) Using mainnet
[2017-11-03 01:57:22,054] [DEBUG] [cli:419] (11.140460213643008) Load secrets from 3
[2017-11-03 01:57:22,099] [DEBUG] [client:95] (11.140460213643008) Connect to https://node.blockstack.org:6263
[2017-11-03 01:57:22,103] [WARNING] [storage:632] (11.140460213643008) Storage implementation is missing a "get_immutable_handler" method
[2017-11-03 01:57:22,105] [WARNING] [storage:632] (11.140460213643008) Storage implementation is missing a "put_immutable_handler" method
[2017-11-03 01:57:22,106] [WARNING] [storage:632] (11.140460213643008) Storage implementation is missing a "delete_immutable_handler" method
[2017-11-03 01:57:22,108] [WARNING] [storage:632] (11.140460213643008) Storage implementation is missing a "delete_mutable_handler" method
[2017-11-03 01:57:22,252] [WARNING] [dropbox:188] (11) Config file '/root/.blockstack/client.ini': section 'dropbox' is missing 'token'.  Write access will be disabled
[2017-11-03 01:57:22,253] [DEBUG] [client:110] (11.140460213643008) Loaded storage drivers ['disk', 'gaia_hub', 'dropbox', 's3', 'blockstack_resolver', 'http', 'dht']
[2017-11-03 01:58:12,514] [ERROR] [rpc:5078] (11.140460213643008) Failed to start API endpoint: exit code 1
[2017-11-03 01:58:12,517] [ERROR] [rpc:5079] (11.140460213643008) Error log:
  [2017-11-03 01:57:22,577] [DEBUG] [spv:103] (33.140715831277312) Using mainnet
  [2017-11-03 01:57:23,281] [INFO] [rpc:5294] (33.140715831277312) API server version 0.17.0 starting...
  [2017-11-03 01:57:23,281] [INFO] [rpc:5295] (33.140715831277312) Machine:   x86_64
  [2017-11-03 01:57:23,281] [INFO] [rpc:5296] (33.140715831277312) Version:   #1 SMP PREEMPT Fri Oct 27 16:16:03 CEST 2017
  [2017-11-03 01:57:23,281] [INFO] [rpc:5297] (33.140715831277312) Platform:  Linux-4.13.10-1-ARCH-x86_64-with-Ubuntu-16.04-xenial
  [2017-11-03 01:57:23,281] [INFO] [rpc:5298] (33.140715831277312) uname:     Linux 8db3872fc579 4.13.10-1-ARCH #1 SMP PREEMPT Fri Oct 27 16:16:03 CEST 2017 x86_64 x86_64
  [2017-11-03 01:57:23,281] [INFO] [rpc:5299] (33.140715831277312) System:    Linux
  [2017-11-03 01:57:23,282] [INFO] [rpc:5300] (33.140715831277312) Processor: x86_64
  [2017-11-03 01:57:23,282] [INFO] [rpc:5301] (33.140715831277312) pip:
  asn1crypto==0.23.0
  base58==0.2.5
  basicrpc==0.0.2
  bitmerchant==0.1.8
  blockstack==0.17.0.11
  blockstack-profiles==0.14.1
  blockstack-zones==0.14.3
  boto==2.48.0
  cachetools==2.0.1
  certifi==2017.7.27.1
  cffi==1.11.2
  chardet==3.0.4
  cryptography==2.1.2
  defusedxml==0.5.0
  dropbox==8.4.0
  ecdsa==0.13
  enum34==1.1.6
  functools32==3.2.3.post2
  google-api-python-client==1.6.4
  httplib2==0.10.3
  idna==2.6
  ipaddress==1.0.18
  jsonpatch==1.16
  jsonpointer==1.14
  jsonschema==2.6.0
  jsontokens==0.0.4
  keychain==0.14.2.0
  keylib==0.1.1
  oauth2client==4.1.2
  onedrivesdk==1.1.8
  protocoin==0.2
  pyasn1==0.3.7
  pyasn1-modules==0.1.5
  pycparser==2.18
  PyDrive==1.3.1
  pyparsing==2.2.0
  PyYAML==3.12
  requests==2.18.4
  rsa==3.4.2
  scrypt==0.8.0
  simplejson==3.11.1
  six==1.11.0
  uritemplate==3.0.0
  urllib3==1.22
  utilitybelt==0.2.6
  virtualchain==0.17.0.4
  warlock==1.3.0
  
  [2017-11-03 01:57:27,258] [DEBUG] [rpc:5355] (33.140715831277312) Running in the background
  [2017-11-03 01:58:12,486] [ERROR] [utils:171] (33.140715831277312) Child exit status 256
  [2017-11-03 01:58:12,486] [ERROR] [rpc:5362] (33.140715831277312) API server failed to start
  
{
    "error": "Failed to start API endpoint (exit code 1)"
}
Failed to start Blockstack daemon -- is your password correct?
stopping the running blockstack-api container
```

**Comment by kantai** [comment]
Sorry to see you're experiencing issues with the `launcher` script.

Does the failed start create a logfile `/home/user/api_endpoint.log` ?

**Comment by aliencam** [comment]
Yes, in the log it seems everything is fine until::

```
[2017-11-03 01:57:27,759] [DEBUG] [rpc:5396] (48.140715831277312) Initializing registrar...
[2017-11-03 01:57:27,760] [DEBUG] [registrar:107] (48.140715831277312) RegistrarWorker already initialized
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/rpc_runner.py", line 70, in <module>
    res = local_api_start(port=portnum, config_dir=config_dir, api_pass=api_pass, password=passwd)
  File "/usr/local/lib/python2.7/dist-packages/blockstack_client/rpc.py", line 5399, in local_api_start
    log.error("Failed to initialize registrar: {}".format(res['error']))
TypeError: 'int' object has no attribute '__getitem__'
[2017-11-03 01:57:27,783] [DEBUG] [rpc:5158] (48.140715831277312) Atexit handler invoked; shutting down
[2017-11-03 01:57:27,785] [DEBUG] [rpc:4971] (48.140715831277312) Server shutdown
[2017-11-03 01:57:28,278] [DEBUG] [rpc:5190] (33.140715831277312) Attempt 2 to ping API server
[2017-11-03 01:57:28,285] [DEBUG] [rpc:5010] (33.140715831277312) Connect to API at localhost:6270
[2017-11-03 01:57:28,289] [DEBUG] [rpc:5201] (33.140715831277312) API server is not responding; trying again in 2 seconds

... retrying pings cut for brevity...

[2017-11-03 01:58:12,446] [ERROR] [rpc:5219] (33.140715831277312) API endpoint did not initialize


```

**Comment by kantai** [comment]
Do you have a file

`/tmp/registrar.lock` ?

If so, try to delete it and re-start and see if that fixes the issue.

**Comment by aliencam** [comment]
There is not a  
`/tmp/registrar.lock` 
file on my host machine, and I can't check inside the docker containers since I am not able to start them.

**Comment by kantai** [comment]
Sorry -- I think the correct location is 

`/tmp/.blockstack_tmp/registrar.lock`

**Comment by aliencam** [comment]
oh yes, can't believe i missed that folder...
Removing the file did not work, but I followed it up by just installing blockstack through pip2 and blockstack-core seems to be working fine now. 

Thanks for your help
