### ISSUE TITLE
Regtest docker image: bad file descriptor

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#739]
My regtest docker image instance died with the following error:
```
[2018-02-09 19:14:09,080] [DEBUG] [indexer:376] (1.139840508729088) Rename 'snapshots': /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/blockstack-server.snapshots.tmp --> /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/blockstack-server.snapshots
[2018-02-09 19:14:09,107] [INFO] [indexer:555] (1.139840508729088) Removing old backup '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/backups/blockstack-server.db.bak.1007'
[2018-02-09 19:14:09,108] [INFO] [indexer:555] (1.139840508729088) Removing old backup '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/backups/blockstack-server.snapshots.bak.1007'
[2018-02-09 19:14:09,110] [INFO] [indexer:555] (1.139840508729088) Removing old backup '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/backups/blockstack-server.lastblock.bak.1007'
[2018-02-09 19:14:09,111] [DEBUG] [indexer:1154] (1.139840508729088) CONSENSUS(1038): a1a1c864fbce7f3b5bd2fcca0c291f37
[2018-02-09 19:14:09,111] [DEBUG] [indexer:1168] (1.139840508729088) Last block is 1038
[2018-02-09 19:14:09,111] [INFO] [virtualchain:69] (1.139840508729088) 0 seconds
[2018-02-09 19:14:09,117] [DEBUG] [namedb:92] (1.139840508729088) Connect to database '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/blockstack-server.db'
[2018-02-09 19:14:09,129] [DEBUG] [indexer:175] (1.139840508729088) consensus snapshots at '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/blockstack-server.snapshots'
[2018-02-09 19:14:09,133] [DEBUG] [indexer:210] (1.139840508729088) lastblock at '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/blockstack-server.lastblock'
[2018-02-09 19:14:09,137] [DEBUG] [indexer:213] (1.139840508729088) Lastblock: 1038 (/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/blockstack-server.lastblock)
[2018-02-09 19:14:09,160] [DEBUG] [blockstack-test-scenario:593] (1.139840508729088) sync atlas node up to 1038
[2018-02-09 19:14:09,160] [DEBUG] [blockstack-test-scenario:598] (1.139840508729088) Synchronize Atlas DB from 1038 to 1039
[2018-02-09 19:14:09,166] [DEBUG] [namedb:775] (1.139840508729088) Get all ops at 1038 in /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/blockstack-server.db
[2018-02-09 19:14:09,169] [DEBUG] [db:1914] (1.139840508729088) 0 name-preorder/import states at 1038
[2018-02-09 19:14:09,171] [DEBUG] [db:1969] (1.139840508729088) 0 name-change states at 1038
[2018-02-09 19:14:09,173] [DEBUG] [db:2015] (1.139840508729088) 0 preorders created at 1038
[2018-02-09 19:14:09,175] [DEBUG] [db:2059] (1.139840508729088) 0 namespace-preorder states at 1038
[2018-02-09 19:14:09,177] [DEBUG] [db:2107] (1.139840508729088) 0 namespace-change states at 1038
[2018-02-09 19:14:09,177] [DEBUG] [atlas:933] (1.139840508729088) Queued 0 zonefiles from 1038-1038
[2018-02-09 19:14:09,183] [DEBUG] [db:232] (1.139840508729088) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/blockstack-server.db .backup "/tmp/blockstack-test-databases-1xyc2G/blockstack.db.1038"
Traceback (most recent call last):
  File "/usr/local/bin/blockstack-test-scenario", line 1504, in <module>
    rc = run_scenario( scenario, config_file, client_config_file, interactive=interactive, blocktime=blocktime, webtest_port=webtest_port )
  File "/usr/local/bin/blockstack-test-scenario", line 843, in run_scenario
    testlib.next_block( **test_env )
  File "/usr/local/lib/python2.7/dist-packages/blockstack_integration_tests/scenarios/testlib.py", line 2861, in next_block
    blockstack_export_db( os.path.join( snapshots_dir, "blockstack.db" ), get_current_block(**kw), **kw )
  File "/usr/local/lib/python2.7/dist-packages/blockstack_integration_tests/scenarios/testlib.py", line 2475, in blockstack_export_db
    shutil.copy( atlas_path, os.path.join( os.path.dirname(path), "atlas.db.%s" % block_height ) )
  File "/usr/lib/python2.7/shutil.py", line 120, in copy
    copymode(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 89, in copymode
    st = os.stat(src)
OSError: [Errno 9] Bad file descriptor: '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.subdomain_registrar/atlas.db'
^C

```

**Comment by jackzampolin** [comment]
What command did you use to start the image? The same one from https://github.com/blockstack/blockstack-core/tree/master/integration_tests?

**Comment by larrysalibra** [comment]
The one from this pull request https://github.com/blockstack/blockstack-core/pull/737
```
IMAGE=$(docker run -dt -p 6270:6270 -p 7103:7103 -v /tmp:/tmp -e BLOCKSTACK_TEST_CLIENT_RPC_PORT=6270 -e BLOCKSTACK_TEST_CLIENT_BIND=0.0.0.0 -e BSK_SUBDOMAIN_REGTEST_BIND=0.0.0.0 quay.io/blockstack/integrationtests:develop blockstack-test-scenario --interactive 2 blockstack_integration_tests.scenarios.subdomain_registrar)
```

**Comment by yknl** [comment]
I've encountered this error a few times with the docker image. It seems to happen intermittently, usually doesn't happen again after restarting the container.

**Comment by jcnelson** [comment]
I think this could be because the code isn't using the `sqlite3 .backup` command to safely copy the Atlas database.  I'll patch this in the `develop` branch.

**Comment by jcnelson** [comment]
Closing as stale.
