### ISSUE TITLE
Regtest node disconnect

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#759]
I started the docker regtest instance with the following command

```
IMAGE=$(docker run -dt -p 6270:6270 -p 16269:16269 -p 18332:18332 -e BLOCKSTACK_TEST_CLIENT_RPC_PORT=6270 -e BLOCKSTACK_TEST_CLIENT_BIND=0.0.0.0 -e BLOCKSTACK_TEST_BITCOIND_ALLOWIP=0.0.0.0/0 quay.io/blockstack/integrationtests:master blockstack-test-scenario --interactive 2 blockstack_integration_tests.scenarios.browser_env)
```

Left it running for 45 minutes or so (didn't use it at all) and came back to this error message:

```
[2018-02-23 17:25:06,057] [DEBUG] [indexer:1400] (1.140507780290304) Sync virtualchain state from 1689 to 1690
[2018-02-23 17:25:06,057] [DEBUG] [spv:744] (1.140507780290304) Synchronize testnet 1689 to 1689
[2018-02-23 17:25:06,058] [DEBUG] [spv:767] (1.140507780290304) connect to localhost:18444
[2018-02-23 17:25:06,058] [DEBUG] [spv:368] (1.140507780290304) handshake (version 60002)
[2018-02-23 17:25:06,059] [DEBUG] [spv:371] (1.140507780290304) send Version
[2018-02-23 17:25:06,059] [DEBUG] [spv:384] (1.140507780290304) handle version
[2018-02-23 17:25:06,059] [DEBUG] [spv:386] (1.140507780290304) send VerAck
[2018-02-23 17:25:06,060] [DEBUG] [spv:358] (1.140507780290304) send getheaders
[2018-02-23 17:25:06,479] [DEBUG] [spv:403] (1.140507780290304) handle ping
[2018-02-23 17:25:06,479] [DEBUG] [spv:406] (1.140507780290304) send pong
[2018-02-23 17:25:06,792] [DEBUG] [spv:250] (1.140507780290304) handle headers (1)
[2018-02-23 17:25:06,792] [DEBUG] [spv:268] (1.140507780290304) Receive 1 headers (1688 to 1689)
[2018-02-23 17:25:06,793] [DEBUG] [spv:785] (1.140507780290304) synced headers from 1688 to 1689 in /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/spv_headers.dat
[2018-02-23 17:25:06,793] [DEBUG] [blocks:125] (1.140507780290304) BlockDownloader: fetch blocks 1689-1689
[2018-02-23 17:25:06,794] [DEBUG] [blocks:173] (1.140507780290304) Segwit support: False
[2018-02-23 17:25:06,794] [DEBUG] [blocks:313] (1.140507780290304) handshake (version 60002)
[2018-02-23 17:25:06,794] [DEBUG] [blocks:316] (1.140507780290304) send Version
[2018-02-23 17:25:06,795] [DEBUG] [blocks:329] (1.140507780290304) handle version
[2018-02-23 17:25:06,795] [DEBUG] [blocks:331] (1.140507780290304) send VerAck
[2018-02-23 17:25:06,795] [DEBUG] [blocks:347] (1.140507780290304) send getdata for 1689-1689 (0b7d06371fb055ec6d6730e7cff2d5ad1694157b61ca86366d3c21b4265bca38-0b7d06371fb055ec6d6730e7cff2d5ad1694157b61ca86366d3c21b4265bca38)
[2018-02-23 17:25:07,003] [DEBUG] [blocks:372] (1.140507780290304) handle ping
[2018-02-23 17:25:07,003] [DEBUG] [blocks:375] (1.140507780290304) send pong
[2018-02-23 17:25:07,322] [DEBUG] [blocks:207] (1.140507780290304) num blocks received = 0, num requested = 1
[2018-02-23 17:25:07,322] [DEBUG] [blocks:544] (1.140507780290304) handle block 1689 (0b7d06371fb055ec6d6730e7cff2d5ad1694157b61ca86366d3c21b4265bca38)
[2018-02-23 17:25:07,325] [DEBUG] [blocks:657] (1.140507780290304) Request 0 nulldata sender TXs
[2018-02-23 17:25:07,326] [DEBUG] [indexer:1340] (1.140507780290304) Process block 1689 (0 virtual transactions)
[2018-02-23 17:25:07,326] [DEBUG] [virtualchain_hooks:292] (1.140507780290304) SCAN BEGIN: 0 ops at block 1689
[2018-02-23 17:25:07,327] [DEBUG] [virtualchain_hooks:318] (1.140507780290304) SCAN END: 0 ops at block 1689 (0 collisions)
[2018-02-23 17:25:07,327] [DEBUG] [indexer:1063] (1.140507780290304) Snapshotting block 1689
[2018-02-23 17:25:07,327] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1689: consensus hash of 1688 is cb33c1f0f2bf504905e2da57baa7e00b
[2018-02-23 17:25:07,328] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1689: consensus hash of 1686 is 85ed30ae3c965c4aa6d3034a66e96775
[2018-02-23 17:25:07,329] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1689: consensus hash of 1682 is c8501691fde53d6e78e18625b9f94ee5
[2018-02-23 17:25:07,329] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1689: consensus hash of 1674 is 3be584ffb277fe0811688250670c035f
[2018-02-23 17:25:07,330] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1689: consensus hash of 1658 is ec92df457856b994fb29bc4aa2d10706
[2018-02-23 17:25:07,330] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1689: consensus hash of 1626 is 7ad042197a67b06483fa938a6a13241c
[2018-02-23 17:25:07,331] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1689: consensus hash of 1562 is 5e42a937bb8b1772afdc69b8e91d79e8
[2018-02-23 17:25:07,332] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1689: consensus hash of 1434 is 2713e3a9f1897d48da6fc08493b64213
[2018-02-23 17:25:07,332] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1689: consensus hash of 1178 is 6d605de0986cf205e46f732f74b6738e
[2018-02-23 17:25:07,332] [DEBUG] [indexer:980] (1.140507780290304) Snapshot('5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456', [u'cb33c1f0f2bf504905e2da57baa7e00b', u'85ed30ae3c965c4aa6d3034a66e96775', u'c8501691fde53d6e78e18625b9f94ee5', u'3be584ffb277fe0811688250670c035f', u'ec92df457856b994fb29bc4aa2d10706', u'7ad042197a67b06483fa938a6a13241c', u'5e42a937bb8b1772afdc69b8e91d79e8', u'2713e3a9f1897d48da6fc08493b64213', u'6d605de0986cf205e46f732f74b6738e'])
[2018-02-23 17:25:07,333] [DEBUG] [virtualchain_hooks:497] (1.140507780290304) Synchronize Atlas DB for 1689
[2018-02-23 17:25:07,349] [DEBUG] [namedb:865] (1.140507780290304) Get all ops at 1689 in /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db
[2018-02-23 17:25:07,350] [DEBUG] [db:1862] (1.140507780290304) 0 preorders created at 1689
[2018-02-23 17:25:07,350] [DEBUG] [db:1896] (1.140507780290304) 0 non-preorder operations at 1689
[2018-02-23 17:25:07,350] [DEBUG] [atlas:994] (1.140507780290304) Queued 0 zonefiles from 1689-1688
[2018-02-23 17:25:07,364] [DEBUG] [virtualchain_hooks:527] (1.140507780290304) Synchronize subdomain index for 1689
[2018-02-23 17:25:07,380] [DEBUG] [subdomains:925] (1.140507780290304) BEGIN Processing zonefiles discovered since last re-indexing
[2018-02-23 17:25:07,380] [DEBUG] [subdomains:861] (1.140507780290304) Discovered 0 zonefiles
[2018-02-23 17:25:07,381] [DEBUG] [subdomains:927] (1.140507780290304) END Processing zonefiles discovered since last re-indexing
[2018-02-23 17:25:07,393] [DEBUG] [indexer:369] (1.140507780290304) CHAINSTATE: INSERT INTO snapshots (block_id,consensus_hash,ops_hash,timestamp) VALUES ( 1689, '59d063fc8ea228b01df6fe18a02c7af5', '5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456', 1519406707); ''
[2018-02-23 17:25:07,400] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db .backup "/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/blockstack-server.db.bak.1688"
[2018-02-23 17:25:07,541] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.snapshots .backup "/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/blockstack-server.snapshots.bak.1688"
[2018-02-23 17:25:07,665] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/atlas.db .backup "/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/atlas.db.bak.1688"
[2018-02-23 17:25:07,786] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/subdomains.db .backup "/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/subdomains.db.bak.1688"
[2018-02-23 17:25:07,907] [INFO] [indexer:816] (1.140507780290304) Removing old backup '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/blockstack-server.db.bak.1658'
[2018-02-23 17:25:07,907] [INFO] [indexer:816] (1.140507780290304) Removing old backup '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/atlas.db.bak.1658'
[2018-02-23 17:25:07,907] [INFO] [indexer:816] (1.140507780290304) Removing old backup '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/blockstack-server.snapshots.bak.1658'
[2018-02-23 17:25:07,908] [INFO] [indexer:816] (1.140507780290304) Removing old backup '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/subdomains.db.bak.1658'
[2018-02-23 17:25:07,908] [DEBUG] [indexer:1434] (1.140507780290304) CONSENSUS(1689): 59d063fc8ea228b01df6fe18a02c7af5
[2018-02-23 17:25:07,908] [DEBUG] [indexer:1448] (1.140507780290304) Last block is 1689
[2018-02-23 17:25:07,909] [INFO] [virtualchain:62] (1.140507780290304) 1 seconds
[2018-02-23 17:25:07,909] [DEBUG] [blockstackd:2094] (1.140507780290304) End indexing (up to 1689)
[2018-02-23 17:25:07,909] [WARNING] [namedb:153] (1.140507780290304) !!! Getting raw read/write DB instance !!!
[2018-02-23 17:25:07,909] [DEBUG] [namedb:91] (1.140507780290304) Connect to database '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db'
[2018-02-23 17:25:07,911] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db .backup "/tmp/blockstack-test-databases-ZiwUIs/snapshot.1689/blockstack-server.db"
[2018-02-23 17:25:08,035] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.snapshots .backup "/tmp/blockstack-test-databases-ZiwUIs/snapshot.1689/blockstack-server.snapshots"
[2018-02-23 17:25:08,160] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/atlas.db .backup "/tmp/blockstack-test-databases-ZiwUIs/snapshot.1689/atlas.db"
[2018-02-23 17:25:08,287] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/subdomains.db .backup "/tmp/blockstack-test-databases-ZiwUIs/snapshot.1689/subdomains.db"
[2018-02-23 17:25:08,430] [WARNING] [namedb:153] (1.140507780290304) !!! Getting raw read/write DB instance !!!
[2018-02-23 17:25:08,430] [DEBUG] [namedb:91] (1.140507780290304) Connect to database '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db'
[2018-02-23 17:25:10,436] [DEBUG] [session:104] (1.140507780290304) [1] Connect to bitcoind at http://blockstack@localhost:18332, timeout=60.0
[2018-02-23 17:25:10,457] [DEBUG] [blockstack-test-scenario:1079] (1.140507780290304) next block (now at 1690)
[2018-02-23 17:25:10,458] [WARNING] [namedb:153] (1.140507780290304) !!! Getting raw read/write DB instance !!!
[2018-02-23 17:25:10,458] [DEBUG] [namedb:91] (1.140507780290304) Connect to database '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db'
[2018-02-23 17:25:10,459] [DEBUG] [blockstackd:2055] (1.140507780290304) index blockchain in /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env
[2018-02-23 17:25:10,459] [DEBUG] [session:104] (1.140507780290304) [1] Connect to bitcoind at http://blockstack@localhost:18332, timeout=300.0
[2018-02-23 17:25:10,461] [DEBUG] [namedb:91] (1.140507780290304) Connect to database '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db'
[2018-02-23 17:25:10,462] [DEBUG] [blockstackd:2080] (1.140507780290304) Begin indexing (up to 1690)
[2018-02-23 17:25:10,462] [INFO] [virtualchain_hooks:577] (1.140507780290304) Synchronizing database /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env up to block 1690
[2018-02-23 17:25:10,462] [DEBUG] [namedb:91] (1.140507780290304) Connect to database '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db'
[2018-02-23 17:25:10,463] [DEBUG] [indexer:1400] (1.140507780290304) Sync virtualchain state from 1690 to 1691
[2018-02-23 17:25:10,463] [DEBUG] [spv:744] (1.140507780290304) Synchronize testnet 1690 to 1690
[2018-02-23 17:25:10,464] [DEBUG] [spv:767] (1.140507780290304) connect to localhost:18444
[2018-02-23 17:25:10,464] [DEBUG] [spv:368] (1.140507780290304) handshake (version 60002)
[2018-02-23 17:25:10,464] [DEBUG] [spv:371] (1.140507780290304) send Version
[2018-02-23 17:25:10,465] [DEBUG] [spv:384] (1.140507780290304) handle version
[2018-02-23 17:25:10,465] [DEBUG] [spv:386] (1.140507780290304) send VerAck
[2018-02-23 17:25:10,465] [DEBUG] [spv:358] (1.140507780290304) send getheaders
[2018-02-23 17:25:10,883] [DEBUG] [spv:403] (1.140507780290304) handle ping
[2018-02-23 17:25:10,883] [DEBUG] [spv:406] (1.140507780290304) send pong
[2018-02-23 17:25:11,089] [DEBUG] [spv:250] (1.140507780290304) handle headers (1)
[2018-02-23 17:25:11,090] [DEBUG] [spv:268] (1.140507780290304) Receive 1 headers (1689 to 1690)
[2018-02-23 17:25:11,091] [DEBUG] [spv:785] (1.140507780290304) synced headers from 1689 to 1690 in /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/spv_headers.dat
[2018-02-23 17:25:11,092] [DEBUG] [blocks:125] (1.140507780290304) BlockDownloader: fetch blocks 1690-1690
[2018-02-23 17:25:11,093] [DEBUG] [blocks:173] (1.140507780290304) Segwit support: False
[2018-02-23 17:25:11,093] [DEBUG] [blocks:313] (1.140507780290304) handshake (version 60002)
[2018-02-23 17:25:11,093] [DEBUG] [blocks:316] (1.140507780290304) send Version
[2018-02-23 17:25:11,094] [DEBUG] [blocks:329] (1.140507780290304) handle version
[2018-02-23 17:25:11,094] [DEBUG] [blocks:331] (1.140507780290304) send VerAck
[2018-02-23 17:25:11,094] [DEBUG] [blocks:347] (1.140507780290304) send getdata for 1690-1690 (0a90d9e6a52dbbd60b23e2bcf3d72dc594a4806fd978373d7e6c750b9013abca-0a90d9e6a52dbbd60b23e2bcf3d72dc594a4806fd978373d7e6c750b9013abca)
[2018-02-23 17:25:11,616] [DEBUG] [blocks:372] (1.140507780290304) handle ping
[2018-02-23 17:25:11,616] [DEBUG] [blocks:375] (1.140507780290304) send pong
[2018-02-23 17:25:11,928] [DEBUG] [blocks:207] (1.140507780290304) num blocks received = 0, num requested = 1
[2018-02-23 17:25:11,928] [DEBUG] [blocks:544] (1.140507780290304) handle block 1690 (0a90d9e6a52dbbd60b23e2bcf3d72dc594a4806fd978373d7e6c750b9013abca)
[2018-02-23 17:25:11,929] [DEBUG] [blocks:657] (1.140507780290304) Request 0 nulldata sender TXs
[2018-02-23 17:25:11,929] [DEBUG] [indexer:1340] (1.140507780290304) Process block 1690 (0 virtual transactions)
[2018-02-23 17:25:11,930] [DEBUG] [virtualchain_hooks:292] (1.140507780290304) SCAN BEGIN: 0 ops at block 1690
[2018-02-23 17:25:11,930] [DEBUG] [virtualchain_hooks:318] (1.140507780290304) SCAN END: 0 ops at block 1690 (0 collisions)
[2018-02-23 17:25:11,930] [DEBUG] [indexer:1063] (1.140507780290304) Snapshotting block 1690
[2018-02-23 17:25:11,930] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1690: consensus hash of 1689 is 59d063fc8ea228b01df6fe18a02c7af5
[2018-02-23 17:25:11,931] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1690: consensus hash of 1687 is b2d9de9c0ae60a1368321015b4f4b3b9
[2018-02-23 17:25:11,931] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1690: consensus hash of 1683 is 3e4801abda49d74f6c206afd5387f27b
[2018-02-23 17:25:11,931] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1690: consensus hash of 1675 is 61a66f7f0e571546602ad9f3bdca0493
[2018-02-23 17:25:11,932] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1690: consensus hash of 1659 is 7292e7f1b0219048c1f741375ede39d5
[2018-02-23 17:25:11,932] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1690: consensus hash of 1627 is 9aa7f1b6f1299a40c4c0df009f93380a
[2018-02-23 17:25:11,932] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1690: consensus hash of 1563 is 244558fa319207571f668c48fd53f65e
[2018-02-23 17:25:11,933] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1690: consensus hash of 1435 is ca140d105981a3f1a2aa4a7578b32942
[2018-02-23 17:25:11,933] [DEBUG] [indexer:1076] (1.140507780290304) Snapshotting block 1690: consensus hash of 1179 is d1aaa464ba56859d5c6067f017d583e9
[2018-02-23 17:25:11,933] [DEBUG] [indexer:980] (1.140507780290304) Snapshot('5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456', [u'59d063fc8ea228b01df6fe18a02c7af5', u'b2d9de9c0ae60a1368321015b4f4b3b9', u'3e4801abda49d74f6c206afd5387f27b', u'61a66f7f0e571546602ad9f3bdca0493', u'7292e7f1b0219048c1f741375ede39d5', u'9aa7f1b6f1299a40c4c0df009f93380a', u'244558fa319207571f668c48fd53f65e', u'ca140d105981a3f1a2aa4a7578b32942', u'd1aaa464ba56859d5c6067f017d583e9'])
[2018-02-23 17:25:11,933] [DEBUG] [virtualchain_hooks:497] (1.140507780290304) Synchronize Atlas DB for 1690
[2018-02-23 17:25:11,950] [DEBUG] [namedb:865] (1.140507780290304) Get all ops at 1690 in /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db
[2018-02-23 17:25:11,951] [DEBUG] [db:1862] (1.140507780290304) 0 preorders created at 1690
[2018-02-23 17:25:11,951] [DEBUG] [db:1896] (1.140507780290304) 0 non-preorder operations at 1690
[2018-02-23 17:25:11,951] [DEBUG] [atlas:994] (1.140507780290304) Queued 0 zonefiles from 1690-1689
[2018-02-23 17:25:11,967] [DEBUG] [virtualchain_hooks:527] (1.140507780290304) Synchronize subdomain index for 1690
[2018-02-23 17:25:11,986] [DEBUG] [subdomains:925] (1.140507780290304) BEGIN Processing zonefiles discovered since last re-indexing
[2018-02-23 17:25:11,987] [DEBUG] [subdomains:861] (1.140507780290304) Discovered 0 zonefiles
[2018-02-23 17:25:11,987] [DEBUG] [subdomains:927] (1.140507780290304) END Processing zonefiles discovered since last re-indexing
[2018-02-23 17:25:12,003] [DEBUG] [indexer:369] (1.140507780290304) CHAINSTATE: INSERT INTO snapshots (block_id,consensus_hash,ops_hash,timestamp) VALUES ( 1690, 'd7d305cb25e831ba7e7b84033584b0d5', '5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456', 1519406712); ''
[2018-02-23 17:25:12,011] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db .backup "/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/blockstack-server.db.bak.1689"
[2018-02-23 17:25:12,195] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.snapshots .backup "/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/blockstack-server.snapshots.bak.1689"
[2018-02-23 17:25:12,414] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/atlas.db .backup "/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/atlas.db.bak.1689"
[2018-02-23 17:25:12,560] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/subdomains.db .backup "/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/subdomains.db.bak.1689"
[2018-02-23 17:25:12,692] [INFO] [indexer:816] (1.140507780290304) Removing old backup '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/blockstack-server.db.bak.1659'
[2018-02-23 17:25:12,692] [INFO] [indexer:816] (1.140507780290304) Removing old backup '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/blockstack-server.snapshots.bak.1659'
[2018-02-23 17:25:12,692] [INFO] [indexer:816] (1.140507780290304) Removing old backup '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/atlas.db.bak.1659'
[2018-02-23 17:25:12,693] [INFO] [indexer:816] (1.140507780290304) Removing old backup '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/backups/subdomains.db.bak.1659'
[2018-02-23 17:25:12,693] [DEBUG] [indexer:1434] (1.140507780290304) CONSENSUS(1690): d7d305cb25e831ba7e7b84033584b0d5
[2018-02-23 17:25:12,694] [DEBUG] [indexer:1448] (1.140507780290304) Last block is 1690
[2018-02-23 17:25:12,694] [INFO] [virtualchain:62] (1.140507780290304) 2 seconds
[2018-02-23 17:25:12,694] [DEBUG] [blockstackd:2094] (1.140507780290304) End indexing (up to 1690)
[2018-02-23 17:25:12,694] [WARNING] [namedb:153] (1.140507780290304) !!! Getting raw read/write DB instance !!!
[2018-02-23 17:25:12,695] [DEBUG] [namedb:91] (1.140507780290304) Connect to database '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db'
[2018-02-23 17:25:12,696] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db .backup "/tmp/blockstack-test-databases-ZiwUIs/snapshot.1690/blockstack-server.db"
[2018-02-23 17:25:12,821] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.snapshots .backup "/tmp/blockstack-test-databases-ZiwUIs/snapshot.1690/blockstack-server.snapshots"
[2018-02-23 17:25:12,945] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/atlas.db .backup "/tmp/blockstack-test-databases-ZiwUIs/snapshot.1690/atlas.db"
[2018-02-23 17:25:13,070] [DEBUG] [indexer:1666] (1.140507780290304) /usr/bin/sqlite3 /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/subdomains.db .backup "/tmp/blockstack-test-databases-ZiwUIs/snapshot.1690/subdomains.db"
[2018-02-23 17:25:13,196] [WARNING] [namedb:153] (1.140507780290304) !!! Getting raw read/write DB instance !!!
[2018-02-23 17:25:13,196] [DEBUG] [namedb:91] (1.140507780290304) Connect to database '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db'
[2018-02-23 17:31:21,904] [DEBUG] [session:104] (1.140507780290304) [1] Connect to bitcoind at http://blockstack@localhost:18332, timeout=60.0
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/bin/blockstack-test-scenario", line 160, in run
    bitcoind.ping()
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 143, in __call__
    response = self._get_response()
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/authproxy.py", line 185, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

[2018-02-23 17:31:21,979] [DEBUG] [blockstack-test-scenario:1079] (1.140507780290304) next block (now at 1691)
[2018-02-23 17:31:21,980] [WARNING] [namedb:153] (1.140507780290304) !!! Getting raw read/write DB instance !!!
[2018-02-23 17:31:21,981] [DEBUG] [namedb:91] (1.140507780290304) Connect to database '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db'
[2018-02-23 17:31:21,982] [DEBUG] [blockstackd:2055] (1.140507780290304) index blockchain in /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env
[2018-02-23 17:31:21,983] [DEBUG] [session:104] (1.140507780290304) [1] Connect to bitcoind at http://blockstack@localhost:18332, timeout=300.0
[2018-02-23 17:31:21,988] [DEBUG] [namedb:91] (1.140507780290304) Connect to database '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db'
[2018-02-23 17:31:21,990] [DEBUG] [blockstackd:2080] (1.140507780290304) Begin indexing (up to 1691)
[2018-02-23 17:31:21,990] [INFO] [virtualchain_hooks:577] (1.140507780290304) Synchronizing database /tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env up to block 1691
[2018-02-23 17:31:21,990] [DEBUG] [namedb:91] (1.140507780290304) Connect to database '/tmp/blockstack-run-scenario.blockstack_integration_tests.scenarios.browser_env/blockstack-server.db'
[2018-02-23 17:31:21,992] [DEBUG] [indexer:1400] (1.140507780290304) Sync virtualchain state from 1691 to 1692
[2018-02-23 17:31:21,992] [DEBUG] [spv:744] (1.140507780290304) Synchronize testnet 1691 to 1691
[2018-02-23 17:31:21,993] [DEBUG] [spv:767] (1.140507780290304) connect to localhost:18444
[2018-02-23 17:31:21,994] [DEBUG] [spv:368] (1.140507780290304) handshake (version 60002)
[2018-02-23 17:31:21,994] [DEBUG] [spv:371] (1.140507780290304) send Version
[2018-02-23 17:31:21,996] [DEBUG] [spv:384] (1.140507780290304) handle version
[2018-02-23 17:31:21,996] [DEBUG] [spv:386] (1.140507780290304) send VerAck
[2018-02-23 17:31:21,996] [DEBUG] [spv:358] (1.140507780290304) send getheaders
[2018-02-23 18:16:43,112] [ERROR] [blocks:831] (1.140507780290304) Node disconnected.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/blocks.py", line 816, in get_bitcoin_virtual_transactions
    rc = SPVClient.sync_header_chain( headers_path, bitcoind_server, spv_last_block )
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/spv.py", line 773, in sync_header_chain
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/blockchain/bitcoin_blockchain/spv.py", line 232, in run
    self.loop()
  File "/usr/local/lib/python2.7/dist-packages/protocoin/clients.py", line 102, in loop
    raise NodeDisconnectException("Node disconnected.")
NodeDisconnectException: Node disconnected.
[2018-02-23 18:16:43,121] [DEBUG] [blocks:833] (1.140507780290304) Try again in 1.47680065326 seconds
[2018-02-23 18:16:43,183] [DEBUG] [atlas:3007] (1.140507672508160) localhost:16264: revalidate old peers
[2018-02-23 18:16:44,600] [DEBUG] [spv:744] (1.140507780290304) Synchronize testnet 1691 to 1691
[2018-02-23 18:16:44,600] [DEBUG] [spv:767] (1.140507780290304) connect to localhost:18444
[2018-02-23 18:16:44,601] [DEBUG] [spv:368] (1.140507780290304) handshake (version 60002)
[2018-02-23 18:16:44,602] [DEBUG] [spv:371] (1.140507780290304) send Version
[2018-02-23 18:16:44,603] [DEBUG] [spv:384] (1.140507780290304) handle version
[2018-02-23 18:16:44,603] [DEBUG] [spv:386] (1.140507780290304) send VerAck
[2018-02-23 18:16:44,604] [DEBUG] [spv:358] (1.140507780290304) send getheaders

```

**Comment by jcnelson** [comment]
The `bitcoind` node is locking up for some reason.  Might be environment-related.  Does this happen without Docker?  Also, can you show the contents of `/proc/1/cpuset`?
