### ISSUE TITLE
Error Post Upgrade to .19

### ISSUE THREAD

**Issue by doodlemania2** [blockstack/blockstack-core#876]
[2018-10-23 10:20:45,415] [DEBUG] [subdomains:774] (1243.1995753664) Store Subdomain(fqn=samcampbell.id.blockstack,domain=id.blockstack,seq=0,address=1E5CnJG8SA79CNQMfmy669L7F2HG6ckxRr,zfhash=1191730f3356b0c4ce0201fde898168634c0e7bb,zfindex=95899)
[2018-10-23 10:20:45,440] [ERROR] [util:289] (1243.1995753664) table subdomain_records has 12 columns but 14 values were supplied
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/util.py", line 279, in db_query_execute
    ret = cur.execute(query, values)
OperationalError: table subdomain_records has 12 columns but 14 values were supplied
[2018-10-23 10:20:45,443] [ERROR] [util:290] (1243.1995753664) FATAL: failed to execute query (INSERT OR REPLACE INTO subdomain_records VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?), ('samcampbell.id.blockstack', 'id.blockstack', 0, '1E5CnJG8SA79CNQMfmy669L7F2HG6ckxRr', '1191730f3356b0c4ce0201fde898168634c0e7bb', 'None', 546914, '40d2e3f3701b69aa7c04c029ae83a3da45f9c28a', 95899, 0, u'e59d8d581a2a712e2783838138888d36d9b5ac0e2985d3836ddb1e99a9fb172b', '', 0, 'https://registrar.blockstack.org'))
[2018-10-23 10:20:45,466] [ERROR] [util:291] (1243.1995753664)   File "/usr/local/bin/blockstack-core", line 42, in <module>
    run_blockstackd()

  File "/usr/local/lib/python2.7/dist-packages/blockstack/blockstackd.py", line 2934, in run_blockstackd
    exit_status = run_server(working_dir, foreground=args.foreground, expected_snapshots=expected_snapshots, port=args.port, api_port=args.api_port, use_api=use_api, use_indexer=use_indexer, indexer_url=args.indexer_url)

  File "/usr/local/lib/python2.7/dist-packages/blockstack/blockstackd.py", line 2428, in run_server
    running = index_blockchain(server_state, expected_snapshots=expected_snapshots)

  File "/usr/local/lib/python2.7/dist-packages/blockstack/blockstackd.py", line 2207, in index_blockchain
    rc = virtualchain_hooks.sync_blockchain(working_dir, bt_opts, current_block, server_state, expected_snapshots=expected_snapshots, tx_filter=blockstack_tx_filter)

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/nameset/virtualchain_hooks.py", line 595, in sync_blockchain
    rc = virtualchain.sync_virtualchain(bt_opts, last_block, new_db, expected_snapshots=expected_snapshots, **virtualchain_args)

  File "/usr/local/lib/python2.7/dist-packages/virtualchain/virtualchain.py", line 53, in sync_virtualchain
    rc = indexer.StateEngine.build(blockchain_opts, last_block + 1, state_engine, expected_snapshots=expected_snapshots, tx_filter=tx_filter )

  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/indexer.py", line 1463, in build
    consensus_hash = state_engine.process_block(processed_block_id, ops, expected_snapshots=expected_snapshots)

  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/indexer.py", line 1382, in process_block
    rc = self.save(block_id, consensus_hash, ops_hash, sanitized_ops, virtualchain_ops_hints, backup=backup)

  File "/usr/local/lib/python2.7/dist-packages/virtualchain/lib/indexer.py", line 853, in save
    rc = self.impl.db_save(block_id, consensus_hash, ops_hash, accepted_ops, virtualchain_ops_hints, db_state=self.state)

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/nameset/virtualchain_hooks.py", line 535, in db_save
    subdomain_index.index(block_height, block_height+1)

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/subdomains.py", line 940, in index
    self.index_discovered_zonefiles(block_end)

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/subdomains.py", line 924, in index_discovered_zonefiles
    self.process_subdomains(subseq)

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/subdomains.py", line 775, in process_subdomains
    self.subdomain_db.update_subdomain_entry(subrec, cur=cursor)

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/subdomains.py", line 1467, in update_subdomain_entry
    db_query_execute(cursor, write_cmd, args)

  File "/usr/local/lib/python2.7/dist-packages/blockstack/lib/util.py", line 291, in db_query_execute
    log.error("\n".join(traceback.format_stack()))

**Comment by doodlemania2** [comment]
Was on .0. Upgraded to .8. Will report back to see if that fixed it.

**Comment by doodlemania2** [comment]
That appears to have fixed it - thank you Jude for the rapid updates...
